//Generated By Solar Editor

import MapBaseInitState from "state/module/MapBaseInitState"

/**
 key_name = 配置项名字
 value = 值
 #<%1%># = 配置代码
 v1 = 配置项1
 v2 = 配置项2
 v3 = 配置项3
 v4 = 配置项4
 v5 = 配置项5
 v6 = 配置项6
 v7 = 配置项7
 v8 = 配置项8
 v9 = 配置项9
 */
export type data_type = {
    key_name?: string
    value?: any
    v1?: string
    v2?: string
    v3?: number
    v4?: any
    v5?: any
    v6?: any
    v7?: any
    v8?: any
    v9?: any
    [key: string]: any
}

declare global {
    type t_基础 = data_type
}

export const data: data_type[] = [
    {
        "key_name": "全图视野",
        "value": false,
        "#<%1%>#": "import MapBaseInitState from \"state/module/MapBaseInitState\";\nMapBaseInitState.config.player_see = false"
    },
    {
        "key_name": "初始镜头高度",
        "value": 3000,
        "#<%1%>#": "MapBaseInitState.config.initial_lens_height = 3000"
    },
    {
        "key_name": "开局初始金币",
        "value": 100,
        "#<%1%>#": "MapBaseInitState.config.gold = 100"
    },
    {
        "key_name": "开局初始木材",
        "value": 0,
        "#<%1%>#": "MapBaseInitState.config.wood = 0"
    },
    {
        "key_name": "开局初始人口",
        "value": 0,
        "#<%1%>#": "MapBaseInitState.config.population = 0"
    },
    {
        "key_name": "开局提示文本",
        "value": " ",
        "#<%1%>#": "MapBaseInitState.config.start_text = ' '"
    },
    {
        "key_name": "开启玩家赏金奖励",
        "value": "11,12",
        "#<%1%>#": "MapBaseInitState.config.open_gives_bounty = [11,12]"
    },
    {
        "key_name": "开局起始点创建单位",
        "value": "A3zz",
        "#<%1%>#": "MapBaseInitState.config.start_CreateUnitType = 'A3zz'"
    },
    {
        "key_name": "地图等级平方奖励金币",
        "value": 50,
        "#<%1%>#": "MapBaseInitState.config.goldForMapLvl = 50"
    },
    {
        "key_name": "收藏地图开局奖励金币",
        "value": 0,
        "#<%1%>#": "MapBaseInitState.config.addGoldByCollect = 0"
    },
    {
        "key_name": "输入礼包码获得金币",
        "value": "n:金币兑换码,v:100",
        "#<%1%>#": "MapBaseInitState.config.addGoldsOnChat.yyds = {\"n\":\"金币兑换码\",\"v\":100}",
        "v1": "yyds",
        "v2": "金币兑换码",
        "v3": 100
    },
    {
        "key_name": "输入礼包码获得金币",
        "value": "n:金币兑换码,v:10",
        "#<%1%>#": "MapBaseInitState.config.addGoldsOnChat.我是菜鸟 = {\"n\":\"金币兑换码\",\"v\":10}",
        "v1": "我是菜鸟",
        "v2": "金币兑换码",
        "v3": 10
    },
    {
        "key_name": "输入礼包码获得木材",
        "value": "n:木材兑换码,v:1",
        "#<%1%>#": "MapBaseInitState.config.addLumbersOnChat.我要木材 = {\"n\":\"木材兑换码\",\"v\":1}",
        "v1": "我要木材",
        "v2": "木材兑换码",
        "v3": 1
    }
]
export const d_基础 = data;


//code
export default function () {
    MapBaseInitState.config.player_see = false
    MapBaseInitState.config.initial_lens_height = 3000
    MapBaseInitState.config.gold = 0
    MapBaseInitState.config.wood = 0
    MapBaseInitState.config.population = 0
    MapBaseInitState.config.start_text = ' '
    MapBaseInitState.config.open_gives_bounty = [11, 12]
    MapBaseInitState.config.start_CreateUnitType = 'A3zz'
    MapBaseInitState.config.goldForMapLvl = 0
    MapBaseInitState.config.addGoldByCollect = 0
    MapBaseInitState.config.addGoldsOnChat.yyds = {"n": "金币兑换码", "v": 100}
    MapBaseInitState.config.addGoldsOnChat.我是菜鸟 = {"n": "金币兑换码", "v": 10}
    MapBaseInitState.config.addLumbersOnChat.我要木材 = {"n": "木材兑换码", "v": 1}
}
