//Generated By Solar Editor

import UiProperty from "gui/UiProperty"
/**
	Name = 属性词条
	key = 字段
	childKey = 子字段
	showPercentage = 是否百分比
	add_show_num = 显示数值修正
*/
export type data_type = {
	Name?: string
	key?: string
	childKey?: any
	showPercentage?: boolean
	add_show_num?: number
    [key:string]: any
}

declare global {
    type t_属性面板ui显示 = data_type
}

export const data: data_type[] = [
	{
		"Name":"|cffff0000伤害增幅|r",
		"key":"damage_increased",
		"showPercentage":true
	},
	{
		"Name":"|cffff0000主炮射程附加|r",
		"key":"autoMissileAttackRange"
	},
	{
		"Name":"|cffff0000主炮射程增幅|r",
		"key":"autoMissileAttackRange_p",
		"showPercentage":true
	},
	{
		"Name":"|cffff0000主炮射速增幅|r",
		"key":"autoMissileAttackSpeed",
		"showPercentage":true
	},
	{
		"Name":"|cffff0000攻击增幅|r",
		"key":"attack_p",
		"showPercentage":true
	},
	{
		"Name":"|cffff0000力量增幅|r",
		"key":"strength_p",
		"showPercentage":true
	},
	{
		"Name":"|cffff0000敏捷增幅|r",
		"key":"agility_p",
		"showPercentage":true
	},
	{
		"Name":"|cffff0000智力增幅|r",
		"key":"intelligence_p",
		"showPercentage":true
	},
	{
		"Name":"|cffff0000全属性增幅|r",
		"key":"full_property_p",
		"showPercentage":true
	},
	{
		"Name":"|cff00b050复活次数|r",
		"key":"死亡后立刻复活"
	},
	{
		"Name":"|cff00b050伤害减免|r",
		"key":"damage_reduction",
		"showPercentage":true
	},
	{
		"Name":"|cff00b050护甲增幅|r",
		"key":"def_p",
		"showPercentage":true
	},
	{
		"Name":"|cff00b050生命回复|r",
		"key":"reply_life_on_pers"
	},
	{
		"Name":"|cff00b050生命回复(比例)|r",
		"key":"reply_life_by_p_on_pers",
		"showPercentage":true
	},
	{
		"Name":"|cffd08953杀敌加攻击|r",
		"key":"add_attack_on_kill"
	},
	{
		"Name":"|cffd08953每秒加攻击|r",
		"key":"add_attack_on_pers"
	},
	{
		"Name":"|cffd08953杀敌加生命|r",
		"key":"add_max_life_on_kill"
	},
	{
		"Name":"|cffd08953每秒加生命|r",
		"key":"add_max_life_on_pers"
	},
	{
		"Name":"|cffd08953杀敌加力量|r",
		"key":"add_strength_on_kill"
	},
	{
		"Name":"|cffd08953杀敌加力量增幅|r",
		"key":"add_strength_on_kill_p",
		"showPercentage":true
	},
	{
		"Name":"|cffd08953杀敌加敏捷|r",
		"key":"add_agility_on_kill"
	},
	{
		"Name":"|cffd08953杀敌加敏捷增幅|r",
		"key":"add_agility_on_kill_p",
		"showPercentage":true
	},
	{
		"Name":"|cffd08953杀敌加智力|r",
		"key":"add_intelligence_on_kill"
	},
	{
		"Name":"|cffd08953杀敌加智力增幅|r",
		"key":"add_intelligence_on_kill_p",
		"showPercentage":true
	},
	{
		"Name":"|cffd08953每秒加力量|r",
		"key":"add_strength_on_pers"
	},
	{
		"Name":"|cffd08953每秒加敏捷|r",
		"key":"add_agility_on_pers"
	},
	{
		"Name":"|cffd08953每秒加智力|r",
		"key":"add_intelligence_on_pers"
	},
	{
		"Name":"|cffffff00存档掉率|r",
		"key":"存档掉率",
		"showPercentage":true
	},
	{
		"Name":"|cffffff00金币效率|r",
		"key":"earn_gold_p",
		"showPercentage":true
	},
	{
		"Name":"|cffffff00经验倍率增幅|r",
		"key":"经验倍率",
		"showPercentage":true
	},
	{
		"Name":"|cffffff00杀敌经验附加|r",
		"key":"杀敌经验"
	},
	{
		"Name":"|cffffff00杀敌金币|r",
		"key":"add_gold_on_kill"
	},
	{
		"Name":"|cffffff00船长信件吞噬上限|r",
		"key":"吞噬船长上限",
		"add_show_num":2
	},
	{
		"Name":"|cffffff00吞天石吞噬上限|r",
		"key":"吞天石吞噬上限",
		"add_show_num":2
	}
]
export const d_属性面板ui显示 = data;


//code
export default function(){

 UiProperty.config = []
 for (let datum of data) {
  if (datum.key){
   UiProperty.config.push(datum as any)
  }
 }
}
