//Generated By Solar Editor

import SolarNewItemsFormulaState from "state/common/SolarNewItemsFormulaState"
/**
	key_name = 备注
	id = 合成物品id
	NewItemsFormulaState_materials = 合成材料id
	#<%1%># = 配置代码
*/
export type data_type = {
	key_name?: any
	id?: string
	NewItemsFormulaState_materials?: string
    [key:string]: any
}

declare global {
    type t_物品合成 = data_type
}

export const data: data_type[] = [
	{
		"id":"船身Lv10",
		"NewItemsFormulaState_materials":"船身Lv9:2",
		"#<%1%>#":"SolarNewItemsFormulaState.config.船身Lv10 = {material:{\"船身Lv9\":2}}"
	},
	{
		"id":"甲板Lv10",
		"NewItemsFormulaState_materials":"甲板Lv9:2",
		"#<%1%>#":"SolarNewItemsFormulaState.config.甲板Lv10 = {material:{\"甲板Lv9\":2}}"
	},
	{
		"id":"马达Lv10",
		"NewItemsFormulaState_materials":"马达Lv9:2",
		"#<%1%>#":"SolarNewItemsFormulaState.config.马达Lv10 = {material:{\"马达Lv9\":2}}"
	},
	{
		"id":"炮弹Lv10",
		"NewItemsFormulaState_materials":"炮弹Lv9:2",
		"#<%1%>#":"SolarNewItemsFormulaState.config.炮弹Lv10 = {material:{\"炮弹Lv9\":2}}"
	},
	{
		"id":"船头Lv10",
		"NewItemsFormulaState_materials":"船头Lv9:2",
		"#<%1%>#":"SolarNewItemsFormulaState.config.船头Lv10 = {material:{\"船头Lv9\":2}}"
	},
	{
		"id":"船帆Lv10",
		"NewItemsFormulaState_materials":"船帆Lv9:2",
		"#<%1%>#":"SolarNewItemsFormulaState.config.船帆Lv10 = {material:{\"船帆Lv9\":2}}"
	},
	{
		"id":"桅杆Lv10",
		"NewItemsFormulaState_materials":"桅杆Lv9:2",
		"#<%1%>#":"SolarNewItemsFormulaState.config.桅杆Lv10 = {material:{\"桅杆Lv9\":2}}"
	},
	{
		"id":"修理工Lv10",
		"NewItemsFormulaState_materials":"修理工Lv9:2",
		"#<%1%>#":"SolarNewItemsFormulaState.config.修理工Lv10 = {material:{\"修理工Lv9\":2}}"
	}
]
export const d_物品合成 = data;


//code
export default function(){
	SolarNewItemsFormulaState.config.船身Lv10 = {material:{"船身Lv9":2}}
	SolarNewItemsFormulaState.config.甲板Lv10 = {material:{"甲板Lv9":2}}
	SolarNewItemsFormulaState.config.马达Lv10 = {material:{"马达Lv9":2}}
	SolarNewItemsFormulaState.config.炮弹Lv10 = {material:{"炮弹Lv9":2}}
	SolarNewItemsFormulaState.config.船头Lv10 = {material:{"船头Lv9":2}}
	SolarNewItemsFormulaState.config.船帆Lv10 = {material:{"船帆Lv9":2}}
	SolarNewItemsFormulaState.config.桅杆Lv10 = {material:{"桅杆Lv9":2}}
	SolarNewItemsFormulaState.config.修理工Lv10 = {material:{"修理工Lv9":2}}
}
