//Generated By Solar Editor

/**
	id = id
	_parent = 父id
	Name = 名字
	Sellitems = 售出物品
	scale = 缩放
	modelScale = 模型缩放
	file = 模型文件
	abilList = 技能
	uberSplat = 建筑路径纹理
	buildingShadow = 建筑阴影
	movetp = 类型
*/
export type data_type = {
	id?: string
	_parent?: string
	Name?: string
	Sellitems?: string
	scale?: number
	modelScale?: number
	file?: string
	abilList?: string
	uberSplat?: string
	buildingShadow?: string
	movetp?: string
    [key:string]: any
}

declare global {
    type t_商店npc = data_type
}

export const data: data_type[] = [
	{
		"id":"a43y",
		"_parent":"ngme",
		"Name":"船身(生命)",
		"Sellitems":"a41w,a41x,a41y,a41z,a420,a421,a422,a423,a424",
		"scale":2,
		"modelScale":2,
		"file":"units\\human\\Arthas\\Arthas.mdx",
		"abilList":"Aneu,Avul,Apit",
		"uberSplat":"",
		"buildingShadow":"",
		"movetp":"",
		"Tip":"船身(生命)"
	},
	{
		"id":"a43z",
		"_parent":"ngme",
		"Name":"甲板(护甲)",
		"Sellitems":"a426,a427,a428,a429,a42a,a42b,a42c,a42d,a42e",
		"scale":2,
		"modelScale":2,
		"file":"units\\human\\Arthas\\Arthas.mdx",
		"abilList":"Aneu,Avul,Apit",
		"uberSplat":"",
		"buildingShadow":"",
		"movetp":"",
		"Tip":"甲板(护甲)"
	},
	{
		"id":"a440",
		"_parent":"ngme",
		"Name":"马达(移速)",
		"Sellitems":"a42g,a42h,a42j,a42k,a42l,a42m,a42n,a42p,a42q",
		"scale":2,
		"modelScale":2,
		"file":"units\\human\\Arthas\\Arthas.mdx",
		"abilList":"Aneu,Avul,Apit",
		"uberSplat":"",
		"buildingShadow":"",
		"movetp":"",
		"Tip":"马达(移速)"
	},
	{
		"id":"a441",
		"_parent":"ngme",
		"Name":"炮弹(攻击)",
		"Sellitems":"a42s,a42t,a42u,a42v,a42w,a42x,a42y,a42z,a430",
		"scale":1.4,
		"modelScale":2,
		"file":"units\\human\\WarWagon\\WarWagon.mdx",
		"abilList":"Aneu,Avul,Apit",
		"uberSplat":"",
		"buildingShadow":"",
		"movetp":"",
		"Tip":"炮弹(攻击)"
	},
	{
		"id":"a442",
		"_parent":"ngme",
		"Name":"船头(力量)",
		"Sellitems":"a432,a433,a434,a435,a436,a437,a438,a439,a43a",
		"scale":2,
		"modelScale":2,
		"file":"units\\human\\Jaina\\Jaina.mdl",
		"abilList":"Aneu,Avul,Apit",
		"uberSplat":"",
		"buildingShadow":"",
		"movetp":"",
		"Tip":"船头(力量)"
	},
	{
		"id":"a443",
		"_parent":"ngme",
		"Name":"船帆(敏捷)",
		"Sellitems":"a43c,a43d,a43e,a43f,a43g,a43h,a43j,a43k,a43l",
		"scale":2,
		"modelScale":2,
		"file":"units\\human\\Jaina\\Jaina.mdl",
		"abilList":"Aneu,Avul,Apit",
		"uberSplat":"",
		"buildingShadow":"",
		"movetp":"",
		"Tip":"船帆(敏捷)"
	},
	{
		"id":"a444",
		"_parent":"ngme",
		"Name":"桅杆(智力)",
		"Sellitems":"a43n,a43p,a43q,a43r,a43s,a43t,a43u,a43v,a43w",
		"scale":2,
		"modelScale":2,
		"file":"units\\human\\Jaina\\Jaina.mdl",
		"abilList":"Aneu,Avul,Apit",
		"uberSplat":"",
		"buildingShadow":"",
		"movetp":"",
		"Tip":"桅杆(智力)"
	},
	{
		"id":"a446",
		"_parent":"ngme",
		"Name":"修理工(恢复)",
		"Sellitems":"a44b,a44c,a44d,a44e,a44f,a44g,a44h,a44j,a44k",
		"scale":2.3,
		"modelScale":2,
		"file":"Units\\Creeps\\HeroTinkerRobot\\HeroTinkerRobot.mdx",
		"abilList":"Aneu,Avul,Apit",
		"uberSplat":"",
		"buildingShadow":"",
		"movetp":"",
		"Tip":"修理工(恢复)"
	},
	{
		"id":"a449",
		"_parent":"ngme",
		"Name":"船长(打钱)",
		"Sellitems":"a41s,a41t,a41u,a41v",
		"scale":2,
		"modelScale":2,
		"file":"units\\creeps\\Medivh\\Medivh.mdx",
		"abilList":"Aneu,Avul,Apit",
		"uberSplat":"",
		"buildingShadow":"",
		"movetp":"",
		"Tip":"船长(打钱)"
	},
	{
		"id":"a44a",
		"_parent":"ngme",
		"Name":"海上奇珍",
		"Sellitems":"a3zx",
		"scale":2,
		"modelScale":2,
		"file":"单位\\海上奇珍\\海上奇珍.mdx",
		"abilList":"Aneu,Avul,Apit",
		"uberSplat":"",
		"buildingShadow":"",
		"movetp":"",
		"Tip":"海上奇珍"
	}
]
export const d_商店npc = data;


//code
export default function(){
}
