//Generated By Solar Editor

/**
	id = id
	_parent = 父id
	Name = 名字
	dmgplus1 = 攻击力
	HP = 生命值
	def = 基础护甲
	rangeN1 = 攻击范围
	movetp = 类型
	modelScale = 模型缩放
	Art = 图标 - 普通
	file = 模型文件
*/
export type data_type = {
	id?: string
	_parent?: string
	Name?: string
	dmgplus1?: number
	HP?: number
	def?: number
	rangeN1?: number
	movetp?: string
	modelScale?: number
	Art?: any
	file?: string
    [key:string]: any
}

declare global {
    type t_大触须 = data_type
}

export const data: data_type[] = [
	{
		"id":"a45e",
		"_parent":"nfgt",
		"Name":"克苏鲁的触手",
		"dmgplus1":50000,
		"HP":2000000,
		"def":0,
		"rangeN1":300,
		"movetp":"amph",
		"modelScale":1.2,
		"file":"model\\进攻怪\\大触手.mdx",
		"Ubertip":"克苏鲁的触手"
	}
]
export const d_大触须 = data;


//code
export default function(){
}
