//Generated By Solar Editor

import 英雄属性书 from "state/物品/英雄属性书"
/**
	id = id
	_parent = 父id
	Name = 名字
	type = 类型
	val = 数值
	HP = 生命值
	goldcost = 黄金消耗
	lumbercost = 木材消耗
	Art = 图标 - 普通
	abilList = 技能
	Level = 等级
	stockMax = 最大库存量
	stockRegen = 购买时间间隔
*/
export type data_type = {
	id?: string
	_parent?: string
	Name?: string
	type?: string
	val?: number
	HP?: number
	goldcost?: number
	lumbercost?: number
	Art?: string
	abilList?: string
	Level?: number
	stockMax?: number
	stockRegen?: number
    [key:string]: any
}

declare global {
    type t_属性书 = data_type
}

export const data: data_type[] = [
	{
		"id":"a3nx",
		"_parent":"manh",
		"Name":"|cffEEE8AA知识之书+1000",
		"type":"FULLP",
		"val":1000,
		"HP":100,
		"goldcost":100000,
		"lumbercost":0,
		"Art":"ReplaceableTextures\\CommandButtons\\BTNTomeRed.blp",
		"abilList":" ",
		"Level":8,
		"stockMax":99,
		"stockRegen":1,
		"Ubertip":"|cffEEE8AA知识之书+1000",
		"Description":"|cffEEE8AA知识之书+1000",
		"Tip":"|cffEEE8AA知识之书+1000"
	}
]
export const d_属性书 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            英雄属性书.config[datum.id] = {type: datum.type, val: datum.val}
        }
    }
}
