//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	templateType = 基础模板
	name = 名字
	icon = 图标
	model = 模型
	colorR = 红色通道
	colorG = 绿色通道
	colorB = 蓝色通道
	modelScale = 模型缩放
	moveSpeed = 移速
	damage = 攻击力
	maxLife = 生命值
	maxMana = 最大魔法值
	def = 护甲
	damageCd = 攻击间隔
	range = 攻击范围
	missileModel = 投射物模型
	moveType = 移动类型
	flyHeight = 飞行高度
	goldCost = 金币消耗
	describe = 提示说明
*/
export type data_type = {
	id?: string
	class?: string
	templateType?: string
	name?: string
	icon?: string
	model?: string
	colorR?: number
	colorG?: number
	colorB?: number
	modelScale?: number
	moveSpeed?: number
	damage?: number
	maxLife?: number
	maxMana?: any
	def?: number
	damageCd?: number
	range?: number
	missileModel?: string
	moveType?: string
	flyHeight?: any
	goldCost?: any
	describe?: string
    [key:string]: any
}

declare global {
    type t_擂台挑战怪 = data_type
}

export const data: data_type[] = [
	{
		"id":"擂台小木船",
		"class":"擂台挑战怪",
		"templateType":"远程敏捷英雄",
		"name":"擂台小木船",
		"icon":"进攻怪图标\\01小木船.blp",
		"model":"model\\进攻怪\\小木船.mdx",
		"colorR":255,
		"colorG":0,
		"colorB":0,
		"modelScale":2,
		"moveSpeed":522,
		"damage":200,
		"maxLife":2000,
		"def":0,
		"damageCd":0.8,
		"range":125,
		"missileModel":"Abilities\\Weapons\\HarpyMissile\\HarpyMissile.mdx",
		"moveType":"amph",
		"describe":"攻击/血量x10，奖励全队2000金币。"
	},
	{
		"id":"擂台驱逐舰",
		"class":"擂台挑战怪",
		"templateType":"远程敏捷英雄",
		"name":"擂台驱逐舰",
		"icon":"进攻怪图标\\02驱逐舰.blp",
		"model":"units\\nightelf\\NightElfTransportShip\\NightElfTransportShip.mdl",
		"colorR":255,
		"colorG":0,
		"colorB":0,
		"modelScale":2,
		"moveSpeed":522,
		"damage":600.0,
		"maxLife":6000.0,
		"def":0,
		"damageCd":0.8,
		"range":200,
		"missileModel":"Abilities\\Weapons\\Banditmissile\\Banditmissile.mdx",
		"moveType":"amph",
		"describe":"攻击/血量x10，奖励全队30秒内无敌。"
	},
	{
		"id":"擂台护卫舰",
		"class":"擂台挑战怪",
		"templateType":"远程敏捷英雄",
		"name":"擂台护卫舰",
		"icon":"进攻怪图标\\03护卫舰.blp",
		"model":"units\\creeps\\HumanDestroyerShip\\HumanDestroyerShip.mdl",
		"colorR":255,
		"colorG":0,
		"colorB":0,
		"modelScale":2,
		"moveSpeed":522,
		"damage":1200.0,
		"maxLife":12000.0,
		"def":0,
		"damageCd":0.8,
		"range":300,
		"missileModel":"Abilities\\Weapons\\FireballMissile\\FireballMissile.mdx",
		"moveType":"amph",
		"describe":"攻击/血量x10，奖励全队金币收益+25%。"
	},
	{
		"id":"擂台巡洋舰",
		"class":"擂台挑战怪",
		"templateType":"远程敏捷英雄",
		"name":"擂台巡洋舰",
		"icon":"进攻怪图标\\04巡航舰.blp",
		"model":"model\\进攻怪\\巡洋舰.mdx",
		"colorR":255,
		"colorG":0,
		"colorB":0,
		"modelScale":2,
		"moveSpeed":522,
		"damage":2400.0,
		"maxLife":24000.0,
		"def":0,
		"damageCd":0.8,
		"range":400,
		"missileModel":"Abilities\\Weapons\\RedDragonBreath\\RedDragonMissile.mdx",
		"moveType":"amph",
		"describe":"攻击/血量x10，奖励全队5000金币。"
	},
	{
		"id":"擂台重舰",
		"class":"擂台挑战怪",
		"templateType":"远程敏捷英雄",
		"name":"擂台重舰",
		"icon":"进攻怪图标\\05重舰.blp",
		"model":"model\\进攻怪\\重舰.mdx",
		"colorR":255,
		"colorG":0,
		"colorB":0,
		"modelScale":2,
		"moveSpeed":522,
		"damage":4800.0,
		"maxLife":48000.0,
		"def":20,
		"damageCd":0.8,
		"range":400,
		"missileModel":"abilities\\weapons\\catapult\\catapultmissile.mdx",
		"moveType":"amph",
		"describe":"攻击/血量x10，奖励全队20%攻击力加成"
	},
	{
		"id":"擂台海龟",
		"class":"擂台挑战怪",
		"templateType":"远程敏捷英雄",
		"name":"擂台海龟",
		"icon":"进攻怪图标\\06海龟.blp",
		"model":"model\\进攻怪\\海龟.mdx",
		"colorR":255,
		"colorG":0,
		"colorB":0,
		"modelScale":2,
		"moveSpeed":522,
		"damage":9600.0,
		"maxLife":96000.0,
		"def":20,
		"damageCd":0.8,
		"range":125,
		"missileModel":"Abilities\\Weapons\\ChimaeraLightningMissile\\ChimaeraLightningMissile.mdx",
		"moveType":"amph",
		"describe":"攻击/血量x10，奖励全队15秒内护甲+999。"
	},
	{
		"id":"擂台石像鬼",
		"class":"擂台挑战怪",
		"templateType":"远程敏捷英雄",
		"name":"擂台石像鬼",
		"icon":"进攻怪图标\\07石像鬼.blp",
		"model":"model\\进攻怪\\石像鬼.mdx",
		"colorR":255,
		"colorG":0,
		"colorB":0,
		"modelScale":2,
		"moveSpeed":522,
		"damage":19200.0,
		"maxLife":288000.0,
		"def":0,
		"damageCd":0.5,
		"range":150,
		"missileModel":"Abilities\\Weapons\\Axe\\AxeMissile.mdx",
		"moveType":"amph",
		"describe":"攻击/血量x10，奖励击杀者进化为剑圣。"
	},
	{
		"id":"擂台九头蛇",
		"class":"擂台挑战怪",
		"templateType":"远程敏捷英雄",
		"name":"擂台九头蛇",
		"icon":"进攻怪图标\\08九头蛇.blp",
		"model":"Units\\Creeps\\Hydra\\Hydra.mdx",
		"colorR":255,
		"colorG":0,
		"colorB":0,
		"modelScale":2,
		"moveSpeed":522,
		"damage":38400.0,
		"maxLife":864000.0,
		"def":20,
		"damageCd":1,
		"range":300,
		"missileModel":"Abilities\\Weapons\\NecromancerMissile\\NecromancerMissile.mdx",
		"moveType":"amph",
		"describe":"攻击/血量x10，奖励当前全队15秒内无敌。"
	},
	{
		"id":"擂台触手",
		"class":"擂台挑战怪",
		"templateType":"远程敏捷英雄",
		"name":"擂台触手",
		"icon":"进攻怪图标\\09触手.blp",
		"model":"model\\进攻怪\\大触手.mdx",
		"colorR":255,
		"colorG":0,
		"colorB":0,
		"modelScale":2,
		"moveSpeed":522,
		"damage":76800.0,
		"maxLife":2592000.0,
		"def":50,
		"damageCd":0.8,
		"range":400,
		"missileModel":"Abilities\\Weapons\\AncestralGuardianMissile\\AncestralGuardianMissile.mdx",
		"moveType":"amph",
		"describe":"攻击/血量x10，奖励当前全队15秒内攻击力+300%"
	}
]
export const d_擂台挑战怪 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
