//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	templateType = 基础模板
	name = 名字
	icon = 图标
	model = 模型
	colorR = 红色通道
	colorG = 绿色通道
	colorB = 蓝色通道
	modelScale = 模型缩放
	moveSpeed = 移速
	maxLife = 生命值
	maxMana = 最大魔法值
	def = 护甲
	damage = 攻击力
	damageCd = 攻击间隔
	range = 攻击范围
	missileModel = 投射物模型
	moveType = 移动类型
	flyHeight = 飞行高度
	goldCost = 金币消耗
	describe = 提示说明
*/
export type data_type = {
	id?: string
	class?: string
	templateType?: string
	name?: string
	icon?: string
	model?: string
	colorR?: any
	colorG?: any
	colorB?: any
	modelScale?: any
	moveSpeed?: any
	maxLife?: any
	maxMana?: any
	def?: any
	damage?: any
	damageCd?: any
	range?: any
	missileModel?: any
	moveType?: any
	flyHeight?: any
	goldCost?: any
	describe?: any
    [key:string]: any
}

declare global {
    type t_擂台单位挑战NPC = data_type
}

export const data: data_type[] = [
	{
		"id":"擂台挑战",
		"class":"擂台挑战",
		"templateType":"NPC单位",
		"name":"|cffff0000擂台挑战",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"units\\human\\Jaina\\Jaina.mdx"
	}
]
export const d_擂台单位挑战NPC = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
