//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
import 造成伤害时附带目标最大生命值比例的伤害 from "state/单位/造成伤害时附带目标最大生命值比例的伤害"
/**
	id = 自定义id
	class = 类别
	templateType = 基础模板
	name = 名字
	icon = 图标
	model = 模型
	abilities = 技能列表
	colorR = 红色通道
	colorG = 绿色通道
	colorB = 蓝色通道
	modelScale = 模型缩放
	bounty = 奖金
	moveSpeed = 移速
	maxLife = 生命值
	def = 护甲
	damage = 攻击力
	damageCd = 攻击间隔
	range = 攻击范围
	acquireRange = 主动攻击范围
	missileModel = 投射物模型
	moveType = 移动类型
	afterDeathBirthUnits = 死亡后诞生的单位
	flyHeight = 飞行高度
	goldCost = 金币消耗
	附带伤害 = 附带伤害
	maxMana = 最大魔法值
	describe = 提示说明
*/
export type data_type = {
	id?: string
	class?: string
	templateType?: string
	name?: string
	icon?: string
	model?: string
	abilities?: any
	colorR?: number
	colorG?: number
	colorB?: number
	modelScale?: number
	bounty?: number
	moveSpeed?: number
	maxLife?: number
	def?: number
	damage?: number
	damageCd?: number
	range?: number
	acquireRange?: number
	missileModel?: string
	moveType?: string
	afterDeathBirthUnits?: any
	flyHeight?: any
	goldCost?: any
	附带伤害?: number
	maxMana?: any
	describe?: any
    [key:string]: any
}

declare global {
    type t_深度海域怪 = data_type
}

export const data: data_type[] = [
	{
		"id":"深度海域怪1",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"黑色船只",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\小木船.mdx",
		"colorR":0,
		"colorG":0,
		"colorB":0,
		"modelScale":2,
		"bounty":0,
		"moveSpeed":250,
		"maxLife":2000000,
		"def":2000,
		"damage":500000,
		"damageCd":1,
		"range":600,
		"acquireRange":5000,
		"missileModel":"Abilities\\Weapons\\HarpyMissile\\HarpyMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.05
	},
	{
		"id":"深度海域怪2",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"触手",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"Units\\Creeps\\ForgottenOne\\ForgottenOneTent.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":350,
		"maxLife":2400000.0,
		"def":2200.0,
		"damage":600000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\Banditmissile\\Banditmissile.mdx",
		"moveType":"amph",
		"附带伤害":0.060000000000000005
	},
	{
		"id":"深度海域怪3",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"血红触手",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\大触手.mdx",
		"colorR":255,
		"colorG":0,
		"colorB":0,
		"modelScale":2,
		"bounty":0,
		"moveSpeed":350,
		"maxLife":2880000.0,
		"def":2400.0,
		"damage":700000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\FireballMissile\\FireballMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.07
	},
	{
		"id":"深度海域怪4",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"迷宫怪物",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\巡洋舰.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":440,
		"maxLife":3456000.0,
		"def":2600.0,
		"damage":800000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\RedDragonBreath\\RedDragonMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.08
	},
	{
		"id":"深度海域怪5",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"世外桃源怪物",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\重舰.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":260,
		"maxLife":4147200.0,
		"def":2800.0,
		"damage":900000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"abilities\\weapons\\catapult\\catapultmissile.mdx",
		"moveType":"amph",
		"附带伤害":0.09
	},
	{
		"id":"深度海域怪6",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪6",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\海龟.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":250,
		"maxLife":4976640.0,
		"def":3000.0,
		"damage":1000000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\ChimaeraLightningMissile\\ChimaeraLightningMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.09999999999999999
	},
	{
		"id":"深度海域怪7",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪7",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\石像鬼.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":250,
		"maxLife":5971968.0,
		"def":3200.0,
		"damage":1100000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\Axe\\AxeMissile.mdx",
		"moveType":"amph",
		"flyHeight":200,
		"附带伤害":0.10999999999999999
	},
	{
		"id":"深度海域怪8",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪8",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"Units\\Creeps\\Hydra\\Hydra.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":250,
		"maxLife":7166361.6,
		"def":3400.0,
		"damage":1200000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\NecromancerMissile\\NecromancerMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.11999999999999998
	},
	{
		"id":"深度海域怪9",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪9",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"Units\\Creeps\\ForgottenOne\\ForgottenOneTent.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":0,
		"maxLife":8599633.92,
		"def":3600.0,
		"damage":1300000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\AncestralGuardianMissile\\AncestralGuardianMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.12999999999999998
	},
	{
		"id":"深度海域怪10",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪10",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\飞蛇.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":522,
		"maxLife":1.0319560704E7,
		"def":3800.0,
		"damage":1400000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\GreenDragonMissile\\GreenDragonMissile.mdx",
		"moveType":"amph",
		"flyHeight":200,
		"附带伤害":0.13999999999999999
	},
	{
		"id":"深度海域怪11",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪11",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\娜迦步兵.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":250,
		"maxLife":1.23834728448E7,
		"def":4000.0,
		"damage":1500000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\FragDriller\\FragDriller.mdx",
		"moveType":"amph",
		"附带伤害":0.15
	},
	{
		"id":"深度海域怪12",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪12",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\太空堡垒.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":250,
		"maxLife":1.486016741376E7,
		"def":4200.0,
		"damage":1600000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\BansheeMissile\\BansheeMissile.mdx",
		"moveType":"amph",
		"flyHeight":200,
		"附带伤害":0.16
	},
	{
		"id":"深度海域怪13",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪13",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"Units\\Critters\\Hydralisk\\Hydralisk.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":420,
		"maxLife":1.7832200896512E7,
		"def":4400.0,
		"damage":1700000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\KeeperGroveMissile\\KeeperGroveMissile.mdl",
		"moveType":"amph",
		"附带伤害":0.17
	},
	{
		"id":"深度海域怪14",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪14",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\阴影.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":300,
		"maxLife":2.13986410758144E7,
		"def":4600.0,
		"damage":1800000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\GargoyleMissile\\GargoyleMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.18000000000000002
	},
	{
		"id":"深度海域怪15",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪15",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\克苏恩眼睛.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":200,
		"maxLife":2.567836929097728E7,
		"def":4800.0,
		"damage":1900000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\MakuraMissile\\MakuraMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.19000000000000003
	},
	{
		"id":"深度海域怪16",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪16",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\海妖HD3.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":200,
		"maxLife":3.081404314917276E7,
		"def":5000.0,
		"damage":2000000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\MakuraMissile\\MakuraMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.20000000000000004
	},
	{
		"id":"深度海域怪17",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪17",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\女妖.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":200,
		"maxLife":3.697685177900736E7,
		"def":5200.0,
		"damage":2100000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\MakuraMissile\\MakuraMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.21000000000000005
	},
	{
		"id":"深度海域怪18",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪18",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\克苏恩.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":200,
		"maxLife":4.437222213480888E7,
		"def":5400.0,
		"damage":2200000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\MakuraMissile\\MakuraMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.22000000000000006
	},
	{
		"id":"深度海域怪19",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪19",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\克苏恩眼睛.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":200,
		"maxLife":5.324666656177068E7,
		"def":5600.0,
		"damage":2300000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\MakuraMissile\\MakuraMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.23000000000000007
	},
	{
		"id":"深度海域怪20",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪20",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\克苏恩眼睛.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":200,
		"maxLife":6.389599987412484E7,
		"def":5800.0,
		"damage":2400000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\MakuraMissile\\MakuraMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.24000000000000007
	},
	{
		"id":"深度海域怪21",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪21",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\克苏恩眼睛.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":200,
		"maxLife":7.667519984894976E7,
		"def":6000.0,
		"damage":2500000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\MakuraMissile\\MakuraMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.25000000000000006
	},
	{
		"id":"深度海域怪22",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪22",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\克苏恩眼睛.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":200,
		"maxLife":9.201023981873976E7,
		"def":6200.0,
		"damage":2600000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\MakuraMissile\\MakuraMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.26000000000000006
	},
	{
		"id":"深度海域怪23",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪23",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\克苏恩眼睛.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":200,
		"maxLife":1.1041228778248776E8,
		"def":6400.0,
		"damage":2700000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\MakuraMissile\\MakuraMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.2700000000000001
	},
	{
		"id":"深度海域怪24",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪24",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\克苏恩眼睛.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":200,
		"maxLife":1.324947453389856E8,
		"def":6600.0,
		"damage":2800000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\MakuraMissile\\MakuraMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.2800000000000001
	},
	{
		"id":"深度海域怪25",
		"class":"深度海域怪",
		"templateType":"远程单位",
		"name":"|cffff0000深度海域怪25",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\克苏恩眼睛.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":0,
		"moveSpeed":200,
		"maxLife":1.589936944067832E8,
		"def":6800.0,
		"damage":2900000.0,
		"damageCd":1,
		"range":600,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\MakuraMissile\\MakuraMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.2900000000000001
	}
]
export const d_深度海域怪 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }

    for (let d of data) {
        if (d.id && d.附带伤害) {
            造成伤害时附带目标最大生命值比例的伤害.config[d.id] = d.附带伤害
        }
    }
}
