//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	templateType = 基础模板
	name = 名字
	describe = 提示说明
	icon = 图标
	model = 模型
	modelScale = 模型缩放
	flyHeight = 飞行高度
	sellItems = (内置有效)售卖演员物品类型id列表
*/
export type data_type = {
	id?: string
	class?: string
	templateType?: string
	name?: string
	describe?: any
	icon?: string
	model?: string
	modelScale?: number
	flyHeight?: any
	sellItems?: any[]
    [key:string]: any
}

declare global {
    type t_演员物品售卖NPC = data_type
}

export const data: data_type[] = [
	{
		"id":"船长合成提示",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"高级船长(预览)",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"units\\creeps\\Medivh\\Medivh.mdx",
		"modelScale":2,
		"sellItems":[
			"黑胡子",
			"白胡子",
			"雷霆支配者",
			"麦哲伦",
			"艾尼路",
			"娜米",
			"鲁灰",
			"小丑",
			"两仪式",
			"炮姐"
		]
	},
	{
		"id":"船长合成提示2",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"高级船长(预览)",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"units\\creeps\\Medivh\\Medivh.mdx",
		"modelScale":2,
		"sellItems":[
			"咔噗"
		]
	},
	{
		"id":"副炮",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"副炮(频率)",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"units\\human\\MortarTeam\\MortarTeam.mdx",
		"modelScale":2.2,
		"sellItems":[
			"天雷炮",
			"喋血炮",
			"环雷装置",
			"刮痧装置",
			"破甲装置",
			"刺蛇炮",
			"致命炮",
			"激光炮"
		]
	},
	{
		"id":"海上奇珍",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"海上奇珍",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"单位\\海上奇珍\\海上奇珍.mdx",
		"modelScale":1,
		"sellItems":[
			"胶胶果实",
			"杀敌抽奖",
			"吞天石",
			"修炼",
			"船长信件",
			"核心部件"
		]
	},
	{
		"id":"深海奇珍",
		"class":"商店",
		"templateType":"NPC飞行单位",
		"name":"深海奇珍",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"单位\\海上奇珍\\海上奇珍.mdx",
		"modelScale":1,
		"flyHeight":200,
		"sellItems":[
			"深海下一关"
		]
	},
	{
		"id":"高级船长",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"船长(高级物品)",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"units\\creeps\\Medivh\\Medivh.mdx",
		"modelScale":2,
		"sellItems":[
			"白胡子制作书",
			"雷霆支配者制作书",
			"小丑制作书",
			"黑胡子制作书",
			"啦啦啦呀·索隆制作书",
			"Nico·罗宾制作书",
			"山只制作书",
			"布鲁克",
			"香科四",
			"MOM！",
			"暮年雷利"
		]
	},
	{
		"id":"基础船长",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"船长(打钱)",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"units\\creeps\\Medivh\\Medivh.mdx",
		"modelScale":2,
		"sellItems":[
			"赏金王",
			"强盗王",
			"山贼王",
			"海贼王",
			"吧唧"
		]
	},
	{
		"id":"核心部件预览",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"核心部件预览",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"units\\creeps\\Medivh\\Medivh.mdx",
		"modelScale":2,
		"sellItems":[
			"极限重炮",
			"绝杀",
			"巫术炮弹",
			"洲际导弹",
			"毒火炮",
			"不朽甲板",
			"光壁",
			"全面覆盖",
			"古老者甲板"
		]
	},
	{
		"id":"核心部件预览2",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"核心部件预览2",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"units\\creeps\\Medivh\\Medivh.mdx",
		"modelScale":2,
		"sellItems":[
			"曲率推进装置",
			"未来装置",
			"神避",
			"荒火引擎"
		]
	},
	{
		"id":"船身(生命)",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"船身(生命)",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"units\\human\\Arthas\\Arthas.mdx",
		"modelScale":2,
		"sellItems":[
			"船身Lv1",
			"船身Lv2",
			"船身Lv3",
			"船身Lv4",
			"船身Lv5",
			"船身Lv6",
			"船身Lv7",
			"船身Lv8",
			"船身Lv9"
		]
	},
	{
		"id":"甲板(护甲)",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"甲板(护甲)",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"units\\human\\Arthas\\Arthas.mdx",
		"modelScale":2,
		"sellItems":[
			"甲板Lv1",
			"甲板Lv2",
			"甲板Lv3",
			"甲板Lv4",
			"甲板Lv5",
			"甲板Lv6",
			"甲板Lv7",
			"甲板Lv8",
			"甲板Lv9"
		]
	},
	{
		"id":"马达(移速)",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"马达(移速)",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"units\\human\\Arthas\\Arthas.mdx",
		"modelScale":2,
		"sellItems":[
			"马达Lv1",
			"马达Lv2",
			"马达Lv3",
			"马达Lv4",
			"马达Lv5",
			"马达Lv6",
			"马达Lv7",
			"马达Lv8",
			"马达Lv9"
		]
	},
	{
		"id":"炮弹(攻击)",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"炮弹(攻击)",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"units\\human\\WarWagon\\WarWagon.mdx",
		"modelScale":2,
		"sellItems":[
			"炮弹Lv1",
			"炮弹Lv2",
			"炮弹Lv3",
			"炮弹Lv4",
			"炮弹Lv5",
			"炮弹Lv6",
			"炮弹Lv7",
			"炮弹Lv8",
			"炮弹Lv9"
		]
	},
	{
		"id":"船头(力量)",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"船头(力量)",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"units\\human\\Jaina\\Jaina.mdl",
		"modelScale":2,
		"sellItems":[
			"船头Lv1",
			"船头Lv2",
			"船头Lv3",
			"船头Lv4",
			"船头Lv5",
			"船头Lv6",
			"船头Lv7",
			"船头Lv8",
			"船头Lv9"
		]
	},
	{
		"id":"船帆(敏捷)",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"船帆(敏捷)",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"units\\human\\Jaina\\Jaina.mdl",
		"modelScale":2,
		"sellItems":[
			"船帆Lv1",
			"船帆Lv2",
			"船帆Lv3",
			"船帆Lv4",
			"船帆Lv5",
			"船帆Lv6",
			"船帆Lv7",
			"船帆Lv8",
			"船帆Lv9"
		]
	},
	{
		"id":"桅杆(智力)",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"桅杆(智力)",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"units\\human\\Jaina\\Jaina.mdl",
		"modelScale":2,
		"sellItems":[
			"桅杆Lv1",
			"桅杆Lv2",
			"桅杆Lv3",
			"桅杆Lv4",
			"桅杆Lv5",
			"桅杆Lv6",
			"桅杆Lv7",
			"桅杆Lv8",
			"桅杆Lv9"
		]
	},
	{
		"id":"修理工(恢复)",
		"class":"商店",
		"templateType":"NPC单位",
		"name":"修理工(恢复)",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"model":"units\\human\\Arthas\\Arthas.mdx",
		"modelScale":2,
		"sellItems":[
			"修理工Lv1",
			"修理工Lv2",
			"修理工Lv3",
			"修理工Lv4",
			"修理工Lv5",
			"修理工Lv6",
			"修理工Lv7",
			"修理工Lv8",
			"修理工Lv9"
		]
	}
]
export const d_演员物品售卖NPC = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
