//Generated By Solar Editor

/**
	id = id
	_parent = 父id
	Name = 名字
	HP = 生命值
	modelScale = 模型缩放
	Art = 图标 - 普通
	file = 模型文件
	Requires = 需求
	abilList = 技能
	fused = 占用人口
	acquire = 主动攻击范围
	rangeN1 = 攻击范围
*/
export type data_type = {
	id?: string
	_parent?: string
	Name?: string
	HP?: number
	modelScale?: number
	Art?: string
	file?: string
	Requires?: string
	abilList?: string
	fused?: number
	acquire?: number
	rangeN1?: number
    [key:string]: any
}

declare global {
    type t_秃鹫 = data_type
}

export const data: data_type[] = [
	{
		"id":"a458",
		"_parent":"hdhw",
		"Name":"秃鹫",
		"HP":10000,
		"modelScale":0.5,
		"Art":"ReplaceableTextures\\CommandButtons\\BTNVulture.blp",
		"file":"units\\critters\\Vulture\\Vulture.mdl",
		"Requires":" ",
		"abilList":" ",
		"fused":0,
		"acquire":1600,
		"rangeN1":600,
		"Ubertip":"秃鹫",
		"Tip":"秃鹫"
	}
]
export const d_秃鹫 = data;


//code
export default function(){
}
