//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
import 造成伤害时附带目标最大生命值比例的伤害 from "state/单位/造成伤害时附带目标最大生命值比例的伤害"
/**
	id = 自定义id
	class = 类别
	templateType = 基础模板
	name = 名字
	icon = 图标
	model = 模型
	abilities = 技能列表
	colorR = 红色通道
	colorG = 绿色通道
	colorB = 蓝色通道
	modelScale = 模型缩放
	bounty = 奖金
	moveSpeed = 移速
	maxLife = 生命值
	def = 护甲
	damage = 攻击力
	damageCd = 攻击间隔
	range = 攻击范围
	acquireRange = 主动攻击范围
	missileModel = 投射物模型
	moveType = 移动类型
	afterDeathBirthUnits = 死亡后诞生的单位
	flyHeight = 飞行高度
	goldCost = 金币消耗
	附带伤害 = 附带伤害
	maxMana = 最大魔法值
	describe = 提示说明
*/
export type data_type = {
	id?: string
	class?: string
	templateType?: string
	name?: string
	icon?: string
	model?: string
	abilities?: any
	colorR?: number
	colorG?: number
	colorB?: number
	modelScale?: number
	bounty?: number
	moveSpeed?: number
	maxLife?: number
	def?: number
	damage?: number
	damageCd?: number
	range?: number
	acquireRange?: number
	missileModel?: string
	moveType?: string
	afterDeathBirthUnits?: any
	flyHeight?: any
	goldCost?: any
	附带伤害?: number
	maxMana?: any
	describe?: any
    [key:string]: any
}

declare global {
    type t_进攻怪演员 = data_type
}

export const data: data_type[] = [
	{
		"id":"进攻怪-小木船",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"小木船",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\小木船.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":3,
		"moveSpeed":250,
		"maxLife":100,
		"def":0,
		"damage":20,
		"damageCd":1,
		"range":125,
		"acquireRange":200,
		"missileModel":"Abilities\\Weapons\\HarpyMissile\\HarpyMissile.mdx",
		"moveType":"float"
	},
	{
		"id":"进攻怪-驱逐舰",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"驱逐舰",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"units\\nightelf\\NightElfTransportShip\\NightElfTransportShip.mdl",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":5,
		"moveSpeed":350,
		"maxLife":400,
		"def":10,
		"damage":30,
		"damageCd":0.96,
		"range":200,
		"acquireRange":200,
		"missileModel":"Abilities\\Weapons\\Banditmissile\\Banditmissile.mdx",
		"moveType":"float",
		"附带伤害":0.005
	},
	{
		"id":"进攻怪-护卫舰",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"护卫舰",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"units\\creeps\\HumanDestroyerShip\\HumanDestroyerShip.mdl",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":8,
		"moveSpeed":350,
		"maxLife":1200,
		"def":20.0,
		"damage":50,
		"damageCd":0.9199999999999999,
		"range":300,
		"acquireRange":250,
		"missileModel":"Abilities\\Weapons\\FireballMissile\\FireballMissile.mdx",
		"moveType":"float",
		"afterDeathBirthUnits":{
			"进攻怪-小护卫舰":6
		},
		"附带伤害":0.01
	},
	{
		"id":"进攻怪-巡洋舰",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"巡洋舰",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\巡洋舰.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":12,
		"moveSpeed":440,
		"maxLife":2400,
		"def":30.0,
		"damage":100,
		"damageCd":0.8799999999999999,
		"range":400,
		"acquireRange":300,
		"missileModel":"Abilities\\Weapons\\RedDragonBreath\\RedDragonMissile.mdx",
		"moveType":"float",
		"附带伤害":0.015
	},
	{
		"id":"进攻怪-重舰",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"重舰",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\重舰.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":15,
		"moveSpeed":260,
		"maxLife":6000,
		"def":40.0,
		"damage":200,
		"damageCd":0.8399999999999999,
		"range":400,
		"acquireRange":400,
		"missileModel":"abilities\\weapons\\catapult\\catapultmissile.mdx",
		"moveType":"float",
		"附带伤害":0.02
	},
	{
		"id":"进攻怪-海龟",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"海龟",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\海龟.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":20,
		"moveSpeed":250,
		"maxLife":15000,
		"def":50.0,
		"damage":500,
		"damageCd":0.7999999999999998,
		"range":125,
		"acquireRange":500,
		"missileModel":"Abilities\\Weapons\\ChimaeraLightningMissile\\ChimaeraLightningMissile.mdx",
		"moveType":"float",
		"附带伤害":0.025
	},
	{
		"id":"进攻怪-石像鬼",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"石像鬼",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\石像鬼.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":25,
		"moveSpeed":250,
		"maxLife":20000,
		"def":60.0,
		"damage":1000,
		"damageCd":0.7599999999999998,
		"range":150,
		"acquireRange":1000,
		"missileModel":"Abilities\\Weapons\\Axe\\AxeMissile.mdx",
		"moveType":"fly",
		"afterDeathBirthUnits":{
			"进攻怪-石像鬼石像":1
		},
		"flyHeight":200,
		"附带伤害":0.030000000000000002
	},
	{
		"id":"进攻怪-九头蛇",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"九头蛇",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"Units\\Creeps\\Hydra\\Hydra.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":30,
		"moveSpeed":250,
		"maxLife":40000,
		"def":70.0,
		"damage":2000,
		"damageCd":0.7199999999999998,
		"range":300,
		"acquireRange":1100.0,
		"missileModel":"Abilities\\Weapons\\NecromancerMissile\\NecromancerMissile.mdx",
		"moveType":"float",
		"afterDeathBirthUnits":{
			"九头蛇【中】":2
		},
		"附带伤害":0.035
	},
	{
		"id":"进攻怪-触手",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"触手",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"Units\\Creeps\\ForgottenOne\\ForgottenOneTent.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":35,
		"moveSpeed":0,
		"maxLife":60000,
		"def":80.0,
		"damage":3000,
		"damageCd":0.6799999999999997,
		"range":400,
		"acquireRange":1200.0,
		"missileModel":"Abilities\\Weapons\\AncestralGuardianMissile\\AncestralGuardianMissile.mdx",
		"moveType":"float",
		"附带伤害":0.04
	},
	{
		"id":"进攻怪-飞蛇",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"飞蛇",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\飞蛇.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":40,
		"moveSpeed":522,
		"maxLife":100000,
		"def":90.0,
		"damage":5000,
		"damageCd":0.6399999999999997,
		"range":550,
		"acquireRange":1300.0,
		"missileModel":"Abilities\\Weapons\\GreenDragonMissile\\GreenDragonMissile.mdx",
		"moveType":"fly",
		"flyHeight":200,
		"附带伤害":0.045
	},
	{
		"id":"进攻怪-深海眷族",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"深海眷族",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\娜迦步兵.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":45,
		"moveSpeed":250,
		"maxLife":150000,
		"def":100.0,
		"damage":8000,
		"damageCd":0.5999999999999996,
		"range":175,
		"acquireRange":1400.0,
		"missileModel":"Abilities\\Weapons\\FragDriller\\FragDriller.mdx",
		"moveType":"float",
		"附带伤害":0.049999999999999996
	},
	{
		"id":"进攻怪-外星堡垒",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"外星堡垒",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"units\\undead\\UndeadAirBarge\\UndeadAirBarge.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":2,
		"bounty":50,
		"moveSpeed":250,
		"maxLife":200000,
		"def":110.0,
		"damage":10000,
		"damageCd":0.5599999999999996,
		"range":600,
		"acquireRange":1500.0,
		"missileModel":"Abilities\\Weapons\\BansheeMissile\\BansheeMissile.mdx",
		"moveType":"fly",
		"afterDeathBirthUnits":{
			"进攻怪-外星堡垒伞兵":8
		},
		"flyHeight":200,
		"附带伤害":0.05499999999999999
	},
	{
		"id":"进攻怪-刺蛇",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"刺蛇",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"Units\\Critters\\Hydralisk\\Hydralisk.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":60,
		"moveSpeed":420,
		"maxLife":300000,
		"def":120.0,
		"damage":20000,
		"damageCd":0.5199999999999996,
		"range":800,
		"acquireRange":1600.0,
		"missileModel":"Abilities\\Weapons\\KeeperGroveMissile\\KeeperGroveMissile.mdl",
		"moveType":"float",
		"附带伤害":0.05999999999999999
	},
	{
		"id":"进攻怪-黑影",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"黑影",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\阴影.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":70,
		"moveSpeed":300,
		"maxLife":500000,
		"def":130.0,
		"damage":50000,
		"damageCd":0.4799999999999996,
		"range":175,
		"acquireRange":1700.0,
		"missileModel":"Abilities\\Weapons\\GargoyleMissile\\GargoyleMissile.mdx",
		"moveType":"float",
		"附带伤害":0.06499999999999999
	},
	{
		"id":"进攻怪-扭曲体",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"扭曲体",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\克苏恩眼睛.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":0.3,
		"bounty":80,
		"moveSpeed":200,
		"maxLife":1000000,
		"def":140.0,
		"damage":100000,
		"damageCd":0.4399999999999996,
		"range":550,
		"acquireRange":1800.0,
		"missileModel":"Abilities\\Weapons\\MakuraMissile\\MakuraMissile.mdx",
		"moveType":"float",
		"附带伤害":0.06999999999999999
	},
	{
		"id":"进攻怪-小护卫舰",
		"class":"辅助进攻怪",
		"templateType":"远程单位",
		"name":"护卫舰",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"units\\creeps\\HumanDestroyerShip\\HumanDestroyerShip.mdl",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":0.5,
		"bounty":20,
		"moveSpeed":350,
		"maxLife":200,
		"def":0,
		"damage":100,
		"damageCd":0.8,
		"range":300,
		"acquireRange":500,
		"missileModel":"Abilities\\Weapons\\FireballMissile\\FireballMissile.mdx",
		"moveType":"float"
	},
	{
		"id":"九头蛇【中】",
		"class":"辅助进攻怪",
		"templateType":"远程单位",
		"name":"九头蛇【中】",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"Units\\Creeps\\Hydra\\Hydra.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":0.8,
		"bounty":20,
		"moveSpeed":275,
		"maxLife":10000,
		"def":0,
		"damage":800,
		"damageCd":0.8,
		"range":300,
		"acquireRange":500,
		"missileModel":"Abilities\\Weapons\\MurgulMagicMissile\\MurgulMagicMissile.mdx",
		"moveType":"float",
		"afterDeathBirthUnits":{
			"九头蛇【小】":2
		}
	},
	{
		"id":"九头蛇【小】",
		"class":"辅助进攻怪",
		"templateType":"远程单位",
		"name":"九头蛇【小】",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"Units\\Creeps\\Hydra\\Hydra.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":0.5,
		"bounty":10,
		"moveSpeed":276,
		"maxLife":5000,
		"def":0,
		"damage":1500,
		"damageCd":0.8,
		"range":300,
		"acquireRange":500,
		"missileModel":"Abilities\\Weapons\\AvengerMissile\\AvengerMissile.mdx",
		"moveType":"float"
	},
	{
		"id":"进攻怪-石像鬼石像",
		"class":"辅助进攻怪",
		"templateType":"远程单位",
		"name":"石像鬼石像",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\石像.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":20,
		"moveSpeed":0,
		"maxLife":30000,
		"def":0,
		"damage":0,
		"damageCd":0.8,
		"range":0,
		"acquireRange":0,
		"moveType":"float"
	},
	{
		"id":"进攻怪-外星堡垒伞兵",
		"class":"辅助进攻怪",
		"templateType":"远程单位",
		"name":"外星堡垒伞兵",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\火枪兵.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":1,
		"bounty":30,
		"moveSpeed":0,
		"maxLife":50000,
		"def":0,
		"damage":3000,
		"damageCd":1,
		"range":600,
		"acquireRange":500,
		"missileModel":"Abilities\\Weapons\\FragDriller\\FragDriller.mdx",
		"moveType":"float"
	}
]
export const d_进攻怪演员 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }

    for (let d of data) {
        if (d.id && d.附带伤害) {
            造成伤害时附带目标最大生命值比例的伤害.config[d.id] = d.附带伤害
        }
    }
}
