//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
import 造成伤害时附带目标最大生命值比例的伤害 from "state/单位/造成伤害时附带目标最大生命值比例的伤害"
/**
	id = 自定义id
	class = 类别
	templateType = 基础模板
	name = 名字
	icon = 图标
	model = 模型
	abilities = 技能列表
	colorR = 红色通道
	colorG = 绿色通道
	index = 序号
	colorB = 蓝色通道
	modelScale = 模型缩放
	bounty = 奖金
	moveSpeed = 移速
	maxLife = 生命值
	def = 护甲
	damage = 攻击力
	damageCd = 攻击间隔
	range = 攻击范围
	missileModel = 投射物模型
	moveType = 移动类型
	flyHeight = 飞行高度
	goldCost = 金币消耗
	maxMana = 最大魔法值
	附带伤害 = 附带伤害
	describe = 提示说明
*/
export type data_type = {
	id?: string
	class?: string
	templateType?: string
	name?: string
	icon?: string
	model?: string
	abilities?: any[]
	colorR?: number
	colorG?: number
	index?: number
	colorB?: number
	modelScale?: number
	bounty?: number
	moveSpeed?: number
	maxLife?: number
	def?: number
	damage?: number
	damageCd?: number
	range?: number
	missileModel?: string
	moveType?: string
	flyHeight?: any
	goldCost?: any
	maxMana?: any
	附带伤害?: number
	describe?: any
    [key:string]: any
}

declare global {
    type t_进攻怪boss = data_type
}

export const data: data_type[] = [
	{
		"id":"大和号",
		"class":"进攻怪boss",
		"templateType":"远程敏捷英雄",
		"name":"大和号",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNWindSerpent.blp",
		"model":"model\\进攻怪\\无敌战舰号.mdx",
		"abilities":[
			"大和号主炮"
		],
		"colorR":255,
		"colorG":255,
		"index":0,
		"colorB":255,
		"modelScale":2,
		"bounty":100,
		"moveSpeed":260,
		"maxLife":10000,
		"def":20,
		"damage":1000,
		"damageCd":1,
		"range":300,
		"missileModel":"Abilities\\Weapons\\KeeperGroveMissile\\KeeperGroveMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.1
	},
	{
		"id":"无敌战舰号",
		"class":"进攻怪boss",
		"templateType":"远程敏捷英雄",
		"name":"无敌战舰号",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\无敌战舰号.mdx",
		"abilities":[
			"无敌战舰号主炮"
		],
		"colorR":255,
		"colorG":255,
		"index":1,
		"colorB":255,
		"modelScale":3,
		"bounty":500,
		"moveSpeed":300,
		"maxLife":100000,
		"def":50,
		"damage":5000,
		"damageCd":1,
		"range":600,
		"missileModel":"Abilities\\Weapons\\DemonHunterMissile\\DemonHunterMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.1
	},
	{
		"id":"巨型海怪",
		"class":"进攻怪boss",
		"templateType":"远程敏捷英雄",
		"name":"巨型海怪",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNSeaTurtleRed.blp",
		"model":"model\\进攻怪\\海妖HD3.mdx",
		"abilities":[
			"巨型海怪主炮"
		],
		"colorR":255,
		"colorG":255,
		"index":2,
		"colorB":255,
		"modelScale":2,
		"bounty":1000,
		"moveSpeed":400,
		"maxLife":1000000,
		"def":100,
		"damage":20000,
		"damageCd":1,
		"range":500,
		"missileModel":"Abilities\\Weapons\\IllidanMissile\\IllidanMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.1
	},
	{
		"id":"克苏鲁之女-克希拉",
		"class":"进攻怪boss",
		"templateType":"远程敏捷英雄",
		"name":"克苏鲁之女-克希拉",
		"model":"model\\进攻怪\\女妖.mdx",
		"abilities":[
			"克希拉主炮"
		],
		"colorR":100,
		"colorG":255,
		"index":3,
		"colorB":100,
		"modelScale":5,
		"bounty":2000,
		"moveSpeed":450,
		"maxLife":2000000,
		"def":200,
		"damage":100000,
		"damageCd":1,
		"range":1200,
		"missileModel":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.15
	},
	{
		"id":"拉莱耶之主-伟大的克苏鲁",
		"class":"进攻怪boss",
		"templateType":"远程敏捷英雄",
		"name":"拉莱耶之主-伟大的克苏鲁",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNRedDragon.blp",
		"model":"model\\进攻怪\\克苏恩.mdx",
		"abilities":[
			"克苏鲁主炮"
		],
		"colorR":100,
		"colorG":200,
		"index":4,
		"colorB":100,
		"modelScale":0.5,
		"bounty":4000,
		"moveSpeed":522,
		"maxLife":5000000,
		"def":300,
		"damage":500000,
		"damageCd":1,
		"range":2000,
		"missileModel":"Abilities\\Weapons\\WardenMissile\\WardenMissile.mdx",
		"moveType":"amph",
		"附带伤害":0.2
	},
	{
		"id":"无敌战舰号护卫舰",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"无敌战舰号护卫舰",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\无敌战舰号.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":0.8,
		"bounty":500,
		"moveSpeed":260,
		"maxLife":5000,
		"def":101,
		"damage":500,
		"damageCd":1,
		"range":600,
		"missileModel":"Abilities\\Weapons\\BloodElfMissile\\BloodElfMissile.mdx",
		"moveType":"amph"
	},
	{
		"id":"克希拉护卫舰",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"克希拉护卫舰",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\无敌战舰号.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":255,
		"modelScale":0.9,
		"bounty":500,
		"moveSpeed":260,
		"maxLife":100000,
		"def":200,
		"damage":1000,
		"damageCd":1,
		"range":800,
		"missileModel":"Abilities\\Weapons\\NagaArrowMissile\\NagaArrowMissile.mdx",
		"moveType":"amph"
	},
	{
		"id":"超级触手",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"超级触手",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\大触手.mdx",
		"colorR":255,
		"colorG":0,
		"colorB":0,
		"modelScale":0.9,
		"bounty":500,
		"moveSpeed":0,
		"maxLife":1000000,
		"def":50,
		"damage":20000,
		"damageCd":0.5,
		"range":200,
		"missileModel":" ",
		"moveType":"amph"
	},
	{
		"id":"跟踪小触手单位",
		"class":"进攻怪",
		"templateType":"远程单位",
		"name":"跟踪小触手单位",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCorruptedEnt.blp",
		"model":"model\\进攻怪\\大触手.mdx",
		"colorR":255,
		"colorG":255,
		"colorB":0,
		"modelScale":0.4,
		"bounty":500,
		"moveSpeed":0,
		"maxLife":3,
		"def":3,
		"damage":3,
		"damageCd":0.5,
		"range":200,
		"missileModel":" ",
		"moveType":"amph"
	}
]
export const d_进攻怪boss = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }

    for (let d of data) {
        if (d.id && d.附带伤害) {
            造成伤害时附带目标最大生命值比例的伤害.config[d.id] = d.附带伤害
        }
    }
}
