//Generated By Solar Editor

import 受到伤害时限制最大伤害值为生命值比例 from "state/单位/受到伤害时限制最大伤害值为生命值比例"
/**
	id = id
	_parent = 父id
	Name = 名字
	nameCount = 称谓数量
	dmgplus1 = 攻击力
	HP = 生命值
	def = 基础护甲
	defUp = 防御升级奖励
	最大受到伤害 = 最大受到伤害
	cool1 = 攻击间隔
	Art = 图标 - 普通
	file = 模型文件
	abilList = 技能
	level = 等级
	weapsOn = 允许攻击模式
	spd = 基础速度
	hideHeroMinimap = 隐藏小地图英雄显示
	fused = 占用人口
	targs1 = 目标允许
	Missileart_1 = 投射物图像
	atkType1 = 攻击类型
	moveHeight = 高度
	movetp = 类型
	scale = 缩放
	modelScale = 模型缩放
	red = 颜色值(红)
	green = 颜色值(绿)
	blue = 颜色值(蓝)
	dmgUp1 = 伤害升级奖励
	sight = 视野范围(白天)
	weapTp1 = 武器类型
	dmgpt1 = 动画伤害点
	weapType1 = 攻击武器声音
	Missilearc_1 = 射弹弧度
	Missilespeed_1 = 射弹速率
	regenType = 生命回复类型
	backSw1 = 动画回复点
	defType = 护甲类型
	dice1 = 伤害骰子数量
	scaleBull = 缩放投射物
	points = 单位附加值
	bountydice = 黄金奖励 - 骰子数量
	rangeN1 = 攻击范围
	targType = 作为目标类型
	MissileHoming_1 = 射弹自导允许
	dropItems = 可设置死亡掉落物品
	bountysides = 黄金奖励 - 骰子面数
	regenHP = 生命回复
	type = 类别
	canFlee = 可以逃跑
	sides1 = 伤害骰子面数
	collision = 碰撞体积
	bountyplus = 黄金奖励 - 基础值
	RngBuff1 = 攻击范围缓冲
*/
export type data_type = {
	id?: string
	_parent?: string
	Name?: string
	nameCount?: number
	dmgplus1?: number
	HP?: number
	def?: number
	defUp?: number
	最大受到伤害?: number
	cool1?: number
	Art?: string
	file?: string
	abilList?: any
	level?: number
	weapsOn?: number
	spd?: number
	hideHeroMinimap?: number
	fused?: number
	targs1?: any
	Missileart_1?: any
	atkType1?: any
	moveHeight?: number
	movetp?: string
	scale?: number
	modelScale?: number
	red?: number
	green?: number
	blue?: number
	dmgUp1?: number
	sight?: number
	weapTp1?: any
	dmgpt1?: any
	weapType1?: any
	Missilearc_1?: any
	Missilespeed_1?: any
	regenType?: string
	backSw1?: any
	defType?: any
	dice1?: number
	scaleBull?: any
	points?: number
	bountydice?: number
	rangeN1?: number
	targType?: any
	MissileHoming_1?: any
	dropItems?: number
	bountysides?: number
	regenHP?: number
	type?: string
	canFlee?: number
	sides1?: number
	collision?: number
	bountyplus?: number
	RngBuff1?: number
    [key:string]: any
}

declare global {
    type t_野怪 = data_type
}

export const data: data_type[] = [
	{
		"id":"A44n",
		"_parent":"ugho",
		"Name":"秒杀守护者",
		"dmgplus1":999999999,
		"HP":5000000,
		"def":100,
		"defUp":3.2,
		"最大受到伤害":0.01,
		"cool1":0.1,
		"Art":"ReplaceableTextures\\CommandButtons\\BTNWindSerpent.blp",
		"file":"units\\naga\\WindSerpent\\WindSerpent.mdl",
		"level":36.0,
		"spd":522.0,
		"hideHeroMinimap":0,
		"fused":0.0,
		"moveHeight":300,
		"movetp":"fly",
		"scale":1.0,
		"modelScale":2,
		"red":255,
		"green":0,
		"blue":0,
		"dmgUp1":230.0,
		"sight":1000,
		"regenType":"always",
		"dice1":1.0,
		"points":600.0,
		"bountydice":0.0,
		"rangeN1":800,
		"dropItems":0.0,
		"bountysides":0.0,
		"regenHP":0.0,
		"type":"",
		"canFlee":0.0,
		"sides1":1.0,
		"collision":60.0,
		"bountyplus":0.0,
		"RngBuff1":2000.0,
		"nsight":1000,
		"Propernames":"秒杀守护者",
		"acquire":800
	},
	{
		"id":"A45g",
		"_parent":"ugho",
		"Name":"污染源",
		"nameCount":1,
		"dmgplus1":0,
		"HP":5000000,
		"def":200,
		"defUp":3.2,
		"cool1":1,
		"Art":"ReplaceableTextures\\CommandButtons\\BTNWindSerpent.blp",
		"file":"model\\进攻怪\\污染核心.mdx",
		"level":36.0,
		"weapsOn":0,
		"spd":0,
		"hideHeroMinimap":1,
		"fused":0.0,
		"moveHeight":300,
		"movetp":"fly",
		"scale":1.0,
		"modelScale":2,
		"red":0,
		"green":255,
		"blue":0,
		"dmgUp1":230.0,
		"sight":1000,
		"regenType":"always",
		"dice1":1.0,
		"points":600.0,
		"bountydice":0.0,
		"rangeN1":800,
		"dropItems":0.0,
		"bountysides":0.0,
		"regenHP":40000,
		"type":"",
		"canFlee":0.0,
		"sides1":1.0,
		"collision":60.0,
		"bountyplus":0.0,
		"RngBuff1":0,
		"nsight":1000,
		"Propernames":"污染源",
		"acquire":800
	}
]
export const d_野怪 = data;


//code
export default function(){

    for (let d of data) {
        if (d.id && d.最大受到伤害) {
            受到伤害时限制最大伤害值为生命值比例.config[d.id] = d.最大受到伤害
        }
    }
}
