//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	templateType = 基础模板
	name = 名字
	describe = 提示说明
	icon = 图标
	moveType = 移动类型
	flyHeight = 飞行高度
	moveSpeed = 移速
	maxLife = 生命值
	maxMana = 最大魔法值
	def = 护甲
	damage = 攻击力
	damageCd = 攻击间隔
	range = 攻击范围
	modelScale = 模型缩放
	missileModel = 投射物模型
	goldCost = 金币消耗
	model = 模型
	bounty = 赏金
	bountyItems = 击杀奖励物品
	sellItems = (内置有效)售卖演员物品类型id列表
*/
export type data_type = {
	id?: string
	class?: string
	templateType?: string
	name?: string
	describe?: string
	icon?: string
	moveType?: string
	flyHeight?: any
	moveSpeed?: number
	maxLife?: number
	maxMana?: any
	def?: number
	damage?: number
	damageCd?: number
	range?: number
	modelScale?: any
	missileModel?: any
	goldCost?: any
	model?: string
	bounty?: any
	bountyItems?: any
	sellItems?: any
    [key:string]: any
}

declare global {
    type t_陆上生物单位演员 = data_type
}

export const data: data_type[] = [
	{
		"id":"强盗领主",
		"class":"陆上生物",
		"templateType":"近战力量英雄",
		"name":"|cffff0000强盗领主",
		"describe":"无敌：被攻击时无敌30秒，冷却45秒。\n中立：目标是中立单位，靠近目标身边125范围目标变为敌对。且在目标头上显示：靠近激活挑战。\n特殊：第二个BOSS死亡后会消失。",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"moveType":"amph",
		"moveSpeed":350,
		"maxLife":150000,
		"def":50,
		"damage":15000,
		"damageCd":1,
		"range":175,
		"model":"units\\creeps\\BanditLord\\BanditLord.mdx",
		"bountyItems":{
			"船长之心-无敌学习书":1
		}
	},
	{
		"id":"农场",
		"class":"陆上生物",
		"templateType":"近战力量英雄",
		"name":"|cffff0001农场",
		"describe":"\n中立：目标是中立单位，靠近目标身边125范围目标变为敌对。且在目标头上显示：靠近激活挑战。\n被摧毁：被摧毁后，每秒刷新12个农民农民持续5秒后消失，每个农民击杀金币300，刷20秒。\n农民属性：2000生命值，护甲0。\n农民刷新完后，10分钟在原地会出现岛主。",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"moveType":"amph",
		"moveSpeed":0,
		"maxLife":50000,
		"def":50,
		"damage":0,
		"damageCd":1,
		"range":0,
		"model":"buildings\\human\\Farm\\Farm.mdx"
	},
	{
		"id":"巫师",
		"class":"陆上生物",
		"templateType":"近战力量英雄",
		"name":"|cffff0001巫师",
		"describe":"中立：目标是中立单位，靠近目标身边125范围目标变为敌对。且在目标头上显示：靠近激活挑战。\n变羊：将目标变样5秒，冷却15秒。",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"moveType":"amph",
		"moveSpeed":350,
		"maxLife":500000,
		"def":50,
		"damage":15000,
		"damageCd":1.25,
		"range":500,
		"model":"units\\creeps\\RevenantOfTheWaves\\RevenantOfTheWaves.mdx",
		"bountyItems":{
			"船长之心-变羊学习书":1
		}
	},
	{
		"id":"兽族酋长",
		"class":"陆上生物",
		"templateType":"近战力量英雄",
		"name":"|cffff0001兽族酋长（高危）",
		"describe":"中立：目标是中立单位，靠近目标身边125范围目标变为敌对。且在目标头上显示：靠近激活挑战。\n振奋：10秒内攻击+500%。冷却20秒。\n特殊：闪电链，造成攻击力x5的伤害，全地图弹射7次。（稍有不慎直接团灭）冷却30s。\n特殊：第三个BOSS死亡后会消失。",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"moveType":"amph",
		"moveSpeed":350,
		"maxLife":1000000,
		"def":100,
		"damage":20000,
		"damageCd":1.25,
		"range":550,
		"model":"units\\orc\\HeroTaurenChieftain\\HeroTaurenChieftain.mdx",
		"bountyItems":{
			"船长之心-酋长学习书":1
		}
	},
	{
		"id":"岛主",
		"class":"陆上生物",
		"templateType":"近战力量英雄",
		"name":"|cffff0001岛主",
		"describe":"两栖，会不断追着打爆农场的人打。\n技能：攻击30%概率击晕0.5秒。",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"moveType":"amph",
		"moveSpeed":300,
		"maxLife":50000,
		"def":100,
		"damage":100000,
		"damageCd":0.5,
		"range":175,
		"modelScale":4,
		"model":"units\\demon\\FelgaurdBlue\\FelgaurdBlue.mdx",
		"bountyItems":{
			"船长之心-岛主学习书":1
		}
	},
	{
		"id":"农民",
		"class":"陆上生物",
		"templateType":"近战单位",
		"name":"|cffff0001农民",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNFrost.blp",
		"moveType":"amph",
		"maxLife":2000,
		"def":0,
		"damage":10,
		"damageCd":1,
		"model":"units\\human\\Peasant\\Peasant.mdx",
		"bounty":100
	}
]
export const d_陆上生物单位演员 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
