//Generated By Solar Editor
//#sl-type editor-line

export const l_中心旋涡点: (Vector & { face: number })[] = [

    //索引[0] 位置相对左下角百分比 54%,55% 
    {x: 527, y: 304, z: -256, face: 91},

    //索引[1] 位置相对左下角百分比 54%,60% 
    {x: 516, y: 873, z: -256, face: -88}

]

