//Generated By Solar Editor
//#sl-type editor-line

export const l_起始点: (Vector & { face: number })[] = [

    //索引[0] 位置相对左下角百分比 54%,4% 
    {x: 471, y: -5148, z: -128, face: 87},

    //索引[1] 位置相对左下角百分比 54%,7% 
    {x: 488, y: -4793, z: -128, face: -92}

]

