//Generated By Solar Editor

import 图标面板 from "界面/图标面板/图标面板"
import 给与玩家奖励 from "state/module/给与玩家奖励系统"
import ActorTypeUtil from "@/ActorTypeUtil"
import 平台存档等地图相关奖励 from "state/存档/平台存档等地图相关奖励"
import BaseUtil from "@/BaseUtil"
/**
	id = id
	class = 类别
	name = 名字
	requireKey = 需求存档key
	requireValMin = 需求最低值
	rewardKey = 奖励名
	rewardVal = 奖励值
	数量叠加 = 数量叠加
	显示数量 = 显示数量
	兑换需要探索点 = 
	requiredTip = 需求信息
	describe = 提示说明
	icon = 图标
	uiShowType = 图标显示类型
*/
export type data_type = {
	id?: string
	class?: string
	name?: string
	requireKey?: string
	requireValMin?: number
	rewardKey?: string
	rewardVal?: any
	数量叠加?: boolean
	显示数量?: boolean
	兑换需要探索点?: number
	requiredTip?: any
	describe?: string
	icon?: string
	uiShowType?: string
    [key:string]: any
}

declare global {
    type t_兑换初始属性存档 = data_type
}

export const data: data_type[] = [
	{
		"id":"探索积分",
		"class":"探索点兑换",
		"name":"探索积分",
		"requireKey":"Itsjf",
		"requireValMin":1,
		"describe":"在深度海域获得的探索积分可以在这里进行分配到需要的加强方位，然后左键点击探索积分是总确认。右键点击是撤销。其他方位图标左键是+1 右键是-1。",
		"icon":"图标\\深海存档\\探索积分.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"力量加成",
		"class":"探索点兑换",
		"name":"力量加成",
		"requireKey":"dh_1",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"strength_p":0.01
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":50,
		"describe":"力量加成1%",
		"icon":"图标\\深海存档\\力量加成.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"敏捷加成",
		"class":"探索点兑换",
		"name":"敏捷加成",
		"requireKey":"dh_2",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"agility_p":0.01
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":50,
		"describe":"敏捷加成1%",
		"icon":"图标\\深海存档\\敏捷加成.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"智力加成",
		"class":"探索点兑换",
		"name":"智力加成",
		"requireKey":"dh_3",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"intelligence_p":0.01
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":50,
		"describe":"智力加成1%",
		"icon":"图标\\深海存档\\智力加成.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"攻击加成",
		"class":"探索点兑换",
		"name":"攻击加成",
		"requireKey":"dh_4",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"attack_p":0.01
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":50,
		"describe":"攻击加成1%",
		"icon":"图标\\深海存档\\攻击加成.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"伤害加成",
		"class":"探索点兑换",
		"name":"伤害加成",
		"requireKey":"dh_5",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"damage_increased":0.01
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":50,
		"describe":"伤害加成1%",
		"icon":"图标\\深海存档\\伤害加成.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"初始力量",
		"class":"探索点兑换",
		"name":"初始力量",
		"requireKey":"dh_6",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"strength":1
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":15,
		"describe":"初始力量1",
		"icon":"图标\\深海存档\\初始力量.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"初始敏捷",
		"class":"探索点兑换",
		"name":"初始敏捷",
		"requireKey":"dh_7",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"agility":1
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":15,
		"describe":"初始敏捷1",
		"icon":"图标\\深海存档\\初始敏捷.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"初始智力",
		"class":"探索点兑换",
		"name":"初始智力",
		"requireKey":"dh_8",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"intelligence":1
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":15,
		"describe":"初始智力1",
		"icon":"图标\\深海存档\\初始智力.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"初始攻击",
		"class":"探索点兑换",
		"name":"初始攻击",
		"requireKey":"dh_9",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"attack":1
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":15,
		"describe":"初始攻击2",
		"icon":"图标\\深海存档\\初始攻击.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"初始护甲",
		"class":"探索点兑换",
		"name":"初始护甲",
		"requireKey":"dh_10",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"def":0.5
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":15,
		"describe":"初始护甲0.5",
		"icon":"图标\\深海存档\\初始护甲.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"初始金币",
		"class":"探索点兑换",
		"name":"初始金币",
		"requireKey":"dh_11",
		"requireValMin":1,
		"rewardKey":"加金币",
		"rewardVal":50,
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":100,
		"describe":"初始金币50",
		"icon":"图标\\深海存档\\初始金币.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"金币加成",
		"class":"探索点兑换",
		"name":"金币加成",
		"requireKey":"dh_12",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"earn_gold_p":0.01
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":50,
		"describe":"金币加成1%",
		"icon":"图标\\深海存档\\金币加成.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"航速",
		"class":"探索点兑换",
		"name":"航速",
		"requireKey":"dh_13",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"move_speed":5
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":100,
		"describe":"航速5",
		"icon":"图标\\深海存档\\航速.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"BOSS伤害",
		"class":"探索点兑换",
		"name":"BOSS伤害",
		"requireKey":"dh_14",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"英雄伤害":0.01
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":100,
		"describe":"BOSS伤害1%",
		"icon":"图标\\深海存档\\BOSS伤害.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"初级探险者",
		"class":"探索点兑换",
		"name":"初级探险者",
		"requireKey":"dh_15",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"full_property":10
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":200,
		"describe":"初级探险者：初始全属性+10",
		"icon":"图标\\深海存档\\初级探险者.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"中级探险者",
		"class":"探索点兑换",
		"name":"中级探险者",
		"requireKey":"dh_16",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"full_property":10,
			"初始金币":50
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":500,
		"describe":"中级探险者：初始全属性+10，初始金币+50",
		"icon":"图标\\深海存档\\中级探险者.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"高级探险者",
		"class":"探索点兑换",
		"name":"高级探险者",
		"requireKey":"dh_17",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"full_property":10,
			"吞天石吞噬上限":1
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":1000,
		"describe":"神话探险家：初始全属性+10，吞天石吞噬上限+1",
		"icon":"图标\\深海存档\\高级探险者.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"顶级探险者",
		"class":"探索点兑换",
		"name":"顶级探险者",
		"requireKey":"dh_18",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"full_property":10,
			"吞噬船长上限":1
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":2000,
		"describe":"顶级探险者：初始全属性+10，吞噬船长上限+1",
		"icon":"图标\\深海存档\\顶级探险者.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"传奇探险家",
		"class":"探索点兑换",
		"name":"传奇探险家",
		"requireKey":"dh_19",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"full_property":10,
			"初始船长信件":1
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":3000,
		"describe":"传奇探险家：初始全属性+10，初始船长信件+1",
		"icon":"图标\\深海存档\\传奇探险家.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"神话探险家",
		"class":"探索点兑换",
		"name":"神话探险家",
		"requireKey":"dh_20",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"full_property":10,
			"add_strength_on_pers":1,
			"add_agility_on_pers":1,
			"add_intelligence_on_pers":1,
			"初始吞天石":1
		},
		"数量叠加":true,
		"显示数量":false,
		"兑换需要探索点":5000,
		"describe":"高级探险者：初始全属性+10，每秒全属性+1，初始吞天石+1",
		"icon":"图标\\深海存档\\神话探险家.blp",
		"uiShowType":"通用图标面板"
	}
]
export const d_兑换初始属性存档 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any) 
        }
    }
    BaseUtil.runLater(0.1,()=>{
        for (let datum of data) {
            if (datum.id) { 
                平台存档等地图相关奖励.distributeRewards(datum);
            }
        }
    })
}
