//Generated By Solar Editor

import 图标面板 from "界面/图标面板/图标面板"
import 给与玩家奖励 from "state/module/给与玩家奖励系统"
import ActorTypeUtil from "@/ActorTypeUtil"
import 平台存档等地图相关奖励 from "state/存档/平台存档等地图相关奖励"
import BaseUtil from "@/BaseUtil"
/**
	id = id
	class = 类别
	name = 名字
	requireKey = 需求存档key
	requireValMin = 需求最低值
	rewardKey = 奖励名
	rewardVal = 奖励值
	数量叠加 = 数量叠加
	requiredTip = 需求信息
	describe = 提示说明
	icon = 图标
	uiShowType = 图标显示类型
*/
export type data_type = {
	id?: string
	class?: string
	name?: string
	requireKey?: string
	requireValMin?: number
	rewardKey?: string
	rewardVal?: any
	数量叠加?: number
	requiredTip?: any
	describe?: string
	icon?: string
	uiShowType?: string
    [key:string]: any
}

declare global {
    type t_击杀BOSS装备存档 = data_type
}

export const data: data_type[] = [
	{
		"id":"yFT4O4428",
		"class":"击杀BOSS",
		"name":"大和号A",
		"requireKey":"kb1a",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"attack":20
		},
		"describe":"攻击+20",
		"icon":"图标\\存档\\大和号.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4429",
		"class":"击杀BOSS",
		"name":"大和号B",
		"requireKey":"kb1b",
		"requireValMin":1,
		"rewardKey":"给物品",
		"rewardVal":"重生十字章",
		"describe":"初始获得一个重生十字章",
		"icon":"图标\\存档\\大和号.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4430",
		"class":"击杀BOSS",
		"name":"大和号C",
		"requireKey":"kb1c",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"attack":5
		},
		"数量叠加":10,
		"describe":"爆炸：攻击+5，最多叠加10次。",
		"icon":"图标\\存档\\大和号.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4431",
		"class":"击杀BOSS",
		"name":"大和号D",
		"requireKey":"kb1d",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"attack":10
		},
		"数量叠加":10,
		"describe":"爆炸2：攻击+10，最多叠加10次。",
		"icon":"图标\\存档\\大和号.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4432",
		"class":"击杀BOSS",
		"name":"无敌战舰号A",
		"requireKey":"kb2a",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"def":1
		},
		"数量叠加":10,
		"describe":"护甲+1，最多叠加10次。",
		"icon":"图标\\存档\\无敌战舰号.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4433",
		"class":"击杀BOSS",
		"name":"无敌战舰号B",
		"requireKey":"kb2b",
		"requireValMin":1,
		"rewardKey":"给物品",
		"rewardVal":"无敌药水",
		"describe":"初始拥有一瓶无敌药水，持续7秒",
		"icon":"图标\\存档\\无敌战舰号.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4434",
		"class":"击杀BOSS",
		"name":"无敌战舰号C",
		"requireKey":"kb2c",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"def":2
		},
		"数量叠加":10,
		"describe":"无敌：护甲+2，最多叠加10次。",
		"icon":"图标\\存档\\无敌战舰号.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4435",
		"class":"击杀BOSS",
		"name":"无敌战舰号D",
		"requireKey":"kb2d",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"def":3
		},
		"数量叠加":10,
		"describe":"无敌2：护甲+3，最多叠加10次。",
		"icon":"图标\\存档\\无敌战舰号.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4436",
		"class":"击杀BOSS",
		"name":"巨型海怪A",
		"requireKey":"kb3a",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"reply_life_on_pers":10
		},
		"describe":"每秒回血+10",
		"icon":"图标\\存档\\巨型海怪.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4437",
		"class":"击杀BOSS",
		"name":"巨型海怪B",
		"requireKey":"kb3b",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"传送冷却":-2
		},
		"describe":"传送冷却-2s",
		"icon":"图标\\存档\\巨型海怪.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4438",
		"class":"击杀BOSS",
		"name":"巨型海怪C",
		"requireKey":"kb3c",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"life":10
		},
		"数量叠加":10,
		"describe":"怪兽：生命值+10，最多叠加10次。",
		"icon":"图标\\存档\\巨型海怪.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4439",
		"class":"击杀BOSS",
		"name":"巨型海怪D",
		"requireKey":"kb3d",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"life":20
		},
		"数量叠加":10,
		"describe":"怪兽2：生命值+20，最多叠加10次。",
		"icon":"图标\\存档\\巨型海怪.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4440",
		"class":"击杀BOSS",
		"name":"克苏鲁之女-克希拉A",
		"requireKey":"kb4a",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"每秒金币":1
		},
		"数量叠加":10,
		"describe":"每秒金币+1，最多叠加10次。",
		"icon":"图标\\存档\\克苏鲁之女.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4441",
		"class":"击杀BOSS",
		"name":"克苏鲁之女-克希拉B",
		"requireKey":"kb4b",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"传送冷却":-3
		},
		"describe":"传送冷却-3s",
		"icon":"图标\\存档\\克苏鲁之女.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4442",
		"class":"击杀BOSS",
		"name":"克苏鲁之女-克希拉C",
		"requireKey":"kb4c",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"move_speed":2
		},
		"数量叠加":10,
		"describe":"理智之敌：初始航速+2/节，最多叠加10次。",
		"icon":"图标\\存档\\克苏鲁之女.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4443",
		"class":"击杀BOSS",
		"name":"克苏鲁之女-克希拉D",
		"requireKey":"kb4d",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"move_speed":5
		},
		"数量叠加":10,
		"describe":"理智之敌2：初始航速+5/节，最多叠加10次。",
		"icon":"图标\\存档\\克苏鲁之女.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4444",
		"class":"击杀BOSS",
		"name":"拉莱耶之主-伟大的克苏鲁A",
		"requireKey":"kb5a",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"每秒金币":3
		},
		"describe":"每秒金币+3",
		"icon":"图标\\存档\\拉莱耶之主-伟大的克苏鲁.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4445",
		"class":"击杀BOSS",
		"name":"拉莱耶之主-伟大的克苏鲁B",
		"requireKey":"kb5b",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"免死金牌":1
		},
		"describe":"被击杀时强行拥有1点生命值不死，持续5秒，每局生效一次。",
		"icon":"图标\\存档\\拉莱耶之主-伟大的克苏鲁.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4446",
		"class":"击杀BOSS",
		"name":"拉莱耶之主-伟大的克苏鲁C",
		"requireKey":"kb5c",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"full_property":2
		},
		"数量叠加":10,
		"describe":"拉莱耶之主：初始属性+2，最多叠加10次。",
		"icon":"图标\\存档\\拉莱耶之主-伟大的克苏鲁.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"yFT4O4447",
		"class":"击杀BOSS",
		"name":"拉莱耶之主-伟大的克苏鲁D",
		"requireKey":"kb5d",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"full_property":5
		},
		"数量叠加":10,
		"describe":"伟大的克苏鲁\n初始属性+5，最多叠加10次。",
		"icon":"图标\\存档\\拉莱耶之主-伟大的克苏鲁.blp",
		"uiShowType":"通用图标面板"
	}
]
export const d_击杀BOSS装备存档 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any) 
        }
    }
    BaseUtil.runLater(0.1,()=>{
        for (let datum of data) {
            if (datum.id) { 
                平台存档等地图相关奖励.distributeRewards(datum);
            }
        }
    })
}
