//Generated By Solar Editor

import 图标面板 from "界面/图标面板/图标面板"
import 给与玩家奖励 from "state/module/给与玩家奖励系统"
import ActorTypeUtil from "@/ActorTypeUtil"
import 平台存档等地图相关奖励 from "state/存档/平台存档等地图相关奖励"
import BaseUtil from "@/BaseUtil"
/**
	id = id
	class = 类别
	name = 名字
	requireKey = 需求存档key
	requireValMin = 需求最低值
	rewardKey = 奖励名
	rewardVal = 奖励值
	数量叠加 = 数量叠加
	显示数量 = 显示数量
	兑换需要点数 = 
	requiredTip = 需求信息
	describe = 提示说明
	icon = 图标
	uiShowType = 图标显示类型
*/
export type data_type = {
	id?: string
	class?: string
	name?: string
	requireKey?: string
	requireValMin?: number
	rewardKey?: string
	rewardVal?: any
	数量叠加?: string
	显示数量?: boolean
	兑换需要点数?: number
	requiredTip?: any
	describe?: string
	icon?: string
	uiShowType?: string
    [key:string]: any
}

declare global {
    type t_历史中的战舰碎片 = data_type
}

export const data: data_type[] = [
	{
		"id":"历史中的战舰碎片",
		"class":"战舰碎片",
		"name":"历史中的战舰碎片",
		"requireKey":"Izjsp",
		"requireValMin":1,
		"describe":"在深度海域获得的战舰碎片可以在这里进行分配到需要的加强方位，然后左键点击探索积分是总确认。右键点击是撤销。其他方位图标左键是+1 右键是-1。",
		"icon":"图标\\深海存档\\历史中的战舰碎片.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"防御加强",
		"class":"战舰碎片",
		"name":"防御加强",
		"requireKey":"xdh_1",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"def":1,
			"life":50
		},
		"数量叠加":"无上限",
		"显示数量":false,
		"兑换需要点数":5,
		"describe":"护甲+1，生命值+50。",
		"icon":"图标\\深海存档\\防御加强.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"攻击加强",
		"class":"战舰碎片",
		"name":"攻击加强",
		"requireKey":"xdh_2",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"attack":10
		},
		"数量叠加":"无上限",
		"显示数量":false,
		"兑换需要点数":10,
		"describe":"攻击力+10",
		"icon":"图标\\深海存档\\攻击加强.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"射程加强",
		"class":"战舰碎片",
		"name":"射程加强",
		"requireKey":"xdh_3",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"autoMissileAttackRange":50
		},
		"数量叠加":"无上限",
		"显示数量":false,
		"兑换需要点数":50,
		"describe":"主炮射程+50",
		"icon":"图标\\深海存档\\射程加强.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"属性加强",
		"class":"战舰碎片",
		"name":"属性加强",
		"requireKey":"xdh_4",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"full_property":10,
			"add_gold_on_kill":1
		},
		"数量叠加":"无上限",
		"显示数量":false,
		"兑换需要点数":100,
		"describe":"基础全属性+10，杀敌金币+1",
		"icon":"图标\\深海存档\\属性加强.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"成长加强",
		"class":"战舰碎片",
		"name":"成长加强",
		"requireKey":"xdh_5",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"杀敌经验":1
		},
		"数量叠加":"无上限",
		"显示数量":false,
		"兑换需要点数":200,
		"describe":"杀敌经验值+1",
		"icon":"图标\\深海存档\\成长加强.blp",
		"uiShowType":"通用图标面板"
	}
]
export const d_历史中的战舰碎片 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any) 
        }
    }
    BaseUtil.runLater(0.1,()=>{
        for (let datum of data) {
            if (datum.id) { 
                平台存档等地图相关奖励.distributeRewards(datum);
            }
        }
    })
}
