//Generated By Solar Editor

import 图标面板 from "界面/图标面板/图标面板"
import 给与玩家奖励 from "state/module/给与玩家奖励系统"
import ActorTypeUtil from "@/ActorTypeUtil"
import 平台存档等地图相关奖励 from "state/存档/平台存档等地图相关奖励"
import BaseUtil from "@/BaseUtil"
/**
	id = id
	class = 类别
	name = 名字
	describe = 提示说明
	requireKey = 需求存档key
	requireVal = 需求最低值
	rewardKey = 奖励名
	rewardVal = 奖励值
	数量叠加 = 数量叠加
	激活码 = 激活码
	requiredTip = 需求信息
	icon = 图标
	hide = 是否隐藏
	uiShowType = 图标显示类型
*/
export type data_type = {
	id?: string
	class?: string
	name?: string
	describe?: string
	requireKey?: string
	requireVal?: any
	rewardKey?: string
	rewardVal?: any
	数量叠加?: any
	激活码?: string
	requiredTip?: string
	icon?: string
	hide?: boolean
	uiShowType?: string
    [key:string]: any
}

declare global {
    type t_平台论坛点赞相关奖励 = data_type
}

export const data: data_type[] = [
	{
		"id":"收藏过地图",
		"class":"礼包奖励",
		"name":"收藏过地图",
		"describe":"初始金币增加50",
		"requireKey":"收藏过地图",
		"rewardKey":"加金币",
		"rewardVal":50,
		"icon":"图标\\礼包存档\\收藏礼包.blp",
		"hide":false,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"累计获得赞数",
		"class":"礼包奖励",
		"name":"累计获得赞数",
		"describe":"初始金币增加100",
		"requireKey":"累计获得赞数",
		"requireVal":3,
		"rewardKey":"加金币",
		"rewardVal":100,
		"requiredTip":"累计获得赞数*3",
		"icon":"图标\\礼包存档\\累计获得点赞礼包.blp",
		"hide":false,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"总签到天数",
		"class":"礼包奖励",
		"name":"总签到天数",
		"describe":"初始护甲增加10%",
		"requireKey":"总签到天数",
		"requireVal":3,
		"rewardKey":"加属性",
		"rewardVal":{
			"def_p":0.1
		},
		"requiredTip":"总签到天数*3",
		"icon":"图标\\礼包存档\\签到礼包.blp",
		"hide":false,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"QQ群礼包",
		"class":"礼包奖励",
		"name":"QQ群礼包",
		"describe":"初始金币增加50|n点击加QQ群782345607获得此礼包激活码!",
		"requireKey":"_qt_qq",
		"rewardKey":"加金币",
		"rewardVal":50,
		"激活码":"hzkslqq",
		"icon":"图标\\礼包存档\\QQ群礼包.blp",
		"hide":false,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"测试福利",
		"class":"礼包奖励",
		"name":"测试福利",
		"describe":"初始金币增加30",
		"requireKey":"测试福利",
		"rewardKey":"加金币",
		"rewardVal":30,
		"icon":"图标\\礼包存档\\测试福利.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"预约福利",
		"class":"礼包奖励",
		"name":"预约福利",
		"describe":"初始金币增加20",
		"requireKey":"预约福利",
		"rewardKey":"加金币",
		"rewardVal":20,
		"icon":"图标\\礼包存档\\预约福利.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"_lb_yxlb",
		"class":"礼包奖励",
		"name":"迎新礼包",
		"describe":"初始金币增加100",
		"requireKey":"_lb_yxlb",
		"rewardKey":"加金币",
		"rewardVal":100,
		"激活码":"yxlb",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNShadowPact.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"_lb_lwjlb",
		"class":"礼包奖励",
		"name":"老玩家礼包",
		"describe":"吞天石吞噬上限+1",
		"requireKey":"_lb_lwjlb",
		"rewardKey":"加属性",
		"rewardVal":{
			"吞天石吞噬上限":1
		},
		"激活码":"lwjlb666",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNShadowPact.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"_lb_zslb",
		"class":"礼包奖励",
		"name":"忠实礼包",
		"describe":"初始木材增加1",
		"requireKey":"_lb_zslb",
		"rewardKey":"加木材",
		"rewardVal":1,
		"激活码":"solar_lb_zslb",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNShadowPact.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"_lb_smlb",
		"class":"礼包奖励",
		"name":"神秘礼包",
		"describe":"存档掉率+5%\n吞天石吞噬上限+1",
		"requireKey":"_lb_smlb",
		"rewardKey":"加属性",
		"rewardVal":{
			"存档掉率":0.05,
			"吞天石吞噬上限":1
		},
		"激活码":"hzksl_smlb666",
		"icon":"图标\\礼包存档\\神秘礼包.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"_lb_cslb",
		"class":"礼包奖励",
		"name":"测试礼包",
		"describe":"吞噬船长上限+1",
		"requireKey":"_lb_cslb",
		"rewardKey":"加属性",
		"rewardVal":{
			"吞噬船长上限":1
		},
		"激活码":"solar_lb_cslb888",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNPotionOfRestoration.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"_lb_smlxlb",
		"class":"礼包奖励",
		"name":"神秘领先礼包",
		"describe":"吞天石吞噬上限+1",
		"requireKey":"_lb_smlxlb",
		"rewardKey":"加属性",
		"rewardVal":{
			"吞天石吞噬上限":1
		},
		"激活码":"smlxlb7",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNPotionOfRestoration.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"_lb_bclb",
		"class":"礼包奖励",
		"name":"补偿礼包",
		"describe":"初始金币增加100",
		"requireKey":"_lb_bclb",
		"rewardKey":"加金币",
		"rewardVal":100,
		"激活码":"bclb520",
		"icon":"图标\\礼包存档\\补偿礼包.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"_lb_qtlb1",
		"class":"礼包奖励",
		"name":"除夕礼包",
		"describe":"吞天石吞噬上限+1",
		"requireKey":"_lb_qtlb1",
		"rewardKey":"加属性",
		"rewardVal":{
			"吞天石吞噬上限":1
		},
		"激活码":"cxlb166",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNShadowPact.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"_lb_qtlb2",
		"class":"礼包奖励",
		"name":"新年礼包",
		"describe":"吞噬船长上限+1",
		"requireKey":"_lb_qtlb2",
		"rewardKey":"加属性",
		"rewardVal":{
			"吞噬船长上限":1
		},
		"激活码":"xnlb688",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNShadowPact.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"_lb_qtlb3",
		"class":"礼包奖励",
		"name":"新春礼包",
		"describe":"吞噬船长上限+1",
		"requireKey":"_lb_qtlb3",
		"rewardKey":"加属性",
		"rewardVal":{
			"吞噬船长上限":1
		},
		"激活码":"xclb666",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNShadowPact.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"_lb_qtlb4",
		"class":"礼包奖励",
		"name":"礼包2023",
		"describe":"初始金币增加100",
		"requireKey":"_lb_qtlb4",
		"rewardKey":"加金币",
		"rewardVal":100,
		"激活码":"lb2023",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNShadowPact.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"_lb_qtlb5",
		"class":"礼包奖励",
		"name":"礼包2024",
		"describe":"存档掉率+5%",
		"requireKey":"_lb_qtlb5",
		"rewardKey":"加属性",
		"rewardVal":{
			"存档掉率":0.05
		},
		"激活码":"lb2024",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNShadowPact.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"_lb_qtlb6",
		"class":"礼包奖励",
		"name":"感谢礼包",
		"describe":"每秒金币增加{\"每秒金币\":1}",
		"requireKey":"_lb_qtlb6",
		"rewardKey":"加属性",
		"rewardVal":{
			"每秒金币":1
		},
		"激活码":"gxlb520",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNShadowPact.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"_lb_qtlb7",
		"class":"礼包奖励",
		"name":"再次感谢礼包",
		"describe":"每秒金币增加{\"每秒金币\":1}",
		"requireKey":"_lb_qtlb7",
		"rewardKey":"加属性",
		"rewardVal":{
			"每秒金币":1
		},
		"激活码":"zcgxlb123",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNShadowPact.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"_lb_qtlb8",
		"class":"礼包奖励",
		"name":"补偿礼包2",
		"describe":"初始金币增加100",
		"requireKey":"_lb_qtlb8",
		"rewardKey":"加金币",
		"rewardVal":100,
		"激活码":"bclb222",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNShadowPact.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	},
	{
		"id":"_lb_qtlb9",
		"class":"礼包奖励",
		"name":"补偿礼包3",
		"describe":"初始金币增加100",
		"requireKey":"_lb_qtlb9",
		"rewardKey":"加金币",
		"rewardVal":100,
		"激活码":"bclb3x3",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNShadowPact.blp",
		"hide":true,
		"uiShowType":"通用图标面板"
	}
]
export const d_平台论坛点赞相关奖励 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any) 
        }
    }
    BaseUtil.runLater(0.1,()=>{
        for (let datum of data) {
            if (datum.id) { 
                平台存档等地图相关奖励.distributeRewards(datum);
            }
        }
    })
}
