//Generated By Solar Editor

import 图标面板 from "界面/图标面板/图标面板"
import 给与玩家奖励 from "state/module/给与玩家奖励系统"
import ActorTypeUtil from "@/ActorTypeUtil"
import 平台存档等地图相关奖励 from "state/存档/平台存档等地图相关奖励"
import BaseUtil from "@/BaseUtil"
/**
	id = id
	class = 类别
	name = 名字
	requireKey = 需求存档key
	requireValMin = 需求最低值
	rewardKey = 奖励名
	rewardVal = 奖励值
	数量叠加 = 数量叠加
	显示数量 = 显示数量
	requiredTip = 需求信息
	describe = 提示说明
	icon = 图标
	uiShowType = 图标显示类型
*/
export type data_type = {
	id?: string
	class?: string
	name?: string
	requireKey?: string
	requireValMin?: number
	rewardKey?: string
	rewardVal?: any
	数量叠加?: string
	显示数量?: any
	requiredTip?: any
	describe?: string
	icon?: string
	uiShowType?: string
    [key:string]: any
}

declare global {
    type t_深度海域存档 = data_type
}

export const data: data_type[] = [
	{
		"id":"红色触手的灵魂碎片",
		"class":"深度海域",
		"name":"红色触手的灵魂碎片",
		"requireKey":"sc_hscs",
		"requireValMin":10,
		"describe":"集齐10个可以解锁红色触手，全属性+20，主炮造成伤害时有30%的概率使用触手击晕目标1秒并且造成10000的额外伤害(内置15秒cd)",
		"icon":"图标\\深海存档\\红色触手的灵魂碎片.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"忠诚之心",
		"class":"深度海域",
		"name":"忠诚之心",
		"requireKey":"sc_zczx",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"add_max_life_on_pers":1
		},
		"数量叠加":"地图等级",
		"describe":"每秒生命值+1，堆叠数量最大=地图等级",
		"icon":"图标\\深海存档\\忠诚之心.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"血色之心",
		"class":"深度海域",
		"name":"血色之心",
		"requireKey":"sc_xszx",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"每秒金币":1
		},
		"数量叠加":"地图等级",
		"describe":"每秒金币+1，堆叠数量最大=地图等级",
		"icon":"图标\\深海存档\\血色之心.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"污染之心",
		"class":"深度海域",
		"name":"污染之心",
		"requireKey":"sc_wrzx",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"attack":5
		},
		"数量叠加":"地图等级",
		"describe":"初始攻击+5，堆叠数量最大=地图等级",
		"icon":"图标\\深海存档\\污染之心.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"深海巨兽的灵魂碎片",
		"class":"深度海域",
		"name":"深海巨兽的灵魂碎片",
		"requireKey":"sc_shjs",
		"requireValMin":15,
		"describe":"（集齐15个可解锁光环，深海巨兽，每5秒，对周围400范围释放一次毁灭，造成攻击力x0.5的伤害，通用）\n每多搜集5个，毁灭的伤害+20%，最大10级",
		"icon":"图标\\深海存档\\深海巨兽的灵魂碎片.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"绝望之心",
		"class":"深度海域",
		"name":"绝望之心",
		"requireKey":"sc_jwzx",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"damage_increased":0.03
		},
		"数量叠加":"地图等级",
		"describe":"伤害加成+3%。堆叠数量=地图等级",
		"icon":"图标\\深海存档\\绝望之心.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"大副的灵魂碎片",
		"class":"深度海域",
		"name":"大副的灵魂碎片",
		"requireKey":"sc_dfsp",
		"requireValMin":20,
		"describe":"（集齐20个可解锁大副的灵魂，初始召唤一个继承自己攻击力100%的大副灵魂，攻速为每秒1次）\n每多搜集5个，大副的攻速+20%，最大10级。",
		"icon":"图标\\深海存档\\大副的灵魂碎片.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"古老者的灵魂碎片",
		"class":"深度海域",
		"name":"古老者的灵魂碎片",
		"requireKey":"sc_glz",
		"requireValMin":25,
		"describe":"（集齐25个可解锁古老者的灵魂，杀敌有30%概率全属性+1，每多搜集5个，概率+10%，只有5级）",
		"icon":"图标\\深海存档\\古老者的灵魂碎片.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"神话权柄",
		"class":"深度海域",
		"name":"神话权柄",
		"requireKey":"shqb",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"damage_increased":0.005
		},
		"describe":"每拥有一个神话权柄，造成的伤害增加0.5%\n叠加上限=地图等级*地图等级 \n（深度海域16层掉落此存档）\n",
		"icon":"图标\\深海存档\\神话权柄.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"神话尽头的呼唤",
		"class":"深度海域",
		"name":"神话尽头的呼唤",
		"requireKey":"sc_shjt",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"受到英雄伤害减免":0.2
		},
		"describe":"受到BOSS伤害-20%",
		"icon":"图标\\深海存档\\神话尽头的呼唤.blp",
		"uiShowType":"通用图标面板"
	},
	{
		"id":"拒绝神话生物",
		"class":"深度海域",
		"name":"拒绝神话生物",
		"requireKey":"sc_jjsh",
		"requireValMin":1,
		"rewardKey":"加属性",
		"rewardVal":{
			"对英雄增加伤害":0.2
		},
		"describe":"BOSS伤害+20%",
		"icon":"图标\\深海存档\\拒绝神话生物.blp",
		"uiShowType":"通用图标面板"
	}
]
export const d_深度海域存档 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any) 
        }
    }
    BaseUtil.runLater(0.1,()=>{
        for (let datum of data) {
            if (datum.id) { 
                平台存档等地图相关奖励.distributeRewards(datum);
            }
        }
    })
}
