//Generated By Solar Editor

import 图标面板 from "界面/图标面板/图标面板"
import 给与玩家奖励 from "state/module/给与玩家奖励系统"
import ActorTypeUtil from "@/ActorTypeUtil"
import 平台存档等地图相关奖励 from "state/存档/平台存档等地图相关奖励"
import BaseUtil from "@/BaseUtil"
/**
	id = id
	class = 类别
	name = 名字
	requireKey = 需求存档key
	requireValMin = 需求最低值
	rewardKey = 奖励名
	rewardVal = 奖励值
	requiredTip = 需求信息
	describe = 提示说明
	icon = 图标
	uiShowType = 图标显示类型
*/
export type data_type = {
	id?: string
	class?: string
	name?: string
	requireKey?: string
	requireValMin?: number
	rewardKey?: string
	rewardVal?: any
	requiredTip?: any
	describe?: string
	icon?: string
	uiShowType?: any
    [key:string]: any
}

declare global {
    type t_神话权柄累计解锁 = data_type
}

export const data: data_type[] = [
	{
		"id":"神话权柄累计解锁1",
		"class":"神话权柄累计解锁",
		"name":"神话权柄5",
		"requireKey":"shqb",
		"requireValMin":5,
		"rewardKey":"加属性",
		"rewardVal":{
			"attack":10
		},
		"describe":"初始攻击+10",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁2",
		"class":"神话权柄累计解锁",
		"name":"神话权柄10",
		"requireKey":"shqb",
		"requireValMin":10,
		"rewardKey":"加属性",
		"rewardVal":{
			"life":200
		},
		"describe":"初始血量+200",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁3",
		"class":"神话权柄累计解锁",
		"name":"神话权柄15",
		"requireKey":"shqb",
		"requireValMin":15,
		"rewardKey":"加属性",
		"rewardVal":{
			"autoMissileAttackRange":50
		},
		"describe":"所有主炮射程+50",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁4",
		"class":"神话权柄累计解锁",
		"name":"神话权柄20",
		"requireKey":"shqb",
		"requireValMin":20,
		"rewardKey":"加属性",
		"rewardVal":{
			"full_property":30
		},
		"describe":"初始三围+30",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁5",
		"class":"神话权柄累计解锁",
		"name":"神话权柄25",
		"requireKey":"shqb",
		"requireValMin":25,
		"rewardKey":"加属性",
		"rewardVal":{
			"add_gold_on_kill":1
		},
		"describe":"杀敌金币+1",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁6",
		"class":"神话权柄累计解锁",
		"name":"神话权柄30",
		"requireKey":"shqb",
		"requireValMin":30,
		"rewardKey":"加属性",
		"rewardVal":{
			"attack":50
		},
		"describe":"初始攻击+50",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁7",
		"class":"神话权柄累计解锁",
		"name":"神话权柄35",
		"requireKey":"shqb",
		"requireValMin":35,
		"rewardKey":"加属性",
		"rewardVal":{
			"life":500
		},
		"describe":"初始血量+500",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁8",
		"class":"神话权柄累计解锁",
		"name":"神话权柄40",
		"requireKey":"shqb",
		"requireValMin":40,
		"rewardKey":"加属性",
		"rewardVal":{
			"autoMissileAttackRange":100
		},
		"describe":"所有主炮射程+100",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁9",
		"class":"神话权柄累计解锁",
		"name":"神话权柄45",
		"requireKey":"shqb",
		"requireValMin":45,
		"rewardKey":"加属性",
		"rewardVal":{
			"full_property":50
		},
		"describe":"初始三围+50",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁10",
		"class":"神话权柄累计解锁",
		"name":"神话权柄50",
		"requireKey":"shqb",
		"requireValMin":50,
		"rewardKey":"加属性",
		"rewardVal":{
			"add_gold_on_kill":1
		},
		"describe":"杀敌金币+1",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁11",
		"class":"神话权柄累计解锁",
		"name":"神话权柄55",
		"requireKey":"shqb",
		"requireValMin":55,
		"rewardKey":"加属性",
		"rewardVal":{
			"attack":100
		},
		"describe":"初始攻击+100",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁12",
		"class":"神话权柄累计解锁",
		"name":"神话权柄60",
		"requireKey":"shqb",
		"requireValMin":60,
		"rewardKey":"加属性",
		"rewardVal":{
			"life":1000
		},
		"describe":"初始血量+1000",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁13",
		"class":"神话权柄累计解锁",
		"name":"神话权柄65",
		"requireKey":"shqb",
		"requireValMin":65,
		"rewardKey":"加属性",
		"rewardVal":{
			"full_property_p":0.1
		},
		"describe":"全属性加成+10%",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁14",
		"class":"神话权柄累计解锁",
		"name":"神话权柄70",
		"requireKey":"shqb",
		"requireValMin":70,
		"rewardKey":"加属性",
		"rewardVal":{
			"full_property":100
		},
		"describe":"初始三围+100",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁15",
		"class":"神话权柄累计解锁",
		"name":"神话权柄75",
		"requireKey":"shqb",
		"requireValMin":75,
		"rewardKey":"加属性",
		"rewardVal":{
			"add_strength_on_kill":1,
			"add_agility_on_kill":1,
			"add_intelligence_on_kill":1
		},
		"describe":"杀敌全属性+1",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁16",
		"class":"神话权柄累计解锁",
		"name":"神话权柄80",
		"requireKey":"shqb",
		"requireValMin":80,
		"rewardKey":"加属性",
		"rewardVal":{
			"damage_increased":0.2
		},
		"describe":"伤害加成+20%",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁17",
		"class":"神话权柄累计解锁",
		"name":"神话权柄85",
		"requireKey":"shqb",
		"requireValMin":85,
		"rewardKey":"加属性",
		"rewardVal":{
			"damage_reduction":0.05
		},
		"describe":"伤害减免+5%",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁18",
		"class":"神话权柄累计解锁",
		"name":"神话权柄90",
		"requireKey":"shqb",
		"requireValMin":90,
		"rewardKey":"加属性",
		"rewardVal":{
			"full_property_p":0.15
		},
		"describe":"全属性加成+15%",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁19",
		"class":"神话权柄累计解锁",
		"name":"神话权柄95",
		"requireKey":"shqb",
		"requireValMin":95,
		"rewardKey":"加属性",
		"rewardVal":{
			"add_strength_on_kill":1,
			"add_agility_on_kill":1,
			"add_intelligence_on_kill":1
		},
		"describe":"杀敌全属性+1",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	},
	{
		"id":"神话权柄累计解锁20",
		"class":"神话权柄累计解锁",
		"name":"神话权柄100",
		"requireKey":"shqb",
		"requireValMin":100,
		"rewardKey":"加属性",
		"rewardVal":{
			"杀敌经验":1,
			"damage_increased":0.3,
			"damage_reduction":0.1
		},
		"describe":"杀敌经验值+1，伤害加成+30%，伤害减免+10%",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBookOfTheDead.blp"
	}
]
export const d_神话权柄累计解锁 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any) 
        }
    }
    BaseUtil.runLater(0.1,()=>{
        for (let datum of data) {
            if (datum.id) { 
                平台存档等地图相关奖励.distributeRewards(datum);
            }
        }
    })
}
