//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	 passive = 是否被动(不可点击的装备)
	name = 名字
	describe = 提示说明
	icon = 图标
	maxCd = 冷却时间
	goldCost = 金币消耗
	lumberCost = 木材消耗
	pawnable = 是否可抵押
	reply_life_p = 点击比例回血
	attributereply_life_on_pers = 太阳属性附加
*/
export type data_type = {
	id?: string
	class?: string
	passive?: boolean
	name?: string
	describe?: string
	icon?: string
	maxCd?: number
	goldCost?: number
	lumberCost?: any
	pawnable?: number
	reply_life_p?: number
	attribute?: {
		reply_life_on_pers?: number
	}
    [key:string]: any
}

declare global {
    type t_修理工 = data_type
}

export const data: data_type[] = [
	{
		"id":"修理工Lv1",
		"class":"基础属性装备",
		"passive":false,
		"name":"修理工Lv1",
		"describe":"每秒恢复5点生命值\n点击回血20%最大值+50倍基础每秒恢复值",
		"icon":"物品图标\\修理工\\修理工1.blp",
		"maxCd":15,
		"goldCost":100,
		"pawnable":1,
		"reply_life_p":0.2,
		"attribute":{
			"reply_life_on_pers":5
		}
	},
	{
		"id":"修理工Lv2",
		"class":"基础属性装备",
		"passive":false,
		"name":"修理工Lv2",
		"describe":"每秒恢复10点生命值\n点击回血25%最大值+50倍基础每秒恢复值",
		"icon":"物品图标\\修理工\\修理工2.blp",
		"maxCd":15,
		"goldCost":200.0,
		"pawnable":1,
		"reply_life_p":0.25,
		"attribute":{
			"reply_life_on_pers":10
		}
	},
	{
		"id":"修理工Lv3",
		"class":"基础属性装备",
		"passive":false,
		"name":"修理工Lv3",
		"describe":"每秒恢复20点生命值\n点击回血30%最大值+50倍基础每秒恢复值",
		"icon":"物品图标\\修理工\\修理工3.blp",
		"maxCd":15,
		"goldCost":400.0,
		"pawnable":1,
		"reply_life_p":0.3,
		"attribute":{
			"reply_life_on_pers":20
		}
	},
	{
		"id":"修理工Lv4",
		"class":"基础属性装备",
		"passive":false,
		"name":"修理工Lv4",
		"describe":"每秒恢复40点生命值\n点击回血35%最大值+50倍基础每秒恢复值",
		"icon":"物品图标\\修理工\\修理工4.blp",
		"maxCd":15,
		"goldCost":800.0,
		"pawnable":1,
		"reply_life_p":0.35,
		"attribute":{
			"reply_life_on_pers":40
		}
	},
	{
		"id":"修理工Lv5",
		"class":"基础属性装备",
		"passive":false,
		"name":"修理工Lv5",
		"describe":"每秒恢复80点生命值\n点击回血40%最大值+50倍基础每秒恢复值",
		"icon":"物品图标\\修理工\\修理工5.blp",
		"maxCd":15,
		"goldCost":1600.0,
		"pawnable":1,
		"reply_life_p":0.39999999999999997,
		"attribute":{
			"reply_life_on_pers":80
		}
	},
	{
		"id":"修理工Lv6",
		"class":"基础属性装备",
		"passive":false,
		"name":"修理工Lv6",
		"describe":"每秒恢复160点生命值\n点击回血45%最大值+50倍基础每秒恢复值",
		"icon":"物品图标\\修理工\\修理工6.blp",
		"maxCd":15,
		"goldCost":3200.0,
		"pawnable":1,
		"reply_life_p":0.44999999999999996,
		"attribute":{
			"reply_life_on_pers":160
		}
	},
	{
		"id":"修理工Lv7",
		"class":"基础属性装备",
		"passive":false,
		"name":"修理工Lv7",
		"describe":"每秒恢复320点生命值\n点击回血50%最大值+50倍基础每秒恢复值",
		"icon":"物品图标\\修理工\\修理工7.blp",
		"maxCd":15,
		"goldCost":6400.0,
		"pawnable":1,
		"reply_life_p":0.49999999999999994,
		"attribute":{
			"reply_life_on_pers":320
		}
	},
	{
		"id":"修理工Lv8",
		"class":"基础属性装备",
		"passive":false,
		"name":"修理工Lv8",
		"describe":"每秒恢复640点生命值\n点击回血55%最大值+50倍基础每秒恢复值",
		"icon":"物品图标\\修理工\\修理工8.blp",
		"maxCd":15,
		"goldCost":12800.0,
		"pawnable":1,
		"reply_life_p":0.5499999999999999,
		"attribute":{
			"reply_life_on_pers":640
		}
	},
	{
		"id":"修理工Lv9",
		"class":"基础属性装备",
		"passive":false,
		"name":"修理工Lv9",
		"describe":"每秒恢复1280点生命值\n点击回血60%最大值+50倍基础每秒恢复值",
		"icon":"物品图标\\修理工\\修理工9.blp",
		"maxCd":15,
		"goldCost":25600.0,
		"pawnable":1,
		"reply_life_p":0.6,
		"attribute":{
			"reply_life_on_pers":1280
		}
	},
	{
		"id":"修理工Lv10",
		"class":"基础属性装备",
		"passive":false,
		"name":"修理工Lv10",
		"describe":"每秒恢复2560点生命值\n点击回血80%最大值+50倍基础每秒恢复值",
		"icon":"物品图标\\修理工\\修理工10.blp",
		"maxCd":15,
		"goldCost":51200.0,
		"pawnable":1,
		"reply_life_p":0.8,
		"attribute":{
			"reply_life_on_pers":2560
		}
	}
]
export const d_修理工 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
