//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
import SolarNewItemsFormulaState from "state/common/SolarNewItemsFormulaState"
/**
	id = 自定义id
	describe = 提示说明
	class = 类别
	 passive = 是否被动(不可点击的装备)
	name = 名字
	icon = 图标
	最大目标数量 = 最大目标数量
	sc_射程 = 射程
	ss_射速 = 射速
	shgs_伤害公式 = 伤害
	goldCost = 金币消耗
	model = 模型
	lumberCost = 木材消耗
	pawnable = 是否可抵押
	attribute = 属性附加
	itemMaterialsFormula = 合成材料id
*/
export type data_type = {
	id?: string
	describe?: string
	class?: string
	passive?: boolean
	name?: string
	icon?: string
	最大目标数量?: number
	sc_射程?: number
	ss_射速?: number
	shgs_伤害公式?: any
	goldCost?: number
	model?: any
	lumberCost?: any
	pawnable?: number
	attribute?: any
	itemMaterialsFormula?: any
    [key:string]: any
}

declare global {
    type t_副炮演员物品 = data_type
}

export const data: data_type[] = [
	{
		"id":"天雷炮",
		"describe":"射程：600\n伤害：攻击力x0.5\n射速：0.3\n特殊：造成伤害时有15%概率触发连锁闪电，造成全属性x1的弹射雷霆，可弹跳5次。|n|cffcccccc天雷炮+lv10桅杆x2+lv10炮弹x2+制作书=【雷霆支配者】|r",
		"class":"副炮",
		"passive":true,
		"name":"天雷炮",
		"icon":"物品图标\\副炮\\01天雷炮.blp",
		"sc_射程":600,
		"ss_射速":0.3,
		"shgs_伤害公式":{
			"attack":0.5
		},
		"goldCost":1400,
		"pawnable":1
	},
	{
		"id":"喋血炮",
		"describe":"伤害吸血+2%|n|cffccccccLV10船头+LV10桅杆+LV10船帆+喋血炮x2+合成书=黑胡子|r",
		"class":"副炮",
		"passive":true,
		"name":"喋血炮",
		"icon":"物品图标\\副炮\\02喋血炮.blp",
		"goldCost":2000,
		"attribute":{
			"blood_sucking":0.02
		},
		"pawnable":1
	},
	{
		"id":"环雷装置",
		"describe":"每秒对身边的敌人造成持续伤害，伤害为1000+10%生命值。",
		"class":"副炮",
		"passive":true,
		"name":"环雷装置",
		"icon":"物品图标\\副炮\\03环雷装置.blp",
		"goldCost":10000,
		"pawnable":1
	},
	{
		"id":"刮痧装置",
		"describe":"射程：600\n伤害：攻击力x0.1\n射速：0.1\n特殊：该副炮造成伤害时削弱目标1点护甲，持续5秒，刷新叠加，最多100层。\n|n|cffcccccc 刮痧装置+lv10船帆x2+制作书=【小丑】|r",
		"class":"副炮",
		"passive":true,
		"name":"刮痧装置",
		"icon":"物品图标\\副炮\\04刮痧装置.blp",
		"sc_射程":600,
		"ss_射速":0.1,
		"shgs_伤害公式":{
			"attack":0.1
		},
		"goldCost":50000,
		"pawnable":1
	},
	{
		"id":"破甲装置",
		"describe":"射程：600\n伤害：攻击力x0.1\n射速：0.1\n特殊：范围600的敌人护甲-30%\n|n|cffcccccc 破甲装置+致命炮+lv10炮弹=【两仪式】|r",
		"class":"副炮",
		"passive":true,
		"name":"破甲装置",
		"icon":"物品图标\\副炮\\05破甲装置.blp",
		"sc_射程":600,
		"ss_射速":0.1,
		"shgs_伤害公式":{
			"attack":0.1
		},
		"goldCost":50000,
		"pawnable":1
	},
	{
		"id":"刺蛇炮",
		"describe":"射程：600\n伤害：攻击力x0.1\n射速：1\n特殊：该副炮造成伤害时会让目标中毒，每秒受到10000点真实伤害，持续5秒。",
		"class":"副炮",
		"passive":true,
		"name":"刺蛇炮",
		"icon":"物品图标\\副炮\\06刺蛇炮.blp",
		"sc_射程":600,
		"ss_射速":1,
		"shgs_伤害公式":{
			"attack":0.1
		},
		"goldCost":50000,
		"pawnable":1
	},
	{
		"id":"致命炮",
		"describe":"射程：800\n伤害：1000+攻击力x2\n射速：0.35\n特殊：该主炮造成伤害时有20%概率x5。\n|n|cffcccccc 破甲装置+致命炮+lv10炮弹=【两仪式】|r",
		"class":"副炮",
		"passive":true,
		"name":"致命炮",
		"icon":"物品图标\\副炮\\07致命炮.blp",
		"sc_射程":800,
		"ss_射速":0.35,
		"shgs_伤害公式":{
			"base":1000.0,
			"attack":2.0
		},
		"goldCost":30000,
		"pawnable":1
	},
	{
		"id":"激光炮",
		"describe":"射程：800\n伤害：500+攻击力x0.2\n射速：0.1\n特殊：无\n激光炮 + 激光炮 = 激光炮lv2",
		"class":"副炮",
		"passive":true,
		"name":"激光炮",
		"icon":"物品图标\\副炮\\08激光炮.blp",
		"sc_射程":800,
		"ss_射速":0.1,
		"shgs_伤害公式":{
			"base":500.0,
			"attack":0.2
		},
		"goldCost":10000,
		"pawnable":1
	},
	{
		"id":"激光炮lv2",
		"describe":"射程：800\n伤害：1000+攻击力x0.3\n射速：0.1\n特殊：无\n激光炮lv2 + 激光炮lv2 = 激光炮lv3",
		"class":"副炮",
		"passive":true,
		"name":"激光炮lv2",
		"icon":"物品图标\\副炮\\09激光炮lv2.blp",
		"sc_射程":800,
		"ss_射速":0.1,
		"shgs_伤害公式":{
			"base":1000.0,
			"attack":0.3
		},
		"goldCost":20000,
		"itemMaterialsFormula":{
			"激光炮":2
		},
		"pawnable":1
	},
	{
		"id":"激光炮lv3",
		"describe":"射程：800\n伤害：2000+攻击力x0.4\n射速：0.1\n特殊：无\n激光炮lv3 + 激光炮lv3 = 激光炮lv4",
		"class":"副炮",
		"passive":true,
		"name":"激光炮lv3",
		"icon":"物品图标\\副炮\\10激光炮lv3.blp",
		"sc_射程":800,
		"ss_射速":0.1,
		"shgs_伤害公式":{
			"base":2000.0,
			"attack":0.4
		},
		"goldCost":40000,
		"itemMaterialsFormula":{
			"激光炮lv2":2
		},
		"pawnable":1
	},
	{
		"id":"激光炮lv4",
		"describe":"射程：800\n伤害：2000+攻击力x0.5\n射速：0.1\n特殊：激光炮可同时攻击2个单位",
		"class":"副炮",
		"passive":true,
		"name":"激光炮lv4",
		"icon":"物品图标\\副炮\\11激光炮lv4.blp",
		"最大目标数量":2,
		"sc_射程":800,
		"ss_射速":0.1,
		"shgs_伤害公式":{
			"base":2000.0,
			"attack":0.5
		},
		"goldCost":80000,
		"itemMaterialsFormula":{
			"激光炮lv3":2
		},
		"pawnable":1
	},
	{
		"id":"激光炮lv5",
		"describe":"射程：800\n伤害：2000+攻击力x0.6\n射速：0.1\n特殊：激光炮可同时攻击3个单位\n激光炮LV5攻击次数达到3000次升级到【炮姐】",
		"class":"副炮",
		"passive":true,
		"name":"激光炮lv5",
		"icon":"物品图标\\副炮\\12激光炮lv5.blp",
		"最大目标数量":3,
		"sc_射程":800,
		"ss_射速":0.1,
		"shgs_伤害公式":{
			"base":2000.0,
			"attack":0.6
		},
		"goldCost":160000,
		"itemMaterialsFormula":{
			"激光炮lv4":2
		},
		"pawnable":1
	}
]
export const d_副炮演员物品 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }

    for (let datum of data) {
        if (datum.itemMaterialsFormula) {
            SolarNewItemsFormulaState.config[datum.id] = {material: datum.itemMaterialsFormula}
        }
    }
}
