//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
import SolarNewItemsFormulaState from "state/common/SolarNewItemsFormulaState"
/**
	id = 自定义id
	describe = 提示说明
	class = 类别
	kind = 种类
	index = 序号
	 passive = 是否被动(不可点击的装备)
	name = 名字
	icon = 图标
	unique = 唯一
	最大目标数量 = 最大目标数量
	sc_射程 = 射程
	ss_射速 = 射速
	shgs_伤害公式 = 伤害
	missileModel = 弹道模型
	goldCost = 金币消耗
	model = 模型
	lumberCost = 木材消耗
	pawnable = 是否可抵押
	attribute = 属性附加
	itemMaterialsFormula = 合成材料id
*/
export type data_type = {
	id?: string
	describe?: string
	class?: string
	kind?: string
	index?: number
	passive?: boolean
	name?: string
	icon?: string
	unique?: boolean
	最大目标数量?: any
	sc_射程?: number
	ss_射速?: number
	shgs_伤害公式?: any
	missileModel?: string
	goldCost?: number
	model?: any
	lumberCost?: any
	pawnable?: number
	attribute?: any
	itemMaterialsFormula?: any
    [key:string]: any
}

declare global {
    type t_基础船长演员物品 = data_type
}

export const data: data_type[] = [
	{
		"id":"赏金王",
		"describe":"射程：600\n伤害：攻击力x0.1\n射速：0.5\n该船长每次造成伤害，可获得3金币。\n|n|cffcccccc 赏金王+强盗王+山贼王+海贼王=【娜米】（用宝宝才能合成）|r",
		"class":"基础船长",
		"kind":"打钱船长",
		"index":0,
		"passive":true,
		"name":"赏金王",
		"icon":"物品图标\\船长\\高级\\船长赏金王.blp",
		"unique":true,
		"sc_射程":600,
		"ss_射速":0.5,
		"shgs_伤害公式":{
			"attack":0.1
		},
		"missileModel":"Objects\\InventoryItems\\PotofGold\\PotofGold.mdl",
		"goldCost":500,
		"pawnable":1
	},
	{
		"id":"强盗王",
		"describe":"射程：800\n伤害：攻击力x0.1\n射速：0.5\n该船长每次造成伤害，可获得5金币。|n|cffcccccc 赏金王+强盗王+山贼王+海贼王=【娜米】（用宝宝才能合成）|r",
		"class":"基础船长",
		"kind":"打钱船长",
		"index":1,
		"passive":true,
		"name":"强盗王",
		"icon":"物品图标\\船长\\高级\\船长强盗王.blp",
		"unique":true,
		"sc_射程":800,
		"ss_射速":0.5,
		"shgs_伤害公式":{
			"attack":0.1
		},
		"missileModel":"Objects\\InventoryItems\\PotofGold\\PotofGold.mdl",
		"goldCost":5000,
		"attribute":{
			"blood_sucking":0.02
		},
		"pawnable":1
	},
	{
		"id":"山贼王",
		"describe":"射程：900\n伤害：攻击力x0.1\n射速：0.5\n该船长每次造成伤害，可获得8+目标10%原本赏金的金币。|n|cffcccccc 赏金王+强盗王+山贼王+海贼王=【娜米】（用宝宝才能合成）|r",
		"class":"基础船长",
		"kind":"打钱船长",
		"index":2,
		"passive":true,
		"name":"山贼王",
		"icon":"物品图标\\船长\\高级\\船长山贼王.blp",
		"unique":true,
		"sc_射程":900,
		"ss_射速":0.5,
		"shgs_伤害公式":{
			"attack":0.1
		},
		"missileModel":"Objects\\InventoryItems\\PotofGold\\PotofGold.mdl",
		"goldCost":15000,
		"pawnable":1
	},
	{
		"id":"海贼王",
		"describe":"射程：900\n伤害：攻击力x0.1\n射速：0.5\n该船长每次造成伤害，可获得10+目标20%原本赏金的金币。|n|cffcccccc 赏金王+强盗王+山贼王+海贼王=【娜米】（用宝宝才能合成）|r",
		"class":"基础船长",
		"kind":"打钱船长",
		"index":3,
		"passive":true,
		"name":"海贼王",
		"icon":"物品图标\\船长\\高级\\船长海贼王.blp",
		"unique":true,
		"sc_射程":900,
		"ss_射速":0.5,
		"shgs_伤害公式":{
			"attack":0.1
		},
		"missileModel":"Objects\\InventoryItems\\PotofGold\\PotofGold.mdl",
		"goldCost":30000,
		"pawnable":1
	}
]
export const d_基础船长演员物品 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }

    for (let datum of data) {
        if (datum.itemMaterialsFormula) {
            SolarNewItemsFormulaState.config[datum.id] = {material: datum.itemMaterialsFormula}
        }
    }
}
