//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	 passive = 是否被动(不可点击的装备)
	name = 名字
	describe = 提示说明
	icon = 图标
	最大目标数量 = 最大目标数量
	sc_射程 = 射程
	ss_射速 = 射速
	shgs_伤害公式 = 伤害公式
	missileModel = 弹道模型
	unique = 唯一
	goldCost = 金币消耗
	lumberCost = 木材消耗
	pawnable = 是否可抵押
	attribute = 属性附加
*/
export type data_type = {
	id?: string
	class?: string
	passive?: boolean
	name?: string
	describe?: string
	icon?: string
	最大目标数量?: number
	sc_射程?: number
	ss_射速?: number
	shgs_伤害公式?: any
	missileModel?: any
	unique?: boolean
	goldCost?: number
	lumberCost?: any
	pawnable?: number
	attribute?: any
    [key:string]: any
}

declare global {
    type t_核心部件 = data_type
}

export const data: data_type[] = [
	{
		"id":"极限重炮",
		"class":"核心部件",
		"passive":false,
		"name":"极限重炮",
		"describe":"伤害加成+30%（+5%）\n力量加成+20%\n主炮：\n射程：800\n伤害：攻击力x5\n射速：0.8\n强化+10：\n力量加成+30%\n强化+15：\n重炮伤害翻倍。",
		"icon":"图标\\核心部件\\01极限重炮.blp",
		"sc_射程":800,
		"ss_射速":0.8,
		"shgs_伤害公式":{
			"attack":5
		},
		"unique":true,
		"goldCost":2000,
		"pawnable":1,
		"attribute":{
			"strength_p":0.2,
			"damage_increased":0.3
		}
	},
	{
		"id":"绝杀",
		"class":"核心部件",
		"passive":false,
		"name":"绝杀",
		"describe":"攻击加成+30%（+5%）\n敏捷加成+20%\n主炮：\n射程：800\n伤害：攻击力x1\n射速：0.1\n强化+10：\n当前敏捷+15%，仅生效一次。\n强化+15：\n绝杀主炮有5%的概率造成10倍伤害。",
		"icon":"图标\\核心部件\\02绝杀.blp",
		"sc_射程":800,
		"ss_射速":0.1,
		"shgs_伤害公式":{
			"attack":1
		},
		"unique":true,
		"goldCost":2000,
		"pawnable":1,
		"attribute":{
			"attack_p":0.3,
			"agility_p":0.2
		}
	},
	{
		"id":"巫术炮弹",
		"class":"核心部件",
		"passive":false,
		"name":"巫术炮弹",
		"describe":"技能伤害+30%（+5%）\n智力加成+20%\n主炮：\n射程：600\n伤害：攻击力x20\n射速：5\n特殊：该主炮可攻击目标范围内550的所有敌人。\n强化+10：\n该炮弹造成伤害时有25%的概率变羊1秒。\n强化+15：\n该主炮射速翻倍。",
		"icon":"图标\\核心部件\\03巫术炮弹.blp",
		"最大目标数量":100,
		"sc_射程":600,
		"ss_射速":5,
		"shgs_伤害公式":{
			"attack":20
		},
		"unique":true,
		"goldCost":2000,
		"pawnable":1,
		"attribute":{
			"intelligence_p":0.2,
			"magic_damage_increased":0.3
		}
	},
	{
		"id":"洲际导弹",
		"class":"核心部件",
		"passive":false,
		"name":"洲际导弹",
		"describe":"全属性+2000（+1000）\n强化+10：\n无\n强化+15：\n所有主炮射程翻倍",
		"icon":"图标\\核心部件\\04洲际导弹.blp",
		"unique":true,
		"goldCost":2000,
		"pawnable":1,
		"attribute":{
			"full_property":2000
		}
	},
	{
		"id":"毒火炮",
		"class":"核心部件",
		"passive":false,
		"name":"毒火炮",
		"describe":"伤害加成+30%（+5%）\n主炮：\n射程：700\n伤害：攻击力x0.1\n射速：0.5\n特殊：毒火炮可攻击5个目标，该主炮造成伤害有10%概率使敌人进入毒火状态，受到任意伤害增加50%（+5%）的伤害，持续3秒。\n强化+10：\n毒火概率+5%\n强化+15：\n毒火持续时间+3秒。",
		"icon":"图标\\核心部件\\05毒火炮.blp",
		"sc_射程":700,
		"ss_射速":0.5,
		"shgs_伤害公式":{
			"attack":0.1
		},
		"unique":true,
		"goldCost":2000,
		"pawnable":1,
		"attribute":{
			"damage_increased":0.3
		}
	},
	{
		"id":"不朽甲板",
		"class":"核心部件",
		"passive":false,
		"name":"不朽甲板",
		"describe":"全属性+2000（+1000）\n强化+10：\n受到超过生命值25%的伤害时无敌0.5s\n强化+15：\n受到伤害不会超过生命值的30%",
		"icon":"图标\\核心部件\\06不朽甲板.blp",
		"unique":true,
		"goldCost":2000,
		"pawnable":1,
		"attribute":{
			"full_property":2000
		}
	},
	{
		"id":"光壁",
		"class":"核心部件",
		"passive":false,
		"name":"光壁",
		"describe":"护甲加成+30%（+5%）\n强化+10：\n受到伤害减少10%\n强化+15：\n每秒对身边500范围的敌人造成10000+3%生命最大值的真实伤害。",
		"icon":"图标\\核心部件\\07光壁.blp",
		"unique":true,
		"goldCost":2000,
		"pawnable":1,
		"attribute":{
			"damage_reduction":0.1
		}
	},
	{
		"id":"全面覆盖",
		"class":"核心部件",
		"passive":false,
		"name":"全面覆盖",
		"describe":"全属性+2000（+1000）\n强化+10：\n当前三围+10%，仅生效一次。\n强化+15：\n你三围最低的2个，会变得和最高的一样。",
		"icon":"图标\\核心部件\\08全面覆盖.blp",
		"unique":true,
		"goldCost":2000,
		"pawnable":1,
		"attribute":{
			"full_property":2000
		}
	},
	{
		"id":"古老者甲板",
		"class":"核心部件",
		"passive":false,
		"name":"古老者甲板",
		"describe":"全属性+2000（+1000）\n强化+10：\n每分钟获得1%全属性加成。\n强化+15：\n杀敌全属性+5",
		"icon":"图标\\核心部件\\09古老者甲板.blp",
		"unique":true,
		"goldCost":2000,
		"pawnable":1,
		"attribute":{
			"full_property":2000
		}
	},
	{
		"id":"曲率推进装置",
		"class":"核心部件",
		"passive":false,
		"name":"曲率推进装置",
		"describe":"航速+100（+20）\n强化+10：\n移动后会在路径上残留5秒的曲率波动，对触碰到的敌人每秒造成攻击力x3的伤害。\n强化+15：\n航速+100%",
		"icon":"图标\\核心部件\\10曲率推进装置.blp",
		"unique":true,
		"goldCost":2000,
		"pawnable":1,
		"attribute":{
			"move_speed":100
		}
	},
	{
		"id":"未来装置",
		"class":"核心部件",
		"passive":false,
		"name":"未来装置",
		"describe":"航速-100(+5)\n特殊：每次升级增加1%当前全属性。\n强化+10：\n经验加成+100%\n强化+15：\n杀敌经验值+1",
		"icon":"图标\\核心部件\\11未来装置.blp",
		"unique":true,
		"goldCost":2000,
		"pawnable":1,
		"attribute":{
			"move_speed":-100
		}
	},
	{
		"id":"神避",
		"class":"核心部件",
		"passive":false,
		"name":"神避",
		"describe":"BOSS增伤+30%（+5%）\n主炮：\n射程：1000\n伤害：攻击力x10\n射速：0.5\n特殊：该主炮只会对BOSS进行攻击。\n强化+10：\nBOSS伤害+50%\n强化+15：\n击杀BOSS增加当前15%攻击力。\n",
		"icon":"图标\\核心部件\\12神避.blp",
		"sc_射程":1000,
		"ss_射速":0.5,
		"shgs_伤害公式":{
			"attack":10
		},
		"unique":true,
		"goldCost":2000,
		"pawnable":1,
		"attribute":{
			"对英雄增加伤害":0.3
		}
	},
	{
		"id":"荒火引擎",
		"class":"核心部件",
		"passive":false,
		"name":"荒火引擎",
		"describe":"全属性+2000（+1000）\n特殊：无敌5秒，冷却15秒。\n强化+10：\n无敌期间移速+100%\n强化+15：\n无敌期间造成的伤害翻倍。",
		"icon":"图标\\核心部件\\13荒火引擎.blp",
		"unique":true,
		"goldCost":2000,
		"pawnable":1,
		"attribute":{
			"full_property":2000
		}
	}
]
export const d_核心部件 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
