//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	 passive = 是否被动(不可点击的装备)
	name = 名字
	describe = 提示说明
	icon = 图标
	goldCost = 金币消耗
	lumberCost = 木材消耗
	pawnable = 是否可抵押
	attributeintelligence = 属性附加
*/
export type data_type = {
	id?: string
	class?: string
	passive?: boolean
	name?: string
	describe?: string
	icon?: string
	goldCost?: number
	lumberCost?: any
	pawnable?: number
	attribute?: {
		intelligence?: number
		intelligence_p?: number
	}
    [key:string]: any
}

declare global {
    type t_桅杆 = data_type
}

export const data: data_type[] = [
	{
		"id":"桅杆Lv1",
		"class":"基础属性装备",
		"passive":true,
		"name":"桅杆Lv1",
		"describe":"智力+10",
		"icon":"物品图标\\桅杆\\桅杆1.blp",
		"goldCost":50.0,
		"pawnable":1,
		"attribute":{
			"intelligence":10
		}
	},
	{
		"id":"桅杆Lv2",
		"class":"基础属性装备",
		"passive":true,
		"name":"桅杆Lv2",
		"describe":"智力+20",
		"icon":"物品图标\\桅杆\\桅杆2.blp",
		"goldCost":100.0,
		"pawnable":1,
		"attribute":{
			"intelligence":20.0
		}
	},
	{
		"id":"桅杆Lv3",
		"class":"基础属性装备",
		"passive":true,
		"name":"桅杆Lv3",
		"describe":"智力+40",
		"icon":"物品图标\\桅杆\\桅杆3.blp",
		"goldCost":200.0,
		"pawnable":1,
		"attribute":{
			"intelligence":40.0
		}
	},
	{
		"id":"桅杆Lv4",
		"class":"基础属性装备",
		"passive":true,
		"name":"桅杆Lv4",
		"describe":"智力+80",
		"icon":"物品图标\\桅杆\\桅杆4.blp",
		"goldCost":400.0,
		"pawnable":1,
		"attribute":{
			"intelligence":80.0
		}
	},
	{
		"id":"桅杆Lv5",
		"class":"基础属性装备",
		"passive":true,
		"name":"桅杆Lv5",
		"describe":"智力+160",
		"icon":"物品图标\\桅杆\\桅杆5.blp",
		"goldCost":800.0,
		"pawnable":1,
		"attribute":{
			"intelligence":160.0
		}
	},
	{
		"id":"桅杆Lv6",
		"class":"基础属性装备",
		"passive":true,
		"name":"桅杆Lv6",
		"describe":"智力+320",
		"icon":"物品图标\\桅杆\\桅杆6.blp",
		"goldCost":1600.0,
		"pawnable":1,
		"attribute":{
			"intelligence":320.0
		}
	},
	{
		"id":"桅杆Lv7",
		"class":"基础属性装备",
		"passive":true,
		"name":"桅杆Lv7",
		"describe":"智力+640",
		"icon":"物品图标\\桅杆\\桅杆7.blp",
		"goldCost":3200.0,
		"pawnable":1,
		"attribute":{
			"intelligence":640.0
		}
	},
	{
		"id":"桅杆Lv8",
		"class":"基础属性装备",
		"passive":true,
		"name":"桅杆Lv8",
		"describe":"智力+1280",
		"icon":"物品图标\\桅杆\\桅杆8.blp",
		"goldCost":6400.0,
		"pawnable":1,
		"attribute":{
			"intelligence":1280.0
		}
	},
	{
		"id":"桅杆Lv9",
		"class":"基础属性装备",
		"passive":true,
		"name":"桅杆Lv9",
		"describe":"智力+2560 \n|n智力+10%|n\n|n|cffcccccc桅杆Lv9 + 桅杆Lv9 = 桅杆Lv10",
		"icon":"物品图标\\桅杆\\桅杆9.blp",
		"goldCost":12800.0,
		"pawnable":1,
		"attribute":{
			"intelligence_p":0.1,
			"intelligence":2560.0
		}
	},
	{
		"id":"桅杆Lv10",
		"class":"基础属性装备",
		"passive":false,
		"name":"桅杆Lv10",
		"describe":"智力+5120\n|n智力+20%|n\n|n|cffccccccLV10船头+LV10桅杆+LV10船帆+喋血炮x2+合成书=黑胡子|r\n|n|cffcccccc天雷炮+lv10桅杆x2+lv10炮弹x2+制作书=【雷霆支配者】|r\n|n|cffcccccc LV10船头+LV10桅杆+LV10船帆+lv10船身=【麦哲伦】|r",
		"icon":"物品图标\\桅杆\\桅杆10.blp",
		"goldCost":25600.0,
		"pawnable":1,
		"attribute":{
			"intelligence_p":0.2,
			"intelligence":5120.0
		}
	}
]
export const d_桅杆 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
