//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	 passive = 是否被动(不可点击的装备)
	name = 名字
	describe = 提示说明
	model = 模型
	icon = 图标
	unique = 唯一
	goldCost = 金币消耗
	lumberCost = 木材消耗
	pawnable = 是否可抵押
	maxCd = 冷却时间
	attribute = 属性附加
*/
export type data_type = {
	id?: string
	class?: string
	passive?: boolean
	name?: string
	describe?: string
	model?: string
	icon?: string
	unique?: boolean
	goldCost?: number
	lumberCost?: any
	pawnable?: number
	maxCd?: number
	attribute?: any
    [key:string]: any
}

declare global {
    type t_污染的航海器 = data_type
}

export const data: data_type[] = [
	{
		"id":"超级挑战",
		"class":"污染的航海器",
		"passive":false,
		"name":"超级挑战",
		"describe":"掉落污染的航海器。 挑战怪有90秒持续时间。每次挑战当前波数对应的超级怪！",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNRevenant.blp",
		"unique":true,
		"maxCd":90
	},
	{
		"id":"污染的航海器",
		"class":"污染的航海器",
		"passive":true,
		"name":"污染的航海器",
		"model":"model\\基础物品模型.mdx",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNDarkSummoning.blp",
		"unique":true,
		"goldCost":2000,
		"pawnable":1
	}
]
export const d_污染的航海器 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
