//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	 passive = 是否被动(不可点击的装备)
	name = 名字
	describe = 提示说明
	icon = 图标
	targetType = 目标类型
	goldCost = 金币消耗
	lumberCost = 木材消耗
	pawnable = 是否可抵押
	attribute = 属性附加
	stackMax = 最大堆叠
	destroyOnNoUses = 使用完销毁
*/
export type data_type = {
	id?: string
	class?: string
	passive?: boolean
	name?: string
	describe?: string
	icon?: string
	targetType?: any
	goldCost?: number
	lumberCost?: any
	pawnable?: boolean
	attribute?: any
	stackMax?: number
	destroyOnNoUses?: boolean
    [key:string]: any
}

declare global {
    type t_海上奇珍物品 = data_type
}

export const data: data_type[] = [
	{
		"id":"胶胶果实",
		"class":"海上奇珍",
		"passive":true,
		"name":"胶胶果实",
		"describe":"死亡后5秒复活，复活后拥有3秒无敌。可堆叠10个|n|cffcccccc 胶胶果实x20=【鲁灰】|r",
		"icon":"物品图标\\胶胶果实.blp",
		"goldCost":1400,
		"pawnable":true,
		"stackMax":10,
		"destroyOnNoUses":true
	},
	{
		"id":"杀敌抽奖",
		"class":"海上奇珍",
		"passive":true,
		"name":"杀敌抽奖",
		"describe":"消耗杀敌数随机获得一些属性或装备奖励！\n",
		"icon":"图标\\核心部件\\18杀敌抽奖.blp",
		"goldCost":0,
		"pawnable":false
	},
	{
		"id":"修炼",
		"class":"海上奇珍",
		"passive":true,
		"name":"修炼",
		"describe":"奖励三选一，选完进入下一层",
		"icon":"图标\\核心部件\\19金币.blp",
		"goldCost":0,
		"pawnable":false
	},
	{
		"id":"核心部件",
		"class":"海上奇珍",
		"passive":true,
		"name":"核心部件",
		"describe":"随机获得一个核心部件！\n点击可以消耗金币强化\n每次强化可以获得括号后面的数值增长\n11-12级强化失败有几率回退到1级\n13-15级强化失败有几率回退到10级",
		"icon":"图标\\核心部件\\14奇珍商店.blp",
		"goldCost":0,
		"lumberCost":1,
		"pawnable":false
	},
	{
		"id":"吞天石",
		"class":"海上奇珍",
		"passive":false,
		"name":"吞天石",
		"describe":"可以吞噬任意东西,比如物品、天赋、技能、主炮。\n宝宝使用此物品可以复制吞噬队友的天赋技能、主炮。\n(部分特殊效果不会生效：比如允许上岸，允许普通攻击)\n基础吞噬上限2。",
		"icon":"图标\\存档\\吞天石.blp",
		"targetType":"无目标",
		"goldCost":50000,
		"pawnable":false,
		"stackMax":10,
		"destroyOnNoUses":true
	},
	{
		"id":"船长信件",
		"class":"海上奇珍",
		"passive":false,
		"name":"船长信件",
		"describe":"可以吞噬一个船长道具。吞噬上限2",
		"icon":"图标\\核心部件\\17船长信件.blp",
		"targetType":"物品",
		"goldCost":200000,
		"pawnable":false,
		"stackMax":10,
		"destroyOnNoUses":true
	},
	{
		"id":"改造设计图",
		"class":"海上奇珍",
		"passive":false,
		"name":"改造设计图",
		"describe":"对核心部件进行改造\n|cffcccccc(核心部件在难度4以上海上奇珍木材抽奖获得)",
		"icon":"图标\\核心部件\\15改造设计图.blp",
		"targetType":"物品",
		"lumberCost":1,
		"pawnable":true,
		"stackMax":10,
		"destroyOnNoUses":true
	},
	{
		"id":"天工图",
		"class":"海上奇珍",
		"passive":false,
		"name":"天工图",
		"describe":"对核心部件强化时100%成功\n|cffcccccc(核心部件在难度4以上海上奇珍木材抽奖获得)",
		"icon":"图标\\核心部件\\16天工图.blp",
		"targetType":"物品",
		"lumberCost":1,
		"pawnable":true,
		"stackMax":10,
		"destroyOnNoUses":true
	}
]
export const d_海上奇珍物品 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
