//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	 passive = 是否被动(不可点击的装备)
	name = 名字
	describe = 提示说明
	icon = 图标
	targetType = 目标类型
	goldCost = 金币消耗
	lumberCost = 木材消耗
	pawnable = 是否可抵押
	attribute = 属性附加
	stackMax = 最大堆叠
	destroyOnNoUses = 使用完销毁
*/
export type data_type = {
	id?: string
	class?: string
	passive?: boolean
	name?: string
	describe?: string
	icon?: string
	targetType?: any
	goldCost?: number
	lumberCost?: any
	pawnable?: any
	attribute?: any
	stackMax?: any
	destroyOnNoUses?: any
    [key:string]: any
}

declare global {
    type t_深海奇珍物品 = data_type
}

export const data: data_type[] = [
	{
		"id":"深海下一关",
		"class":"深海奇珍物品",
		"passive":true,
		"name":"深海下一关",
		"describe":"深海下一关",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCrystalBall.blp",
		"goldCost":0
	}
]
export const d_深海奇珍物品 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
