//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	 passive = 是否被动(不可点击的装备)
	name = 名字
	describe = 提示说明
	icon = 图标
	goldCost = 金币消耗
	lumberCost = 木材消耗
	pawnable = 是否可抵押
	attributeattack = 属性附加
*/
export type data_type = {
	id?: string
	class?: string
	passive?: boolean
	name?: string
	describe?: string
	icon?: string
	goldCost?: number
	lumberCost?: any
	pawnable?: number
	attribute?: {
		attack?: number
		attack_p?: number
	}
    [key:string]: any
}

declare global {
    type t_炮弹 = data_type
}

export const data: data_type[] = [
	{
		"id":"炮弹Lv1",
		"class":"基础属性装备",
		"passive":true,
		"name":"炮弹Lv1",
		"describe":"攻击力+15",
		"icon":"物品图标\\炮弹\\炮弹1.blp",
		"goldCost":50,
		"pawnable":1,
		"attribute":{
			"attack":15
		}
	},
	{
		"id":"炮弹Lv2",
		"class":"基础属性装备",
		"passive":true,
		"name":"炮弹Lv2",
		"describe":"攻击力+30",
		"icon":"物品图标\\炮弹\\炮弹2.blp",
		"goldCost":100,
		"pawnable":1,
		"attribute":{
			"attack":30.0
		}
	},
	{
		"id":"炮弹Lv3",
		"class":"基础属性装备",
		"passive":true,
		"name":"炮弹Lv3",
		"describe":"攻击力+60",
		"icon":"物品图标\\炮弹\\炮弹3.blp",
		"goldCost":200,
		"pawnable":1,
		"attribute":{
			"attack":60.0
		}
	},
	{
		"id":"炮弹Lv4",
		"class":"基础属性装备",
		"passive":true,
		"name":"炮弹Lv4",
		"describe":"攻击力+120",
		"icon":"物品图标\\炮弹\\炮弹4.blp",
		"goldCost":300,
		"pawnable":1,
		"attribute":{
			"attack":120.0
		}
	},
	{
		"id":"炮弹Lv5",
		"class":"基础属性装备",
		"passive":true,
		"name":"炮弹Lv5",
		"describe":"攻击力+240",
		"icon":"物品图标\\炮弹\\炮弹5.blp",
		"goldCost":500,
		"pawnable":1,
		"attribute":{
			"attack":240.0
		}
	},
	{
		"id":"炮弹Lv6",
		"class":"基础属性装备",
		"passive":true,
		"name":"炮弹Lv6",
		"describe":"攻击力+480",
		"icon":"物品图标\\炮弹\\炮弹6.blp",
		"goldCost":1000,
		"pawnable":1,
		"attribute":{
			"attack":480.0
		}
	},
	{
		"id":"炮弹Lv7",
		"class":"基础属性装备",
		"passive":true,
		"name":"炮弹Lv7",
		"describe":"攻击力+960",
		"icon":"物品图标\\炮弹\\炮弹7.blp",
		"goldCost":2000,
		"pawnable":1,
		"attribute":{
			"attack":960.0
		}
	},
	{
		"id":"炮弹Lv8",
		"class":"基础属性装备",
		"passive":true,
		"name":"炮弹Lv8",
		"describe":"攻击力+1920",
		"icon":"物品图标\\炮弹\\炮弹8.blp",
		"goldCost":4000,
		"pawnable":1,
		"attribute":{
			"attack":1920.0
		}
	},
	{
		"id":"炮弹Lv9",
		"class":"基础属性装备",
		"passive":true,
		"name":"炮弹Lv9",
		"describe":"攻击力+3840\n|n攻击力+10%|n\n |n|cffcccccc炮弹Lv9 + 炮弹Lv9 = 炮弹Lv10",
		"icon":"物品图标\\炮弹\\炮弹9.blp",
		"goldCost":8000,
		"pawnable":1,
		"attribute":{
			"attack_p":0.1,
			"attack":3840.0
		}
	},
	{
		"id":"炮弹Lv10",
		"class":"基础属性装备",
		"passive":false,
		"name":"炮弹Lv10",
		"describe":"攻击力+7680\n|n攻击力+20%|n\n|cffcccccclv10炮弹x2++LV10甲板+制作书 = 白胡子|r\n|n|cffcccccc天雷炮+lv10桅杆x2+lv10炮弹x2+制作书=【雷霆支配者】|r\n|n|cffcccccc 破甲装置+致命炮+lv10炮弹=【两仪式】|r",
		"icon":"物品图标\\炮弹\\炮弹10.blp",
		"goldCost":15360.0,
		"pawnable":1,
		"attribute":{
			"attack_p":0.2,
			"attack":7680.0
		}
	}
]
export const d_炮弹 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
