//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	 passive = 是否被动(不可点击的装备)
	name = 名字
	describe = 提示说明
	icon = 图标
	goldCost = 金币消耗
	lumberCost = 木材消耗
	pawnable = 是否可抵押
	attributedef = 属性附加
*/
export type data_type = {
	id?: string
	class?: string
	passive?: boolean
	name?: string
	describe?: string
	icon?: string
	goldCost?: number
	lumberCost?: any
	pawnable?: number
	attribute?: {
		def?: number
		def_p?: number
	}
    [key:string]: any
}

declare global {
    type t_甲板 = data_type
}

export const data: data_type[] = [
	{
		"id":"甲板Lv1",
		"class":"基础属性装备",
		"passive":true,
		"name":"甲板Lv1",
		"describe":"护甲+5",
		"icon":"物品图标\\甲板\\甲板1.blp",
		"goldCost":100,
		"pawnable":1,
		"attribute":{
			"def":5
		}
	},
	{
		"id":"甲板Lv2",
		"class":"基础属性装备",
		"passive":true,
		"name":"甲板Lv2",
		"describe":"护甲+10",
		"icon":"物品图标\\甲板\\甲板2.blp",
		"goldCost":500,
		"pawnable":1,
		"attribute":{
			"def":10
		}
	},
	{
		"id":"甲板Lv3",
		"class":"基础属性装备",
		"passive":true,
		"name":"甲板Lv3",
		"describe":"护甲+20",
		"icon":"物品图标\\甲板\\甲板3.blp",
		"goldCost":1000.0,
		"pawnable":1,
		"attribute":{
			"def":20
		}
	},
	{
		"id":"甲板Lv4",
		"class":"基础属性装备",
		"passive":true,
		"name":"甲板Lv4",
		"describe":"护甲+30",
		"icon":"物品图标\\甲板\\甲板4.blp",
		"goldCost":1500.0,
		"pawnable":1,
		"attribute":{
			"def":30
		}
	},
	{
		"id":"甲板Lv5",
		"class":"基础属性装备",
		"passive":true,
		"name":"甲板Lv5",
		"describe":"护甲+50",
		"icon":"物品图标\\甲板\\甲板5.blp",
		"goldCost":2500.0,
		"pawnable":1,
		"attribute":{
			"def":50
		}
	},
	{
		"id":"甲板Lv6",
		"class":"基础属性装备",
		"passive":true,
		"name":"甲板Lv6",
		"describe":"护甲+60",
		"icon":"物品图标\\甲板\\甲板6.blp",
		"goldCost":3000.0,
		"pawnable":1,
		"attribute":{
			"def":60
		}
	},
	{
		"id":"甲板Lv7",
		"class":"基础属性装备",
		"passive":true,
		"name":"甲板Lv7",
		"describe":"护甲+80",
		"icon":"物品图标\\甲板\\甲板7.blp",
		"goldCost":4000.0,
		"pawnable":1,
		"attribute":{
			"def":80
		}
	},
	{
		"id":"甲板Lv8",
		"class":"基础属性装备",
		"passive":true,
		"name":"甲板Lv8",
		"describe":"护甲+100",
		"icon":"物品图标\\甲板\\甲板8.blp",
		"goldCost":5000.0,
		"pawnable":1,
		"attribute":{
			"def":100
		}
	},
	{
		"id":"甲板Lv9",
		"class":"基础属性装备",
		"passive":true,
		"name":"甲板Lv9",
		"describe":"护甲+150\n|n护甲+10% ",
		"icon":"物品图标\\甲板\\甲板9.blp",
		"goldCost":7500.0,
		"pawnable":1,
		"attribute":{
			"def":150,
			"def_p":0.1
		}
	},
	{
		"id":"甲板Lv10",
		"class":"基础属性装备",
		"passive":false,
		"name":"甲板Lv10",
		"describe":"护甲+300\n|n护甲+20%|n\n|cffcccccclv10炮弹x2++LV10甲板+制作书 = 白胡子|r",
		"icon":"物品图标\\甲板\\甲板10.blp",
		"goldCost":15000.0,
		"pawnable":1,
		"attribute":{
			"def":300,
			"def_p":0.2
		}
	}
]
export const d_甲板 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
