//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	 passive = 是否被动(不可点击的装备)
	name = 名字
	describe = 提示说明
	icon = 图标
	goldCost = 金币消耗
	lumberCost = 木材消耗
	pawnable = 是否可抵押
	attributeagility = 属性附加
*/
export type data_type = {
	id?: string
	class?: string
	passive?: boolean
	name?: string
	describe?: string
	icon?: string
	goldCost?: number
	lumberCost?: any
	pawnable?: number
	attribute?: {
		agility?: number
		agility_p?: number
	}
    [key:string]: any
}

declare global {
    type t_船帆 = data_type
}

export const data: data_type[] = [
	{
		"id":"船帆Lv1",
		"class":"基础属性装备",
		"passive":true,
		"name":"船帆Lv1",
		"describe":"敏捷+10",
		"icon":"物品图标\\船帆\\船帆1.blp",
		"goldCost":50.0,
		"pawnable":1,
		"attribute":{
			"agility":10
		}
	},
	{
		"id":"船帆Lv2",
		"class":"基础属性装备",
		"passive":true,
		"name":"船帆Lv2",
		"describe":"敏捷+20",
		"icon":"物品图标\\船帆\\船帆2.blp",
		"goldCost":100.0,
		"pawnable":1,
		"attribute":{
			"agility":20.0
		}
	},
	{
		"id":"船帆Lv3",
		"class":"基础属性装备",
		"passive":true,
		"name":"船帆Lv3",
		"describe":"敏捷+40",
		"icon":"物品图标\\船帆\\船帆3.blp",
		"goldCost":200.0,
		"pawnable":1,
		"attribute":{
			"agility":40.0
		}
	},
	{
		"id":"船帆Lv4",
		"class":"基础属性装备",
		"passive":true,
		"name":"船帆Lv4",
		"describe":"敏捷+80",
		"icon":"物品图标\\船帆\\船帆4.blp",
		"goldCost":400.0,
		"pawnable":1,
		"attribute":{
			"agility":80.0
		}
	},
	{
		"id":"船帆Lv5",
		"class":"基础属性装备",
		"passive":true,
		"name":"船帆Lv5",
		"describe":"敏捷+160",
		"icon":"物品图标\\船帆\\船帆5.blp",
		"goldCost":800.0,
		"pawnable":1,
		"attribute":{
			"agility":160.0
		}
	},
	{
		"id":"船帆Lv6",
		"class":"基础属性装备",
		"passive":true,
		"name":"船帆Lv6",
		"describe":"敏捷+320",
		"icon":"物品图标\\船帆\\船帆6.blp",
		"goldCost":1600.0,
		"pawnable":1,
		"attribute":{
			"agility":320.0
		}
	},
	{
		"id":"船帆Lv7",
		"class":"基础属性装备",
		"passive":true,
		"name":"船帆Lv7",
		"describe":"敏捷+640",
		"icon":"物品图标\\船帆\\船帆7.blp",
		"goldCost":3200.0,
		"pawnable":1,
		"attribute":{
			"agility":640.0
		}
	},
	{
		"id":"船帆Lv8",
		"class":"基础属性装备",
		"passive":true,
		"name":"船帆Lv8",
		"describe":"敏捷+1280",
		"icon":"物品图标\\船帆\\船帆8.blp",
		"goldCost":6400.0,
		"pawnable":1,
		"attribute":{
			"agility":1280.0
		}
	},
	{
		"id":"船帆Lv9",
		"class":"基础属性装备",
		"passive":true,
		"name":"船帆Lv9",
		"describe":"敏捷+2560\n|n敏捷+10%|n\n |n|cffcccccc船帆Lv9 + 船帆Lv9 = 船帆Lv10",
		"icon":"物品图标\\船帆\\船帆9.blp",
		"goldCost":12800.0,
		"pawnable":1,
		"attribute":{
			"agility_p":0.1,
			"agility":2560.0
		}
	},
	{
		"id":"船帆Lv10",
		"class":"基础属性装备",
		"passive":false,
		"name":"船帆Lv10",
		"describe":"敏捷+5120\n|n敏捷+20%|n\n|n|cffccccccLV10船头+LV10桅杆+LV10船帆+喋血炮x2+合成书=黑胡子|r\n|n|cffcccccc LV10船头+LV10桅杆+LV10船帆+lv10船身=【麦哲伦】|r\n|n|cffcccccc 刮痧装置+lv10船帆x2+制作书=【小丑】|r",
		"icon":"物品图标\\船帆\\船帆10.blp",
		"goldCost":25600.0,
		"pawnable":1,
		"attribute":{
			"agility_p":0.2,
			"agility":5120.0
		}
	}
]
export const d_船帆 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
