//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	 passive = 是否被动(不可点击的装备)
	name = 名字
	describe = 提示说明
	icon = 图标
	goldCost = 金币消耗
	lumberCost = 木材消耗
	pawnable = 是否可抵押
	attributestrength = 属性附加
*/
export type data_type = {
	id?: string
	class?: string
	passive?: boolean
	name?: string
	describe?: string
	icon?: string
	goldCost?: number
	lumberCost?: any
	pawnable?: number
	attribute?: {
		strength?: number
		strength_p?: number
	}
    [key:string]: any
}

declare global {
    type t_船头 = data_type
}

export const data: data_type[] = [
	{
		"id":"船头Lv1",
		"class":"基础属性装备",
		"passive":true,
		"name":"船头Lv1",
		"describe":"力量+10",
		"icon":"物品图标\\船头\\船头1.blp",
		"goldCost":50.0,
		"pawnable":1,
		"attribute":{
			"strength":10
		}
	},
	{
		"id":"船头Lv2",
		"class":"基础属性装备",
		"passive":true,
		"name":"船头Lv2",
		"describe":"力量+20",
		"icon":"物品图标\\船头\\船头2.blp",
		"goldCost":100.0,
		"pawnable":1,
		"attribute":{
			"strength":20.0
		}
	},
	{
		"id":"船头Lv3",
		"class":"基础属性装备",
		"passive":true,
		"name":"船头Lv3",
		"describe":"力量+40",
		"icon":"物品图标\\船头\\船头3.blp",
		"goldCost":200.0,
		"pawnable":1,
		"attribute":{
			"strength":40.0
		}
	},
	{
		"id":"船头Lv4",
		"class":"基础属性装备",
		"passive":true,
		"name":"船头Lv4",
		"describe":"力量+80",
		"icon":"物品图标\\船头\\船头4.blp",
		"goldCost":400.0,
		"pawnable":1,
		"attribute":{
			"strength":80.0
		}
	},
	{
		"id":"船头Lv5",
		"class":"基础属性装备",
		"passive":true,
		"name":"船头Lv5",
		"describe":"力量+160",
		"icon":"物品图标\\船头\\船头5.blp",
		"goldCost":800.0,
		"pawnable":1,
		"attribute":{
			"strength":160.0
		}
	},
	{
		"id":"船头Lv6",
		"class":"基础属性装备",
		"passive":true,
		"name":"船头Lv6",
		"describe":"力量+320",
		"icon":"物品图标\\船头\\船头6.blp",
		"goldCost":1600.0,
		"pawnable":1,
		"attribute":{
			"strength":320.0
		}
	},
	{
		"id":"船头Lv7",
		"class":"基础属性装备",
		"passive":true,
		"name":"船头Lv7",
		"describe":"力量+640",
		"icon":"物品图标\\船头\\船头7.blp",
		"goldCost":3200.0,
		"pawnable":1,
		"attribute":{
			"strength":640.0
		}
	},
	{
		"id":"船头Lv8",
		"class":"基础属性装备",
		"passive":true,
		"name":"船头Lv8",
		"describe":"力量+1280",
		"icon":"物品图标\\船头\\船头8.blp",
		"goldCost":6400.0,
		"pawnable":1,
		"attribute":{
			"strength":1280.0
		}
	},
	{
		"id":"船头Lv9",
		"class":"基础属性装备",
		"passive":true,
		"name":"船头Lv9",
		"describe":"力量+2560 \n|n力量+10%|n\n|n|cffcccccc船头Lv9 + 船头Lv9 = 船头Lv10",
		"icon":"物品图标\\船头\\船头9.blp",
		"goldCost":12800.0,
		"pawnable":1,
		"attribute":{
			"strength_p":0.1,
			"strength":2560.0
		}
	},
	{
		"id":"船头Lv10",
		"class":"基础属性装备",
		"passive":false,
		"name":"船头Lv10",
		"describe":"力量+5120|n力量+20%|n|cffccccccLV10船头+LV10桅杆+LV10船帆+喋血炮x2+合成书=黑胡子|r\n|n|cffcccccc LV10船头+LV10桅杆+LV10船帆+lv10船身=【麦哲伦】|r",
		"icon":"物品图标\\船头\\船头10.blp",
		"goldCost":25600.0,
		"pawnable":1,
		"attribute":{
			"strength_p":0.2,
			"strength":5120.0
		}
	}
]
export const d_船头 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
