//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	 passive = 是否被动(不可点击的装备)
	name = 名字
	describe = 提示说明
	icon = 图标
	goldCost = 金币消耗
	lumberCost = 木材消耗
	pawnable = 是否可抵押
	attributelife = 属性附加
*/
export type data_type = {
	id?: string
	class?: string
	passive?: boolean
	name?: string
	describe?: string
	icon?: string
	goldCost?: number
	lumberCost?: any
	pawnable?: number
	attribute?: {
		life?: number
		damage_reduction?: number
	}
    [key:string]: any
}

declare global {
    type t_船身 = data_type
}

export const data: data_type[] = [
	{
		"id":"船身Lv1",
		"class":"基础属性装备",
		"passive":true,
		"name":"船身Lv1",
		"describe":"生命值+100",
		"icon":"物品图标\\船身\\船身1.blp",
		"goldCost":50.0,
		"pawnable":1,
		"attribute":{
			"life":100
		}
	},
	{
		"id":"船身Lv2",
		"class":"基础属性装备",
		"passive":true,
		"name":"船身Lv2",
		"describe":"生命值+200",
		"icon":"物品图标\\船身\\船身2.blp",
		"goldCost":100.0,
		"pawnable":1,
		"attribute":{
			"life":200.0
		}
	},
	{
		"id":"船身Lv3",
		"class":"基础属性装备",
		"passive":true,
		"name":"船身Lv3",
		"describe":"生命值+400",
		"icon":"物品图标\\船身\\船身3.blp",
		"goldCost":200.0,
		"pawnable":1,
		"attribute":{
			"life":400.0
		}
	},
	{
		"id":"船身Lv4",
		"class":"基础属性装备",
		"passive":true,
		"name":"船身Lv4",
		"describe":"生命值+800",
		"icon":"物品图标\\船身\\船身4.blp",
		"goldCost":400.0,
		"pawnable":1,
		"attribute":{
			"life":800.0
		}
	},
	{
		"id":"船身Lv5",
		"class":"基础属性装备",
		"passive":true,
		"name":"船身Lv5",
		"describe":"生命值+1600",
		"icon":"物品图标\\船身\\船身5.blp",
		"goldCost":800.0,
		"pawnable":1,
		"attribute":{
			"life":1600.0
		}
	},
	{
		"id":"船身Lv6",
		"class":"基础属性装备",
		"passive":true,
		"name":"船身Lv6",
		"describe":"生命值+3200",
		"icon":"物品图标\\船身\\船身6.blp",
		"goldCost":1600.0,
		"pawnable":1,
		"attribute":{
			"life":3200.0
		}
	},
	{
		"id":"船身Lv7",
		"class":"基础属性装备",
		"passive":true,
		"name":"船身Lv7",
		"describe":"生命值+6400",
		"icon":"物品图标\\船身\\船身7.blp",
		"goldCost":3200.0,
		"pawnable":1,
		"attribute":{
			"life":6400.0
		}
	},
	{
		"id":"船身Lv8",
		"class":"基础属性装备",
		"passive":true,
		"name":"船身Lv8",
		"describe":"生命值+12800",
		"icon":"物品图标\\船身\\船身8.blp",
		"goldCost":6400.0,
		"pawnable":1,
		"attribute":{
			"life":12800.0
		}
	},
	{
		"id":"船身Lv9",
		"class":"基础属性装备",
		"passive":true,
		"name":"船身Lv9",
		"describe":"生命值+25600\n伤害减免+2%",
		"icon":"物品图标\\船身\\船身9.blp",
		"goldCost":12800.0,
		"pawnable":1,
		"attribute":{
			"damage_reduction":0.02,
			"life":25600.0
		}
	},
	{
		"id":"船身Lv10",
		"class":"基础属性装备",
		"passive":false,
		"name":"船身Lv10",
		"describe":"生命值+51200\n伤害减免+5%\n|n|cffcccccc LV10船头+LV10桅杆+LV10船帆+lv10船身=【麦哲伦】|r",
		"icon":"物品图标\\船身\\船身10.blp",
		"goldCost":25600.0,
		"pawnable":1,
		"attribute":{
			"damage_reduction":0.05,
			"life":51200.0
		}
	}
]
export const d_船身 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
