//Generated By Solar Editor

import GradeUtil from "@/GradeUtil"
import AttributeUtil from "@/AttributeUtil"
/**
	id = id
	_parent = 父id
	Name = 名字
	来源 = 来源
	type = 类型
	grade = 品级
	Art = 图标 - 普通
	Ubertip = 说明
	file = 模型文件
	hc_合成 = 合成
	goldcost = 黄金消耗
	abilList = 技能列表
	pawnable = 可以被抵押
	stockMax = 最大库存量
	stockRegen = 购买时间间隔
	usable = 主动使用
	attack = 攻击力
	add_strength_on_kill = 杀敌加力
	add_agility_on_kill = 杀敌加敏捷
	add_intelligence_on_kill = 杀敌加智力
	attack_p = 攻击力增幅
	attackSpd_p = 攻击速度
	def = 护甲
	full_property = 全属性
	strength = 力量
	agility = 敏捷
	intelligence = 智力
	life = 生命值
	mana = 魔法值
	full_property_p = 全属性增幅
	strength_p = 力量增幅
	agility_p = 敏捷增幅
	intelligence_p = 智力增幅
	physical_critical_chance = 物理暴击几率
	physical_critical_damage = 物理暴击伤害
	physical_damage_increased = 物理增伤
	magic_critical_chance = 法术暴击几率
	magic_critical_damage = 法术暴击伤害
	magic_damage_increased = 法术增伤
	damage_increased = 全伤加深
	attack_damage_increased = 攻击增伤
	move_speed = 移动速度
	damage_cool = 攻击间隔
	damage_range = 攻击范围
	damage_reduction = 伤害减免
	blood_sucking = 攻击吸血
*/
export type data_type = {
	id?: string
	_parent?: string
	Name?: string
	来源?: string
	type?: string
	grade?: any
	Art?: string
	Ubertip?: string
	file?: any
	hc_合成?: any
	goldcost?: number
	abilList?: any
	pawnable?: number
	stockMax?: number
	stockRegen?: number
	usable?: any
	attack?: any
	add_strength_on_kill?: any
	add_agility_on_kill?: any
	add_intelligence_on_kill?: any
	attack_p?: any
	attackSpd_p?: any
	def?: any
	full_property?: any
	strength?: any
	agility?: any
	intelligence?: any
	life?: any
	mana?: any
	full_property_p?: any
	strength_p?: any
	agility_p?: any
	intelligence_p?: any
	physical_critical_chance?: any
	physical_critical_damage?: any
	physical_damage_increased?: any
	magic_critical_chance?: any
	magic_critical_damage?: any
	magic_damage_increased?: any
	damage_increased?: any
	attack_damage_increased?: any
	move_speed?: any
	damage_cool?: any
	damage_range?: any
	damage_reduction?: any
	blood_sucking?: any
    [key:string]: any
}

declare global {
    type t_船长 = data_type
}

export const data: data_type[] = [
	{
		"id":"a41s",
		"_parent":"azhr",
		"Name":"赏金王",
		"来源":"购买",
		"type":"船长",
		"Art":"物品图标\\船长\\高级\\船长赏金王.blp",
		"Ubertip":"每次造成伤害，可获得5金币。\n|n|cffcccccc 赏金王+强盗王+山贼王+海贼王=【娜米】|r",
		"goldcost":500,
		"Description":"每次造成伤害，可获得5金币。\n|n|cffcccccc 赏金王+强盗王+山贼王+海贼王=【娜米】|r",
		"Tip":"赏金王",
		"pawnable":1,
		"stockMax":1,
		"stockRegen":0
	},
	{
		"id":"a41t",
		"_parent":"azhr",
		"Name":"强盗王",
		"来源":"购买",
		"type":"船长",
		"Art":"物品图标\\船长\\高级\\船长强盗王.blp",
		"Ubertip":"每次造成伤害，可获得8金币。|n|cffcccccc 赏金王+强盗王+山贼王+海贼王=【娜米】|r",
		"goldcost":4000,
		"Description":"每次造成伤害，可获得8金币。|n|cffcccccc 赏金王+强盗王+山贼王+海贼王=【娜米】|r",
		"Tip":"强盗王",
		"pawnable":1,
		"stockMax":1,
		"stockRegen":0
	},
	{
		"id":"a41u",
		"_parent":"azhr",
		"Name":"山贼王",
		"来源":"购买",
		"type":"船长",
		"Art":"物品图标\\船长\\高级\\船长山贼王.blp",
		"Ubertip":"每次造成伤害，可获得目标10%原本赏金的金币。|n|cffcccccc 赏金王+强盗王+山贼王+海贼王=【娜米】|r",
		"goldcost":12000,
		"Description":"每次造成伤害，可获得目标10%原本赏金的金币。|n|cffcccccc 赏金王+强盗王+山贼王+海贼王=【娜米】|r",
		"Tip":"山贼王",
		"pawnable":1,
		"stockMax":1,
		"stockRegen":0
	},
	{
		"id":"a41v",
		"_parent":"azhr",
		"Name":"海贼王",
		"来源":"购买",
		"type":"船长",
		"Art":"物品图标\\船长\\高级\\船长海贼王.blp",
		"Ubertip":"每次造成伤害，可获得目标20%原本赏金的金币。|n|cffcccccc 赏金王+强盗王+山贼王+海贼王=【娜米】|r",
		"goldcost":100000,
		"Description":"每次造成伤害，可获得目标20%原本赏金的金币。|n|cffcccccc 赏金王+强盗王+山贼王+海贼王=【娜米】|r",
		"Tip":"海贼王",
		"pawnable":1,
		"stockMax":1,
		"stockRegen":0
	}
]
export const d_船长 = data;


//code
export default function(){
 
    for (let datum of data) {
        if (datum.id && datum.grade) {
            GradeUtil.setItemTypeGrade(datum.id, datum.grade)
        }
    }

    for (let datum of data) {
        if (datum && datum.id) { 
            AttributeUtil.setItemTypeAttribute(datum.id,datum)
        }
    }
}
