//Generated By Solar Editor

/**
	id = id
	_parent = 父id
	Name = 名字
	HP = 生命值
	goldcost = 黄金消耗
	lumbercost = 木材消耗
	Art = 图标 - 普通
	usable = 主动使用
	perishable = 使用完会消失
	powerup = 捡取时自动使用
	abilList = 技能
	Level = 等级
	stockMax = 最大库存量
	stockRegen = 购买时间间隔
*/
export type data_type = {
	id?: string
	_parent?: string
	Name?: string
	HP?: number
	goldcost?: number
	lumbercost?: number
	Art?: string
	usable?: number
	perishable?: number
	powerup?: number
	abilList?: string
	Level?: number
	stockMax?: number
	stockRegen?: number
    [key:string]: any
}

declare global {
    type t_藏宝图 = data_type
}

export const data: data_type[] = [
	{
		"id":"a459",
		"_parent":"manh",
		"Name":"水手寻宝图",
		"HP":100,
		"goldcost":1000,
		"lumbercost":0,
		"Art":"ReplaceableTextures\\CommandButtons\\BTNTome.blp",
		"usable":0,
		"perishable":0,
		"powerup":0,
		"abilList":"",
		"Level":8,
		"stockMax":99,
		"stockRegen":1,
		"Ubertip":"水手寻宝图",
		"Description":"水手寻宝图",
		"Tip":"水手寻宝图"
	},
	{
		"id":"a45a",
		"_parent":"manh",
		"Name":"冰霜寻宝图",
		"HP":100,
		"goldcost":200,
		"lumbercost":0,
		"Art":"ReplaceableTextures\\CommandButtons\\BTNTome.blp",
		"usable":0,
		"perishable":0,
		"powerup":0,
		"abilList":"",
		"Level":8,
		"stockMax":99,
		"stockRegen":1,
		"Ubertip":"冰霜寻宝图",
		"Description":"冰霜寻宝图",
		"Tip":"冰霜寻宝图"
	},
	{
		"id":"a45b",
		"_parent":"manh",
		"Name":"黑色寻宝图",
		"HP":100,
		"goldcost":200,
		"lumbercost":0,
		"Art":"ReplaceableTextures\\CommandButtons\\BTNTome.blp",
		"usable":0,
		"perishable":0,
		"powerup":0,
		"abilList":"",
		"Level":8,
		"stockMax":99,
		"stockRegen":1,
		"Ubertip":"黑色寻宝图",
		"Description":"黑色寻宝图",
		"Tip":"黑色寻宝图"
	},
	{
		"id":"a45c",
		"_parent":"manh",
		"Name":"黄金寻宝图",
		"HP":100,
		"goldcost":1000,
		"lumbercost":0,
		"Art":"ReplaceableTextures\\CommandButtons\\BTNTomeRed.blp",
		"usable":0,
		"perishable":0,
		"powerup":0,
		"abilList":"",
		"Level":8,
		"stockMax":99,
		"stockRegen":1,
		"Ubertip":"黄金寻宝图",
		"Description":"黄金寻宝图",
		"Tip":"黄金寻宝图"
	}
]
export const d_藏宝图 = data;


//code
export default function(){
}
