//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	 passive = 是否被动(不可点击的装备)
	name = 名字
	describe = 提示说明
	icon = 图标
	goldCost = 金币消耗
	lumberCost = 木材消耗
	pawnable = 是否可抵押
	attributemove_speed = 属性附加
*/
export type data_type = {
	id?: string
	class?: string
	passive?: boolean
	name?: string
	describe?: string
	icon?: string
	goldCost?: number
	lumberCost?: any
	pawnable?: number
	attribute?: {
		move_speed?: number
		full_property_p?: number
	}
    [key:string]: any
}

declare global {
    type t_马达 = data_type
}

export const data: data_type[] = [
	{
		"id":"马达Lv1",
		"class":"基础属性装备",
		"passive":true,
		"name":"马达Lv1",
		"describe":"移动速度+20",
		"icon":"物品图标\\马达\\马达1.blp",
		"goldCost":200.0,
		"pawnable":1,
		"attribute":{
			"move_speed":20
		}
	},
	{
		"id":"马达Lv2",
		"class":"基础属性装备",
		"passive":true,
		"name":"马达Lv2",
		"describe":"移动速度+40",
		"icon":"物品图标\\马达\\马达2.blp",
		"goldCost":400.0,
		"pawnable":1,
		"attribute":{
			"move_speed":40
		}
	},
	{
		"id":"马达Lv3",
		"class":"基础属性装备",
		"passive":true,
		"name":"马达Lv3",
		"describe":"移动速度+60",
		"icon":"物品图标\\马达\\马达3.blp",
		"goldCost":600.0,
		"pawnable":1,
		"attribute":{
			"move_speed":60
		}
	},
	{
		"id":"马达Lv4",
		"class":"基础属性装备",
		"passive":true,
		"name":"马达Lv4",
		"describe":"移动速度+80",
		"icon":"物品图标\\马达\\马达4.blp",
		"goldCost":800.0,
		"pawnable":1,
		"attribute":{
			"move_speed":80
		}
	},
	{
		"id":"马达Lv5",
		"class":"基础属性装备",
		"passive":true,
		"name":"马达Lv5",
		"describe":"移动速度+120",
		"icon":"物品图标\\马达\\马达5.blp",
		"goldCost":1200.0,
		"pawnable":1,
		"attribute":{
			"move_speed":120
		}
	},
	{
		"id":"马达Lv6",
		"class":"基础属性装备",
		"passive":true,
		"name":"马达Lv6",
		"describe":"移动速度+160",
		"icon":"物品图标\\马达\\马达6.blp",
		"goldCost":1600.0,
		"pawnable":1,
		"attribute":{
			"move_speed":160
		}
	},
	{
		"id":"马达Lv7",
		"class":"基础属性装备",
		"passive":true,
		"name":"马达Lv7",
		"describe":"移动速度+200",
		"icon":"物品图标\\马达\\马达7.blp",
		"goldCost":2000.0,
		"pawnable":1,
		"attribute":{
			"move_speed":200
		}
	},
	{
		"id":"马达Lv8",
		"class":"基础属性装备",
		"passive":true,
		"name":"马达Lv8",
		"describe":"移动速度+280",
		"icon":"物品图标\\马达\\马达8.blp",
		"goldCost":2800.0,
		"pawnable":1,
		"attribute":{
			"move_speed":280
		}
	},
	{
		"id":"马达Lv9",
		"class":"基础属性装备",
		"passive":true,
		"name":"马达Lv9",
		"describe":"移动速度+360\n全属性+5%",
		"icon":"物品图标\\马达\\马达9.blp",
		"goldCost":3600.0,
		"pawnable":1,
		"attribute":{
			"full_property_p":0.05,
			"move_speed":360
		}
	},
	{
		"id":"马达Lv10",
		"class":"基础属性装备",
		"passive":false,
		"name":"马达Lv10",
		"describe":"移动速度+400\n全属性+10%",
		"icon":"物品图标\\马达\\马达10.blp",
		"goldCost":4000.0,
		"pawnable":1,
		"attribute":{
			"full_property_p":0.1,
			"move_speed":400
		}
	}
]
export const d_马达 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
