//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
import 右键移动时闪现到目的地 from "state/unit/右键移动时闪现到目的地"
import 类双击物品时英雄宝宝交换该物品 from "state/宝宝助手/类双击物品时英雄宝宝交换该物品"
/**
	id = 自定义id
	class = 类别
	templateType = 基础模板
	name = 名字
	icon = 图标
	#<%1%># = 代码配置
	model = 模型
	moveSpeed = 移速
	maxLife = 生命值
	maxMana = 最大魔法值
	def = 护甲
	damage = 攻击力
	damageCd = 攻击间隔
	range = 攻击范围
	missileModel = 投射物模型
	moveType = 移动类型
	flyHeight = 飞行高度
	goldCost = 金币消耗
	describe = 提示说明
*/
export type data_type = {
	id?: string
	class?: string
	templateType?: string
	name?: string
	icon?: string
	model?: string
	moveSpeed?: number
	maxLife?: any
	maxMana?: any
	def?: any
	damage?: any
	damageCd?: any
	range?: any
	missileModel?: any
	moveType?: string
	flyHeight?: number
	goldCost?: any
	describe?: any
    [key:string]: any
}

declare global {
    type t_基础宝宝助手 = data_type
}

export const data: data_type[] = [
	{
		"id":"宝宝助手",
		"class":"宝宝助手",
		"templateType":"宝宝助手",
		"name":"|cffff0000宝宝助手",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNRavenForm.blp",
		"#<%1%>#":"右键移动时闪现到目的地.cfg.push(\"宝宝助手\");",
		"model":"units\\critters\\Vulture\\Vulture.mdx",
		"moveSpeed":522,
		"moveType":"fly",
		"flyHeight":150
	}
]
export const d_基础宝宝助手 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
	右键移动时闪现到目的地.cfg.push("宝宝助手");
}
