//Generated By Solar Editor

/**
	id = id
	_parent = 父id
	Name = 名字
	race = 种族
	Hotkey = 热键 - 普通
	DataA = DataA
	DataB = DataB
	hero = 英雄
	Cost = 魔法消耗
	Cool = 魔法施放时间间隔
	Buttonpos_1 = 按钮位置 - 普通 (X)
	Buttonpos_2 = 按钮位置 - 普通 (Y)
	Ubertip = 提示工具 - 普通 - 扩展
	targs = 目标允许
	levels = 等级
*/
export type data_type = {
	id?: string
	_parent?: string
	Name?: string
	race?: string
	Hotkey?: string
	DataA?: any
	DataB?: any
	hero?: number
	Cost?: any
	Cool?: any
	Buttonpos_1?: number
	Buttonpos_2?: number
	Ubertip?: string
	targs?: any
	levels?: number
    [key:string]: any
}

declare global {
    type t_传送 = data_type
}

export const data: data_type[] = [
	{
		"id":"a45d",
		"_parent":"AHmt",
		"Name":"传送(F)",
		"race":" ",
		"Hotkey":"F",
		"DataA":{
			1:"1",
			2:"1"
		},
		"DataB":{
			1:"0.0",
			2:"0.0"
		},
		"hero":0,
		"Cost":{
			1:"0",
			2:"0"
		},
		"Cool":{
			1:"15.0",
			2:"8.0"
		},
		"Buttonpos_1":2,
		"Buttonpos_2":1,
		"Ubertip":"传送到一个友军单位或者建筑物旁边。",
		"targs":{
			1:"friend,ground,structure,invulnerable,allies",
			2:"friend,ground,structure,invulnerable,allies"
		},
		"levels":2,
		"Researchubertip":"传送到一个友军单位或者建筑物旁边。",
		"Tip":"传送(F)"
	}
]
export const d_传送 = data;


//code
export default function(){
}
