//Generated By Solar Editor

/**
	id = id
	_parent = 父id
	Name = 名字
	Ubertip = 提示工具 - 普通 - 扩展
	Area = 影响区域
	DataA = DataA
	DataB = DataB
	DataC = DataC
	reqLevel = 等级要求
	Buttonpos_1 = 按钮位置 - 普通 (X)
	Requires = 需求
	targs = 目标允许
	Missileart = 效果 - 投射物图像
*/
export type data_type = {
	id?: string
	_parent?: string
	Name?: string
	Ubertip?: string
	Area?: number
	DataA?: number
	DataB?: number
	DataC?: number
	reqLevel?: number
	Buttonpos_1?: any
	Requires?: string
	targs?: string
	Missileart?: string
    [key:string]: any
}

declare global {
    type t_多重攻击 = data_type
}

export const data: data_type[] = [
	{
		"id":"a44p",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X2",
		"Ubertip":"远程攻击能攻击2个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":2,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X2",
		"Researchtip":"|cff6495ED多重攻击X2",
		"Tip":"|cff6495ED多重攻击X2"
	},
	{
		"id":"a44q",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X3",
		"Ubertip":"远程攻击能攻击3个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":3,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X3",
		"Researchtip":"|cff6495ED多重攻击X3",
		"Tip":"|cff6495ED多重攻击X3"
	},
	{
		"id":"a44r",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X4",
		"Ubertip":"远程攻击能攻击4个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":4,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X4",
		"Researchtip":"|cff6495ED多重攻击X4",
		"Tip":"|cff6495ED多重攻击X4"
	},
	{
		"id":"a44s",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X5",
		"Ubertip":"远程攻击能攻击5个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":5,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X5",
		"Researchtip":"|cff6495ED多重攻击X5",
		"Tip":"|cff6495ED多重攻击X5"
	},
	{
		"id":"a44t",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X6",
		"Ubertip":"远程攻击能攻击6个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":6,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X6",
		"Researchtip":"|cff6495ED多重攻击X6",
		"Tip":"|cff6495ED多重攻击X6"
	},
	{
		"id":"a44u",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X7",
		"Ubertip":"远程攻击能攻击7个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":7,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X7",
		"Researchtip":"|cff6495ED多重攻击X7",
		"Tip":"|cff6495ED多重攻击X7"
	},
	{
		"id":"a44v",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X8",
		"Ubertip":"远程攻击能攻击8个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":8,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X8",
		"Researchtip":"|cff6495ED多重攻击X8",
		"Tip":"|cff6495ED多重攻击X8"
	},
	{
		"id":"a44w",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X9",
		"Ubertip":"远程攻击能攻击9个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":9,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X9",
		"Researchtip":"|cff6495ED多重攻击X9",
		"Tip":"|cff6495ED多重攻击X9"
	},
	{
		"id":"a44x",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X10",
		"Ubertip":"远程攻击能攻击10个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":10,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X10",
		"Researchtip":"|cff6495ED多重攻击X10",
		"Tip":"|cff6495ED多重攻击X10"
	},
	{
		"id":"a44y",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X11",
		"Ubertip":"远程攻击能攻击11个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":11,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X11",
		"Researchtip":"|cff6495ED多重攻击X11",
		"Tip":"|cff6495ED多重攻击X11"
	},
	{
		"id":"a44z",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X12",
		"Ubertip":"远程攻击能攻击12个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":12,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X12",
		"Researchtip":"|cff6495ED多重攻击X12",
		"Tip":"|cff6495ED多重攻击X12"
	},
	{
		"id":"a450",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X13",
		"Ubertip":"远程攻击能攻击13个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":13,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X13",
		"Researchtip":"|cff6495ED多重攻击X13",
		"Tip":"|cff6495ED多重攻击X13"
	},
	{
		"id":"a451",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X14",
		"Ubertip":"远程攻击能攻击14个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":14,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X14",
		"Researchtip":"|cff6495ED多重攻击X14",
		"Tip":"|cff6495ED多重攻击X14"
	},
	{
		"id":"a452",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X15",
		"Ubertip":"远程攻击能攻击15个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":15,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X15",
		"Researchtip":"|cff6495ED多重攻击X15",
		"Tip":"|cff6495ED多重攻击X15"
	},
	{
		"id":"a453",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X16",
		"Ubertip":"远程攻击能攻击16个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":16,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X16",
		"Researchtip":"|cff6495ED多重攻击X16",
		"Tip":"|cff6495ED多重攻击X16"
	},
	{
		"id":"a454",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X17",
		"Ubertip":"远程攻击能攻击17个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":17,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X17",
		"Researchtip":"|cff6495ED多重攻击X17",
		"Tip":"|cff6495ED多重攻击X17"
	},
	{
		"id":"a455",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X18",
		"Ubertip":"远程攻击能攻击18个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":18,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X18",
		"Researchtip":"|cff6495ED多重攻击X18",
		"Tip":"|cff6495ED多重攻击X18"
	},
	{
		"id":"a456",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X19",
		"Ubertip":"远程攻击能攻击19个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":19,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X19",
		"Researchtip":"|cff6495ED多重攻击X19",
		"Tip":"|cff6495ED多重攻击X19"
	},
	{
		"id":"a457",
		"_parent":"Aroc",
		"Name":"|cff6495ED多重攻击X20",
		"Ubertip":"远程攻击能攻击20个敌人。",
		"Area":800,
		"DataA":0.0,
		"DataB":0.0,
		"DataC":20,
		"reqLevel":1,
		"Requires":" ",
		"targs":"enemies",
		"Missileart":"Abilities\\Weapons\\MoonPriestessMissile\\MoonPriestessMissile.mdl",
		"Researchubertip":"|cff6495ED多重攻击X20",
		"Researchtip":"|cff6495ED多重攻击X20",
		"Tip":"|cff6495ED多重攻击X20"
	}
]
export const d_多重攻击 = data;


//code
export default function(){
}
