//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	name = 名字
	describe = 提示说明
	最大目标数量 = 最大目标数量
	sc_射程 = 射程
	ss_射速 = 射速
	shgs_伤害公式 = 伤害公式
	sh_伤害 = 伤害
	missileModel = 投射物
	colorR = colorR
	colorG = colorG
	colorB = colorB
	alpha = alpha
	ts_特殊 = 特殊
	attribute = attribute
	icon = 图标
	class = 类别
	targetType = 目标类型
	 passive = 是否被动技能
	range = 施放范围
	area = 影响区域
	x = 按钮x
	y = 按钮y
	#<%1%># = 配置代码
*/
export type data_type = {
	id?: string
	name?: string
	describe?: string
	最大目标数量?: any
	sc_射程?: number
	ss_射速?: number
	shgs_伤害公式?: any
	sh_伤害?: string
	missileModel?: string
	colorR?: any
	colorG?: any
	colorB?: any
	alpha?: any
	ts_特殊?: string
	attribute?: any
	icon?: string
	class?: string
	targetType?: string
	passive?: boolean
	range?: number
	area?: number
	x?: number
	y?: number
    [key:string]: any
}

declare global {
    type t_扩展主炮 = data_type
}

export const data: data_type[] = [
	{
		"id":"狂风之力主炮",
		"name":"狂风之力主炮",
		"describe":"射程：300\n伤害：攻击力x1\n射速：1\n特殊：无",
		"sc_射程":300,
		"ss_射速":0.1,
		"shgs_伤害公式":{
			"attack":0.5
		},
		"sh_伤害":"攻击力x0.5",
		"missileModel":"Abilities\\Weapons\\Arrow\\ArrowMissile.mdl",
		"ts_特殊":"无",
		"icon":"船图标\\木船-主炮.blp",
		"class":"主炮",
		"targetType":"无目标",
		"passive":true,
		"range":1000,
		"area":200,
		"x":2,
		"y":2
	}
]
export const d_扩展主炮 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
