//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	targetType = 目标类型
	 passive = 是否被动技能
	name = 名字
	describe = 提示说明
	icon = 图标
	range = 施放范围
	area = 影响区域
	cost = 魔法消耗
	hotKey = 快捷键
	maxCd = 冷却
	x = 按钮x
	y = 按钮y
	targetAllow = 目标允许
	#<%1%># = 配置代码
*/
export type data_type = {
	id?: string
	class?: string
	targetType?: string
	passive?: boolean
	name?: string
	describe?: string
	icon?: string
	range?: number
	area?: number
	cost?: number
	hotKey?: string
	maxCd?: number
	x?: number
	y?: number
	targetAllow?: string
    [key:string]: any
}

declare global {
    type t_模拟传送 = data_type
}

export const data: data_type[] = [
	{
		"id":"传送",
		"class":"技能",
		"targetType":"单位",
		"passive":false,
		"name":"传送(T)",
		"describe":"传送到一个友军单位或者建筑物旁边。",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNStaffOfTeleportation.blp",
		"range":999999,
		"area":0,
		"cost":0,
		"hotKey":"T",
		"maxCd":15,
		"x":2,
		"y":1,
		"targetAllow":"notself,alive,ground,nonhero,mechanical,structure,vulnerable,air,allies,player,invulnerable,hero"
	}
]
export const d_模拟传送 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
