//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	describe = 提示说明
	targetType = 目标类型
	 passive = 是否被动技能
	name = 名字
	icon = 图标
	range = 施放范围
	area = 影响区域
	cost = 魔法消耗
	hotKey = 快捷键
	maxCd = 冷却
	x = 按钮x
	y = 按钮y
	attribute = 属性附加
	最大目标数量 = 最大目标数量
	sc_射程 = 射程
	ss_射速 = 射速
	shgs_伤害公式 = 伤害公式
	missileModel = 弹道模型
	#<%1%># = 配置代码
*/
export type data_type = {
	id?: string
	class?: string
	describe?: string
	targetType?: string
	passive?: boolean
	name?: string
	icon?: string
	range?: number
	area?: number
	cost?: number
	hotKey?: string
	maxCd?: number
	x?: number
	y?: number
	attribute?: any
	最大目标数量?: any
	sc_射程?: number
	ss_射速?: number
	shgs_伤害公式?: any
	missileModel?: string
    [key:string]: any
}

declare global {
    type t_船长之心技能 = data_type
}

export const data: data_type[] = [
	{
		"id":"船长之心-无敌",
		"class":"船长之心",
		"describe":"无敌2秒，冷却5秒。",
		"targetType":"无目标",
		"passive":false,
		"name":"船长之心-无敌",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNGreaterInvulneralbility.blp",
		"range":1000,
		"area":200,
		"cost":0,
		"hotKey":"W",
		"maxCd":5,
		"x":0,
		"y":2
	},
	{
		"id":"船长之心-岛主",
		"class":"船长之心",
		"describe":"船长之心-岛主：\n射程：200\n伤害：50000+攻击力x1\n射速：0.5\n特殊：该主炮造成真实伤害。",
		"targetType":"无目标",
		"passive":true,
		"name":"船长之心-岛主",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNManaShield.blp",
		"range":1000,
		"area":200,
		"cost":0,
		"maxCd":0,
		"x":0,
		"y":2,
		"sc_射程":200,
		"ss_射速":0.5,
		"shgs_伤害公式":{
			"base":50000.0,
			"attack":1.0
		},
		"missileModel":"Abilities\\Weapons\\Rifle\\RifleImpact.mdx"
	},
	{
		"id":"船长之心-变羊",
		"class":"船长之心",
		"describe":"船长之心-变羊：将身边400范围的敌人变羊5秒，冷却15秒。",
		"targetType":"无目标",
		"passive":false,
		"name":"船长之心-变羊",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNPolymorph.blp",
		"range":1000,
		"area":200,
		"cost":0,
		"hotKey":"W",
		"maxCd":15,
		"x":0,
		"y":2
	},
	{
		"id":"船长之心-酋长",
		"class":"船长之心",
		"describe":"船长之心-酋长：全图友军攻击力+500%，持续10秒，冷却60秒。",
		"targetType":"无目标",
		"passive":false,
		"name":"船长之心-酋长",
		"icon":"ReplaceableTextures\\CommandButtons\\BTNBloodLustOn.blp",
		"range":1000,
		"area":200,
		"cost":0,
		"hotKey":"W",
		"maxCd":60,
		"x":0,
		"y":2
	}
]
export const d_船长之心技能 = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
