//Generated By Solar Editor

import ActorTypeUtil from "@/ActorTypeUtil"
/**
	id = 自定义id
	class = 类别
	name = 名字
	kind = 种类
	describe = 提示说明
	dur = 持续时间
	interval = 间隔
	levelMax = 叠加层数上限
	attribute = buff附加属性
	priority = 优先级
	isDebuff = 是减益buff
	levelDurMode = 每层buff独立计时
	icon = 图标
	modelAttachTarget = 目标附加点
	model = 目标附加模型
*/
export type data_type = {
	id?: string
	class?: string
	name?: string
	kind?: any
	describe?: string
	dur?: any
	interval?: number
	levelMax?: any
	attribute?: any
	priority?: any
	isDebuff?: boolean
	levelDurMode?: boolean
	icon?: string
	modelAttachTarget?: string
	model?: string
    [key:string]: any
}

declare global {
    type t_进攻怪加强buff = data_type
}

export const data: data_type[] = [
	{
		"id":"踏尘者寄生",
		"class":"基础",
		"name":"踏尘者寄生",
		"describe":"被踏尘者寄生，攻击力/移速/生命值+100%",
		"attribute":{
			"attack_p":1.0,
			"life_p":1.0,
			"move_speed_p":1.0
		},
		"isDebuff":false,
		"levelDurMode":true,
		"icon":"ReplaceableTextures\\CommandButtons\\BTNParasiteOn.blp",
		"modelAttachTarget":"origin",
		"model":"Abilities\\Spells\\Other\\Parasite\\ParasiteTarget.mdl"
	},
	{
		"id":"狂风之力",
		"class":"基础",
		"name":"狂风之力",
		"describe":"被狂风之力眷顾，攻速/移速+100%",
		"attribute":{
			"attack_p":1.0,
			"move_speed_p":1.0
		},
		"isDebuff":false,
		"levelDurMode":true,
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCyclone.blp",
		"modelAttachTarget":"origin",
		"model":"Abilities\\Spells\\Other\\Tornado\\Tornado_Target.mdl"
	},
	{
		"id":"犹格索托斯之力",
		"class":"基础",
		"name":"犹格索托斯之力",
		"describe":"犹格索托斯之力，范围300献祭，1000+最大生命值10%的真实伤害（多个来源可叠加）",
		"interval":1,
		"isDebuff":false,
		"levelDurMode":true,
		"icon":"ReplaceableTextures\\CommandButtons\\BTNCloakOfFlames.blp",
		"modelAttachTarget":"origin",
		"model":"Abilities\\Spells\\NightElf\\Immolation\\ImmolationDamage.mdl"
	}
]
export const d_进攻怪加强buff = data;


//code
export default function(){

    for (let datum of data) {
        if (datum.id) {
            ActorTypeUtil.registerActorType(datum as any);
        }
    }
}
