import 基础指令 from "state/common/基础指令";
// import 无文字模式 from "state/common/无文字模式";
import 平台存档等地图相关奖励 from "state/存档/平台存档等地图相关奖励";
import UiProperty from "gui/UiProperty";
import 英雄增伤 from "attribute/英雄增伤";
import 每秒加属性 from "attribute/每秒加属性";
import 怪物死亡时刷新怪物 from "state/玩法机制/怪物死亡时刷新怪物";
import 受到伤害时限制最大伤害值为生命值比例 from "state/单位/受到伤害时限制最大伤害值为生命值比例";
import 造成伤害时附带目标最大生命值比例的伤害 from "state/单位/造成伤害时附带目标最大生命值比例的伤害";
import 开局刷新平台房间栏位信息 from "state/存档/开局刷新平台房间栏位信息";
import 类双击物品时英雄宝宝交换该物品 from "state/宝宝助手/类双击物品时英雄宝宝交换该物品";
import 右键移动时闪现到目的地 from "state/unit/右键移动时闪现到目的地";
import 快速建造 from "attribute/玩家属性/快速建造";
import 英雄升级增幅 from "attribute/玩家属性/英雄升级增幅";
import 给与玩家奖励系统 from "state/module/给与玩家奖励系统";
import 图标面板 from "界面/图标面板/图标面板";
import 英雄属性书 from "state/物品/英雄属性书";
import 达尔文进化基础刷怪 from "state/刷怪系统/达尔文进化基础刷怪";
import AA_split_damage from "attribute/AA_split_damage";
import 杀敌时加属性 from "attribute/杀敌时加属性";
import AA_reply_life_on_pers from "attribute/AA_reply_life_on_pers";
import 开局给Npc头上创建名字 from "state/系统/开局给Npc头上创建名字";
import 每秒资源 from "attribute/玩家属性/每秒资源";
import HeroReviveOnDeath from "state/common/HeroReviveOnDeath";
import SolarNewItemsFormulaState from "state/common/SolarNewItemsFormulaState";
import BaseMultiboardState from "state/module/BaseMultiboardState";
import UpdateCameraHeightOnMouseScroll from "state/common/UpdateCameraHeightOnMouseScroll";

export default function StateInit() {

    new UpdateCameraHeightOnMouseScroll();
    new BaseMultiboardState();
    new SolarNewItemsFormulaState();
    // new MapBaseInitState();
    // new GameDifficultyChooseDialogState();
    new HeroReviveOnDeath();
    new 每秒资源();
    new 开局给Npc头上创建名字();
    new AA_reply_life_on_pers();
    new 杀敌时加属性();
    new AA_split_damage();
    new 达尔文进化基础刷怪();
    new 英雄属性书();
    new 图标面板();
    new 给与玩家奖励系统();
    new 英雄升级增幅();
    new 快速建造();
    new 右键移动时闪现到目的地();
    new 类双击物品时英雄宝宝交换该物品();
    new 开局刷新平台房间栏位信息();
    new 造成伤害时附带目标最大生命值比例的伤害();
    new 受到伤害时限制最大伤害值为生命值比例();
    new 怪物死亡时刷新怪物();
    new 每秒加属性();
    new 英雄增伤();
    new UiProperty();
    new 平台存档等地图相关奖励();
    // new 无文字模式();
    new 基础指令();
}