//Generated By Solar Editor

import UpdateCameraHeightOnMouseScroll from "state/common/UpdateCameraHeightOnMouseScroll"
import BaseMultiboardState from "state/module/BaseMultiboardState"
import SolarNewItemsFormulaState from "state/common/SolarNewItemsFormulaState"
/**
	state_name = 配置项名字
	#<%1%># = 配置代码
*/
export type data_type = {
	state_name?: string
    [key:string]: any
}

declare global {
    type t_基础通用模块 = data_type
}

export const data: data_type[] = [
	{
		"state_name":"鼠标轮滑滚动",
		"#<%1%>#":"import UpdateCameraHeightOnMouseScroll from \"state/common/UpdateCameraHeightOnMouseScroll\";"
	},
	{
		"state_name":"基础多面板",
		"#<%1%>#":"import BaseMultiboardState from \"state/module/BaseMultiboardState\";"
	},
	{
		"state_name":"基础物品合成系统",
		"#<%1%>#":"import SolarNewItemsFormulaState from \"state/common/SolarNewItemsFormulaState\";"
	}
]
export const d_基础通用模块 = data;


//code
export default function(){
}
